// SPDX-License-Identifier: GPL-3.0-only
//! Reverse translation of shrunk `java/**` class names.
//!
//! `tools/class-shrink` may rename the `java/**` classes a class file refers
//! to — `java/lang/String` → `b/C` — in both the framework corpus and app
//! PAPKs (`sdk/shrink-maps/`, namespace `b/`). This JVM serves those classes
//! natively and matches them by their original names everywhere
//! (`BUILTIN_CLASS_NAMES`, `BUILTIN_SUPER`, the exception sites, dispatch),
//! so the shrunk spelling is undone at the one place it enters: the
//! `ClassFile` accessors that turn a `CONSTANT_Class` into a name. Nothing
//! past that boundary sees a `b/` name, and a class file that still spells
//! the original (a PAPK shrunk with an older map, or none) works unchanged.
//!
//! Descriptors are left as stored (`(Lb/C;)V`); comparisons that must see
//! through them use [`desc_eq`] / [`desc_starts_with`].
//!
//! The table is generated by `jvm/build.rs` from the active map when the
//! build runs with `PICODROID_SHRINK=1`; otherwise it is empty and every
//! function here is a passthrough. `a/` (framework) names are not the JVM's
//! business — picodroid-core reverse-translates those at dispatch.

// Defines `JAVA_ORIGINALS` (and `JAVA_SHRINK_PAIRS` under cfg(test)).
include!(concat!(env!("OUT_DIR"), "/java_names.rs"));

const PREFIX: &[u8] = b"b/";

/// Reverse-translate a shrunk `b/…` class name to its original `java/**`
/// form. Anything else — original names, `a/` framework names, app classes,
/// array descriptors such as `[Lb/A;` — passes through untouched. A hit is
/// returned from one `static`, so repeated calls hand back the same pointer
/// (the interpreter's resolution caches key on it).
#[inline]
pub fn unshrink_java(name: &[u8]) -> &[u8] {
    if name.len() > PREFIX.len() && name.starts_with(PREFIX) {
        if let Some(original) = lookup(&name[PREFIX.len()..]) {
            return original.as_bytes();
        }
    }
    name
}

/// [`unshrink_java`] for `&str`.
#[inline]
pub fn unshrink_java_str(name: &str) -> &str {
    if name.len() > PREFIX.len() && name.as_bytes().starts_with(PREFIX) {
        if let Some(original) = lookup(&name.as_bytes()[PREFIX.len()..]) {
            return original;
        }
    }
    name
}

/// Decode a bijective base-26 suffix (`A`=0 … `Z`=25, `AA`=26 — the
/// allocator in `tools/class-shrink/src/rename.rs`) and look it up.
#[inline(never)]
fn lookup(suffix: &[u8]) -> Option<&'static str> {
    if JAVA_ORIGINALS.is_empty() {
        return None;
    }
    let mut n: usize = 0;
    for &b in suffix {
        if !b.is_ascii_uppercase() {
            return None;
        }
        n = n.checked_mul(26)?.checked_add((b - b'A' + 1) as usize)?;
    }
    let original = *JAVA_ORIGINALS.get(n.checked_sub(1)?)?;
    (!original.is_empty()).then_some(original)
}

/// Descriptor equality that sees through shrunk `java/**` class names: each
/// `L…;` object type is compared by its reverse-translated name, every other
/// byte verbatim. Symmetric, so a Rust literal, a class file shrunk with the
/// current map and one shrunk with an older map all compare equal.
///
/// With an empty table no `java/**` name has two spellings, so the walk can
/// never disagree with the byte compare; the `is_empty()` guard is a
/// compile-time constant that lets a no-shrink build drop [`walk`] outright.
pub fn desc_eq(a: &[u8], b: &[u8]) -> bool {
    a == b || (!JAVA_ORIGINALS.is_empty() && walk(a, b, false))
}

/// `desc.starts_with(prefix)` with the translation of [`desc_eq`].
pub fn desc_starts_with(desc: &[u8], prefix: &[u8]) -> bool {
    desc.starts_with(prefix) || (!JAVA_ORIGINALS.is_empty() && walk(desc, prefix, true))
}

/// Compare two descriptor token streams; `prefix` stops when `b` runs out.
fn walk(a: &[u8], b: &[u8], prefix: bool) -> bool {
    let (mut i, mut j) = (0usize, 0usize);
    loop {
        match (a.get(i), b.get(j)) {
            (_, None) => return prefix || i == a.len(),
            (None, Some(_)) => return false,
            (Some(&ca), Some(&cb)) => {
                if ca == b'L' && cb == b'L' {
                    let Some(ea) = a[i + 1..].iter().position(|&x| x == b';') else {
                        return false;
                    };
                    let Some(eb) = b[j + 1..].iter().position(|&x| x == b';') else {
                        return false;
                    };
                    if unshrink_java(&a[i + 1..i + 1 + ea]) != unshrink_java(&b[j + 1..j + 1 + eb])
                    {
                        return false;
                    }
                    i += ea + 2;
                    j += eb + 2;
                } else if ca == cb {
                    i += 1;
                    j += 1;
                } else {
                    return false;
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Real in the shrink lane of `scripts/test.sh`, vacuous otherwise.
    #[test]
    fn active_map_round_trips() {
        for &(shrunk, original) in JAVA_SHRINK_PAIRS {
            assert_eq!(unshrink_java(shrunk.as_bytes()), original.as_bytes());
            assert_eq!(unshrink_java_str(shrunk), original);
            assert_eq!(
                unshrink_java_str(original),
                original,
                "originals pass through"
            );
            assert_eq!(
                unshrink_java_str(shrunk).as_ptr(),
                unshrink_java_str(shrunk).as_ptr(),
                "one static per name — the resolution caches key on the pointer"
            );
        }
    }

    #[test]
    fn unmapped_names_pass_through() {
        for n in [
            "b/",
            "b/foo",
            "b/A1",
            "a/A",
            "java/lang/Object",
            "[Lb/A;",
            "bb/A",
            "b/ZZZZ",
        ] {
            if JAVA_SHRINK_PAIRS.iter().all(|&(s, _)| s != n) {
                assert_eq!(unshrink_java_str(n), n);
                assert_eq!(unshrink_java(n.as_bytes()), n.as_bytes());
            }
        }
    }

    #[test]
    fn descriptor_compares_see_through_shrunk_segments() {
        assert!(desc_eq(b"(IJ)V", b"(IJ)V"));
        assert!(!desc_eq(b"(I)V", b"(J)V"));
        assert!(!desc_eq(b"(Lx/Y;)V", b"(Lx/Z;)V"));
        assert!(!desc_eq(b"(Lx/Y;)V", b"(Lx/Y;)I"));
        assert!(!desc_eq(b"(Lx/Y;)V", b"(Lx/Y;"));
        assert!(desc_starts_with(b"(Lx/Y;I)V", b"(Lx/Y;"));
        assert!(!desc_starts_with(b"(Lx/Z;I)V", b"(Lx/Y;"));
        assert!(!desc_starts_with(b"(I)V", b"(Lx/Y;"));
        for &(shrunk, original) in JAVA_SHRINK_PAIRS {
            let a = alloc::format!("(L{shrunk};I)L{shrunk};");
            let b = alloc::format!("(L{original};I)L{original};");
            assert!(desc_eq(a.as_bytes(), b.as_bytes()), "{a} vs {b}");
            assert!(desc_eq(b.as_bytes(), a.as_bytes()), "{b} vs {a}");
            let p = alloc::format!("(L{original};");
            assert!(desc_starts_with(a.as_bytes(), p.as_bytes()));
            assert!(!desc_eq(a.as_bytes(), b"(Lx/Y;I)Lx/Y;"));
        }
    }
}
