// SPDX-License-Identifier: GPL-3.0-only
//! Builds the trust store: every `roots/*.der` (sorted by name) plus the
//! optional `PICODROID_TLS_EXTRA_CA` (a DER file: the nightly's test CA)
//! becomes an `Anchor` in `OUT_DIR/anchors.rs`, with its Subject Name TLV
//! precomputed so the verifier can match a chain entry's Issuer against it
//! with a byte compare.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

#[path = "src/der_lite.rs"]
#[allow(dead_code)]
mod der_lite;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let roots_dir = manifest.join("roots");
    println!("cargo:rerun-if-changed={}", roots_dir.display());
    println!("cargo:rerun-if-env-changed=PICODROID_TLS_EXTRA_CA");

    let mut files: Vec<PathBuf> = std::fs::read_dir(&roots_dir)
        .expect("pd-tls: roots/ directory")
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().map(|x| x == "der").unwrap_or(false))
        .collect();
    files.sort();
    let mut anchors: Vec<(String, PathBuf)> = files
        .into_iter()
        .map(|p| {
            println!("cargo:rerun-if-changed={}", p.display());
            (p.file_stem().unwrap().to_string_lossy().into_owned(), p)
        })
        .collect();

    // The nightly's test CA, or a developer's: appended, never committed.
    if let Ok(extra) = std::env::var("PICODROID_TLS_EXTRA_CA") {
        for (i, path) in extra.split(':').filter(|s| !s.is_empty()).enumerate() {
            let p = Path::new(path);
            assert!(
                p.is_file(),
                "PICODROID_TLS_EXTRA_CA names a file that does not exist: {path}"
            );
            println!("cargo:rerun-if-changed={}", p.display());
            anchors.push((format!("extra_ca_{i}"), p.to_path_buf()));
        }
    }

    let mut src = String::new();
    src.push_str("// Generated by pd-tls/build.rs — the compiled-in trust store.\n");
    src.push_str("pub static ANCHORS: &[Anchor] = &[\n");
    for (name, path) in &anchors {
        let der = std::fs::read(path).unwrap();
        let names = der_lite::cert_names(&der)
            .unwrap_or_else(|| panic!("pd-tls: {} is not an X.509 certificate", path.display()));
        let subject = &der[names.subject];
        assert!(
            !subject.is_empty(),
            "pd-tls: empty subject in {}",
            path.display()
        );
        writeln!(src, "    Anchor {{").unwrap();
        writeln!(src, "        name: {name:?},").unwrap();
        write!(src, "        subject: &[").unwrap();
        for (i, b) in subject.iter().enumerate() {
            if i % 16 == 0 {
                src.push_str("\n            ");
            }
            write!(src, "0x{b:02x}, ").unwrap();
        }
        src.push_str("\n        ],\n");
        writeln!(
            src,
            "        der: include_bytes!({:?}),",
            path.canonicalize().unwrap().display().to_string()
        )
        .unwrap();
        src.push_str("    },\n");
    }
    src.push_str("];\n");
    std::fs::write(out.join("anchors.rs"), src).unwrap();
}
