// SPDX-License-Identifier: GPL-3.0-only
// The build_support modules are shared with picodroid-core/build.rs; each
// caller uses a subset, so unused items here are expected.
#![allow(dead_code, unused_imports, unused_variables)]
//! Build-script orchestrator. Submodules under `build_support/` own each
//! concern (config discovery, board-derived codegen, FreeRTOS compile, LVGL
//! compile, networking, PAPK/APK embedding). This file wires them together.
//!
//! Board-derived *neutral* config (JVM sizing, sensor table, button table,
//! sleep, heap, background pool, handle table) is generated by
//! `build_support/board_cfg.rs`, which `picodroid-core/build.rs` also calls —
//! one generator, two OUT_DIRs. Only pin-bearing artifacts and the C builds
//! are emitted here. See `docs/designs/shared-core-extraction.md` §3.D.

#[path = "../../build_support/config.rs"]
mod config;

#[path = "../../build_support/board_cfg.rs"]
mod board_cfg;

#[path = "../../build_support/boards.rs"]
mod boards;

#[path = "../../build_support/freertos.rs"]
mod freertos;

#[path = "../../build_support/lvgl.rs"]
mod lvgl;

#[path = "../../build_support/network.rs"]
mod network;

#[path = "../../build_support/papk.rs"]
mod papk;

#[path = "../../build_support/jvm_defaults.rs"]
mod jvm_defaults;

use std::env;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // platforms/rp → platforms → repo root
    let repo_root = manifest_dir
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let is_embedded = matches!(target_arch.as_str(), "arm" | "xtensa");

    // Parse board config for the active board (both ARM and sim).
    let board = board_cfg::resolve(&manifest_dir);

    // Emit OUT_DIR/board_imports.rs so src/boards/mod.rs can include the
    // active board's mod.rs (or no-op when no board is active).
    boards::emit_board_imports(out, board.as_ref().map(|b| b.name.as_str()));

    if is_embedded {
        let b = board
            .as_ref()
            .expect("No board feature active — enable board-testbench or similar");

        let mcu_name = config::resolve_active_mcu(&b.cfg.props);
        let mcu_toml_path = config::find_mcu_toml_in(&b.platform_root, &mcu_name);
        let mcu = config::parse_toml(&mcu_toml_path);
        println!("cargo:rerun-if-changed={mcu_toml_path}");

        let mcu_family = mcu
            .get("family")
            .cloned()
            .unwrap_or_else(|| panic!("MCU toml missing 'family': {mcu_toml_path}"));

        if mcu_family == "rp" {
            let freertos_config_dir = format!("mcus/{mcu_family}");
            boards::place_memory_x(out, &b.cfg.props, &mcu_family, &mcu_name);
            freertos::build(
                out,
                &mcu,
                &mcu_toml_path,
                &mcu_family,
                &freertos_config_dir,
                &repo_root,
            );

            if b.cfg.props.get("network_type").map(String::as_str) == Some("cyw43") {
                let heap_kb = board_cfg::mcu_heap_kb(&mcu, &mcu_toml_path);
                network::build_cyw43_driver(&mcu_family, &freertos_config_dir, &repo_root, heap_kb);
                network::build_freertos_tcp(&mcu_family, &freertos_config_dir, &repo_root, heap_kb);
            }
        }
    }

    // Board-derived neutral config — the same generator picodroid-core runs.
    // `Pins::Owned`: this crate emits its own display/touch pin artifacts
    // (and their has_display / has_touch cfgs) just below.
    board_cfg::emit_neutral(out, &board, board_cfg::Pins::Owned);

    // Pin-bearing artifacts consumed by this family's HAL.
    let board_display = board.as_ref().and_then(|b| b.cfg.display.clone());
    let board_touch = board.as_ref().and_then(|b| b.cfg.touch.clone());
    config::emit_display_config(out, &board_display);
    emit_touch_config(out, &board_touch);

    // JVM-crate env vars (safety net for direct cargo invocations).
    board_cfg::emit_jvm_env_vars(&board);

    // LVGL applies to both ARM and sim builds.
    let board_props = board.as_ref().map(|b| b.cfg.props.clone());
    lvgl::build(out, &board_props, &repo_root);

    papk::emit_framework_map_version(out, &repo_root);
    papk::embed_framework_classes(out, &repo_root);
    papk::embed_apk(out, is_embedded);
    papk::embed_papk_flash_init(out, is_embedded);
}

/// Emit `OUT_DIR/touch_config.rs` — the XPT2046 pin/calibration wiring for
/// `hal/rp/touch.rs` and `hal/sim/touch.rs`. Pin-bearing, so it stays with
/// the family; shared code only needs the `has_touch` cfg.
fn emit_touch_config(
    out: &std::path::Path,
    touch: &Option<std::collections::HashMap<String, String>>,
) {
    println!("cargo:rustc-check-cfg=cfg(has_touch)");

    let mut code = String::from("// Generated by build.rs — do not edit\n\n");

    if let Some(t) = touch {
        println!("cargo:rustc-cfg=has_touch");

        let get = |key: &str| -> &str {
            t.get(key)
                .unwrap_or_else(|| panic!("[touch] missing '{key}'"))
                .as_str()
        };

        code.push_str(&format!(
            "pub const TOUCH_SPI_FREQ: u32 = {};\n",
            get("spi_freq")
        ));
        code.push_str(&format!(
            "pub const TOUCH_PIN_CS: u8 = {};\n",
            get("pin_cs")
        ));
        code.push_str(&format!(
            "pub const TOUCH_PIN_IRQ: u8 = {};\n",
            get("pin_irq")
        ));
        code.push_str(&format!(
            "pub const TOUCH_PIN_MISO: u8 = {};\n",
            get("pin_miso")
        ));
        code.push_str(&format!(
            "pub const TOUCH_CAL_X_MIN: u16 = {};\n",
            get("cal_x_min")
        ));
        code.push_str(&format!(
            "pub const TOUCH_CAL_X_MAX: u16 = {};\n",
            get("cal_x_max")
        ));
        code.push_str(&format!(
            "pub const TOUCH_CAL_Y_MIN: u16 = {};\n",
            get("cal_y_min")
        ));
        code.push_str(&format!(
            "pub const TOUCH_CAL_Y_MAX: u16 = {};\n",
            get("cal_y_max")
        ));

        let swap = t.get("swap_xy").map_or("false", |v| v.as_str());
        code.push_str(&format!("pub const TOUCH_SWAP_XY: bool = {swap};\n"));
    }

    let path = out.join("touch_config.rs");
    let mut f = File::create(&path).expect("create touch_config.rs");
    f.write_all(code.as_bytes()).expect("write touch_config.rs");
}
