// SPDX-License-Identifier: GPL-3.0-only
// The build_support modules are shared with picodroid-core/build.rs; each
// caller uses a subset, so unused items here are expected.
#![allow(dead_code, unused_imports, unused_variables)]
//! Build-script orchestrator. Submodules under `build_support/` own each
//! concern (config discovery, board-derived codegen, FreeRTOS compile, LVGL
//! compile, networking, PAPK/APK embedding). This file wires them together.
//!
//! Board-derived *neutral* config (JVM sizing, sensor table, button table,
//! sleep, heap, background pool, handle table) is generated by
//! `build_support/board_cfg.rs`, which `picodroid-core/build.rs` also calls —
//! one generator, two OUT_DIRs. Only pin-bearing artifacts and the C builds
//! are emitted here. See `docs/designs/shared-core-extraction.md` §3.D.

#[path = "../../build_support/config.rs"]
mod config;

#[path = "../../build_support/board_cfg.rs"]
mod board_cfg;

#[path = "../../build_support/boards.rs"]
mod boards;

#[path = "../../build_support/freertos.rs"]
mod freertos;

// No `mod lvgl`: LVGL's C sources are compiled by picodroid-core/build.rs,
// and the resulting static lib reaches this binary through the dependency.
// See the note at the bottom of `main`.

#[path = "../../build_support/network.rs"]
mod network;

#[path = "../../build_support/papk.rs"]
mod papk;

#[path = "../../build_support/jvm_defaults.rs"]
mod jvm_defaults;

use std::env;
use std::path::PathBuf;

fn main() {
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // platforms/rp → platforms → repo root
    let repo_root = manifest_dir
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let is_embedded = matches!(target_arch.as_str(), "arm" | "xtensa");

    // Parse board config for the active board (both ARM and sim).
    let board = board_cfg::resolve(&manifest_dir);

    // Emit OUT_DIR/board_imports.rs so src/boards/mod.rs can include the
    // active board's mod.rs (or no-op when no board is active).
    boards::emit_board_imports(out, board.as_ref().map(|b| b.name.as_str()));

    if is_embedded {
        let b = board
            .as_ref()
            .expect("No board feature active — enable board-testbench or similar");

        let mcu_name = config::resolve_active_mcu(&b.cfg.props);
        let mcu_toml_path = config::find_mcu_toml_in(&b.platform_root, &mcu_name);
        let mcu = config::parse_toml(&mcu_toml_path);
        println!("cargo:rerun-if-changed={mcu_toml_path}");

        let mcu_family = mcu
            .get("family")
            .cloned()
            .unwrap_or_else(|| panic!("MCU toml missing 'family': {mcu_toml_path}"));

        if mcu_family == "rp" {
            let freertos_config_dir = format!("mcus/{mcu_family}");
            boards::place_memory_x(out, &b.cfg.props, &mcu_family, &mcu_name);
            freertos::build(
                out,
                &mcu,
                &mcu_toml_path,
                &mcu_family,
                &freertos_config_dir,
                &repo_root,
            );

            if b.cfg.props.get("network_type").map(String::as_str) == Some("cyw43") {
                let heap_kb = board_cfg::mcu_heap_kb(&mcu, &mcu_toml_path);
                let net_overrides = network::net_config_overrides(&b.cfg.props);
                network::build_cyw43_driver(
                    &mcu_family,
                    &freertos_config_dir,
                    &repo_root,
                    heap_kb,
                    &net_overrides,
                );
                network::build_freertos_tcp(
                    &mcu_family,
                    &freertos_config_dir,
                    &repo_root,
                    heap_kb,
                    &net_overrides,
                );
                // wifi_task.rs bakes these in via option_env!; without the
                // rerun hints a credential/auth change is a cargo no-op and
                // the old values stay in the firmware.
                println!("cargo:rerun-if-env-changed=PICODROID_WIFI_SSID");
                println!("cargo:rerun-if-env-changed=PICODROID_WIFI_PASS");
                println!("cargo:rerun-if-env-changed=PICODROID_WIFI_AUTH");
            }
        }
    }

    // Board-derived neutral config — the same generator picodroid-core runs.
    // `Pins::Owned`: this crate emits its own display/touch pin artifacts
    // (and their has_display / has_touch cfgs) just below.
    board_cfg::emit_neutral(out, &board, board_cfg::Pins::Owned);

    // Pin-bearing artifacts consumed by this family's HAL.
    let board_display = board.as_ref().and_then(|b| b.cfg.display.clone());
    let board_touch = board.as_ref().and_then(|b| b.cfg.touch.clone());
    config::emit_display_config(out, &board_display);
    config::emit_touch_config(out, &board_touch);

    // JVM-crate env vars (safety net for direct cargo invocations).
    board_cfg::emit_jvm_env_vars(&board);

    // LVGL is compiled by picodroid-core/build.rs, not here: that crate now
    // holds the code calling `lv_*`, and the resulting static lib propagates
    // to this binary through the dependency. Compiling it in both places
    // would produce duplicate symbols.

    papk::emit_framework_map_version(out, &repo_root);
    papk::embed_framework_classes(out, &repo_root);
    papk::embed_apk(out, is_embedded);
    papk::embed_papk_flash_init(out, is_embedded);
}
