// SPDX-License-Identifier: GPL-3.0-only
// The build_support modules are shared with picodroid-core/build.rs; each
// caller uses a subset, so unused items here are expected.
#![allow(dead_code, unused_imports, unused_variables)]
//! Build-script orchestrator. Submodules under `build_support/` own each
//! concern (config discovery, board-derived codegen, FreeRTOS compile, LVGL
//! compile, networking, PAPK/APK embedding). This file wires them together.
//!
//! Board-derived *neutral* config (JVM sizing, sensor table, button table,
//! sleep, heap, background pool, handle table) is generated by
//! `build_support/board_cfg.rs`, which `picodroid-core/build.rs` also calls —
//! one generator, two OUT_DIRs. Only pin-bearing artifacts and the C builds
//! are emitted here. See `docs/designs/shared-core-extraction.md` §3.D.

#[path = "../../build_support/config.rs"]
mod config;

#[path = "../../build_support/board_cfg.rs"]
mod board_cfg;

#[path = "../../build_support/boards.rs"]
mod boards;

#[path = "../../build_support/freertos.rs"]
mod freertos;

// No `mod lvgl`: LVGL's C sources are compiled by picodroid-core/build.rs,
// and the resulting static lib reaches this binary through the dependency.
// See the note at the bottom of `main`.

#[path = "../../build_support/network.rs"]
mod network;

#[path = "../../build_support/papk.rs"]
mod papk;

#[path = "../../build_support/jvm_defaults.rs"]
mod jvm_defaults;

use std::env;
use std::path::PathBuf;

fn main() {
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = config::repo_root(&manifest_dir);
    let is_embedded = config::is_embedded();

    // Parse board config for the active board (both ARM and sim).
    let board = board_cfg::resolve(&manifest_dir);

    // Emit OUT_DIR/board_imports.rs so src/boards/mod.rs can include the
    // active board's mod.rs (or no-op when no board is active).
    boards::emit_board_imports(out, board.as_ref().map(|b| b.name.as_str()));

    if is_embedded {
        let b = board
            .as_ref()
            .expect("No board feature active — enable board-testbench or similar");

        let mcu_name = config::resolve_active_mcu(&b.cfg.props);
        let mcu_toml_path = config::find_mcu_toml_in(&b.platform_root, &mcu_name);
        let mcu = config::parse_toml(&mcu_toml_path);
        println!("cargo:rerun-if-changed={mcu_toml_path}");

        let mcu_family = mcu
            .get("family")
            .cloned()
            .unwrap_or_else(|| panic!("MCU toml missing 'family': {mcu_toml_path}"));

        if mcu_family == "rp" {
            let freertos_config_dir = format!("mcus/{mcu_family}");
            boards::place_memory_x(out, &b.cfg.props, &mcu_family, &mcu_name);
            freertos::build(
                out,
                &mcu,
                &mcu_toml_path,
                &mcu_family,
                &freertos_config_dir,
                &repo_root,
            );

            // The network: FreeRTOS+TCP plus the shared glue from
            // picodroid-core, plus the link driver this board's
            // `network_type` names (docs/designs/network-seam-2026-09.md).
            if b.cfg.props.get("has_network").map(String::as_str) == Some("true") {
                // board_cfg::emit_network_cfgs already refused a missing or
                // unknown network_type.
                let network_type = b.cfg.props.get("network_type").cloned().unwrap_or_default();
                let heap_kb = board_cfg::mcu_heap_kb(&mcu, &mcu_toml_path);
                let net_overrides = network::net_config_overrides(&b.cfg.props);
                let freertos_port = mcu
                    .get("freertos_port")
                    .unwrap_or_else(|| panic!("MCU toml missing 'freertos_port': {mcu_toml_path}"));
                let kernel_port_include = repo_root
                    .join("third_party/FreeRTOS-Kernel/portable")
                    .join(freertos_port);
                let family_port_dir = format!("src/hal/{mcu_family}/port");
                match network_type.as_str() {
                    "cyw43" => {
                        // Driver first: its one strcmp resolves from the
                        // freertos_tcp archive's libc_str.c.
                        network::build_cyw43_driver(
                            &repo_root,
                            &freertos_config_dir,
                            &kernel_port_include,
                            &family_port_dir,
                            heap_kb,
                            &net_overrides,
                        );
                        let link_sources = [PathBuf::from(format!(
                            "{family_port_dir}/net/NetworkInterface_CYW43.c"
                        ))];
                        let extra_includes = [repo_root.join("vendor/cyw43-driver/src")];
                        let extra_defines = [
                            (
                                "CYW43_CONFIG_FILE".to_string(),
                                Some("\"cyw43_configport.h\"".to_string()),
                            ),
                            ("CYW43_USE_SPI".to_string(), Some("1".to_string())),
                            ("CYW43_LWIP".to_string(), Some("0".to_string())),
                        ];
                        network::build_freertos_tcp(&network::NetStackBuild {
                            repo_root: &repo_root,
                            freertos_config_dir: &freertos_config_dir,
                            kernel_port_include: &kernel_port_include,
                            family_port_dir: &family_port_dir,
                            heap_kb,
                            overrides: &net_overrides,
                            link_sources: &link_sources,
                            extra_includes: &extra_includes,
                            extra_defines: &extra_defines,
                        });
                        // hal/rp/wifi_task.rs bakes these in via option_env!;
                        // without the rerun hints a credential/auth change is
                        // a cargo no-op and the old values stay in the firmware.
                        println!("cargo:rerun-if-env-changed=PICODROID_WIFI_SSID");
                        println!("cargo:rerun-if-env-changed=PICODROID_WIFI_PASS");
                        println!("cargo:rerun-if-env-changed=PICODROID_WIFI_AUTH");
                    }
                    other => panic!(
                        "platforms/rp/build.rs: no link driver for network_type '{other}' \
                         (add a match arm and a NetworkInterface_<X>.c)"
                    ),
                }
            }
        }
    }

    // Board-derived neutral config — the same generator picodroid-core runs.
    // `Pins::Owned`: this crate emits its own display/touch pin artifacts
    // (and their has_display / has_touch cfgs) just below.
    board_cfg::emit_neutral(out, &board, board_cfg::Pins::Owned);

    // Pin-bearing artifacts consumed by this family's HAL.
    let board_display = board.as_ref().and_then(|b| b.cfg.display.clone());
    let board_touch = board.as_ref().and_then(|b| b.cfg.touch.clone());
    config::emit_display_config(out, &board_display);
    config::emit_touch_config(out, &board_touch);

    // JVM-crate env vars (safety net for direct cargo invocations).
    board_cfg::emit_jvm_env_vars(&board);

    // LVGL is compiled by picodroid-core/build.rs, not here: that crate now
    // holds the code calling `lv_*`, and the resulting static lib propagates
    // to this binary through the dependency. Compiling it in both places
    // would produce duplicate symbols.

    papk::emit_framework_map_version(out, &repo_root);
    papk::embed_framework_classes(
        out,
        &repo_root,
        &board_cfg::framework_class_excludes(&board),
    );
    papk::embed_apk(out, is_embedded);
    papk::embed_papk_flash_init(out, is_embedded);
}
