# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usage.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'usage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busage.proto\x12\x0b\x63laudeusage\"$\n\x06Window\x12\x0b\n\x03pct\x18\x01 \x01(\x05\x12\r\n\x05reset\x18\x02 \x01(\x03\"4\n\x08ModelCap\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03pct\x18\x02 \x01(\x05\x12\r\n\x05reset\x18\x03 \x01(\x03\":\n\x05Today\x12\x10\n\x08tokens_k\x18\x01 \x01(\x05\x12\r\n\x05\x63\x65nts\x18\x02 \x01(\x05\x12\x10\n\x08messages\x18\x03 \x01(\x05\"\'\n\nModelShare\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03pct\x18\x02 \x01(\x05\"\x92\x03\n\nUsageReply\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x13\n\x0b\x62ridge_time\x18\x02 \x01(\x03\x12\x12\n\ntz_minutes\x18\x03 \x01(\x11\x12\n\n\x02ok\x18\x04 \x01(\x08\x12\x0b\n\x03\x65rr\x18\x05 \x01(\t\x12\r\n\x05\x61ge_s\x18\x06 \x01(\x05\x12\x0c\n\x04plan\x18\x07 \x01(\t\x12$\n\x07session\x18\x08 \x01(\x0b\x32\x13.claudeusage.Window\x12#\n\x06weekly\x18\t \x01(\x0b\x32\x13.claudeusage.Window\x12)\n\nmodel_caps\x18\n \x03(\x0b\x32\x15.claudeusage.ModelCap\x12\x15\n\rrate_per_hour\x18\x0b \x01(\x05\x12\x13\n\x0b\x65ta_minutes\x18\x0c \x01(\x05\x12!\n\x05today\x18\r \x01(\x0b\x32\x12.claudeusage.Today\x12\x14\n\x0c\x64\x61y_tokens_k\x18\x0e \x03(\x05\x12\x13\n\x0b\x64\x61y_letters\x18\x0f \x01(\t\x12$\n\x03mix\x18\x10 \x03(\x0b\x32\x17.claudeusage.ModelShareB\x15\n\x11\x63laudeusage.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021claudeusage.protoP\001'
  _globals['_WINDOW']._serialized_start=28
  _globals['_WINDOW']._serialized_end=64
  _globals['_MODELCAP']._serialized_start=66
  _globals['_MODELCAP']._serialized_end=118
  _globals['_TODAY']._serialized_start=120
  _globals['_TODAY']._serialized_end=178
  _globals['_MODELSHARE']._serialized_start=180
  _globals['_MODELSHARE']._serialized_end=219
  _globals['_USAGEREPLY']._serialized_start=222
  _globals['_USAGEREPLY']._serialized_end=624
# @@protoc_insertion_point(module_scope)
