//! Build-script orchestrator. Submodules under `build_support/` own each
//! concern (config discovery, FreeRTOS compile, LVGL compile, networking,
//! PAPK/APK embedding). This file wires them together.

#[path = "build_support/config.rs"]
mod config;

#[path = "build_support/boards.rs"]
mod boards;

#[path = "build_support/freertos.rs"]
mod freertos;

#[path = "build_support/lvgl.rs"]
mod lvgl;

#[path = "build_support/network.rs"]
mod network;

#[path = "build_support/papk.rs"]
mod papk;

use std::env;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let is_arm_embedded = target_arch == "arm";

    let mut sensors = Vec::new();

    if is_arm_embedded {
        let board_name = config::resolve_active_board()
            .expect("No board feature active — enable board-testbench or similar");
        let board_toml_path = format!("boards/{board_name}/board.toml");
        let board = config::parse_board_toml(&board_toml_path);
        println!("cargo:rerun-if-changed={board_toml_path}");

        sensors = board.sensors.clone();

        let mcu_name = config::resolve_active_mcu(&board.props);
        let mcu_toml_path = config::find_mcu_toml(&mcu_name);
        let mcu = config::parse_toml(&mcu_toml_path);
        println!("cargo:rerun-if-changed={mcu_toml_path}");

        let mcu_family = mcu
            .get("family")
            .cloned()
            .unwrap_or_else(|| panic!("MCU toml missing 'family': {mcu_toml_path}"));

        boards::place_memory_x(out, &board.props, &mcu_family, &mcu_name);

        let freertos_config_dir = format!("mcus/{mcu_family}");
        freertos::build(out, &mcu, &mcu_toml_path, &mcu_family, &freertos_config_dir);

        if env::var("CARGO_FEATURE_NET_CYW43").is_ok() {
            network::build_cyw43_driver(&freertos_config_dir);
            network::build_freertos_tcp(&freertos_config_dir);
        }
    }

    emit_sensor_config(out, &sensors);

    // LVGL applies to both ARM and sim builds.
    let board_cfg = config::resolve_active_board().map(|name| {
        let path = format!("boards/{name}/board.toml");
        config::parse_toml(&path)
    });
    lvgl::build(out, &board_cfg);

    papk::emit_framework_map_version(out);
    papk::embed_framework_classes(out);
    papk::embed_apk(out, is_arm_embedded);
    papk::embed_papk_flash_init(out, is_arm_embedded);
}

fn emit_sensor_config(out: &std::path::Path, sensors: &[config::SensorDecl]) {
    if !sensors.is_empty() {
        println!("cargo:rustc-cfg=any_sensor");
    }
    let mut kinds_seen = std::collections::HashSet::new();
    for s in sensors {
        if kinds_seen.insert(s.kind.clone()) {
            println!("cargo:rustc-cfg=sensor_{}", s.kind);
        }
    }

    let mut code = String::new();
    code.push_str("// Generated by build.rs — do not edit\n\n");
    code.push_str("#[derive(Debug, Clone, Copy)]\n");
    code.push_str("#[repr(u8)]\n");
    code.push_str("pub enum SensorKind {\n");
    code.push_str("    Bme688 = 0,\n");
    code.push_str("}\n\n");
    code.push_str("#[derive(Debug, Clone, Copy)]\n");
    code.push_str("pub struct SensorHwCfg {\n");
    code.push_str("    pub kind: SensorKind,\n");
    code.push_str("    pub bus_id: u8,\n");
    code.push_str("    pub addr: u8,\n");
    code.push_str("}\n\n");

    code.push_str("pub const SENSORS: &[SensorHwCfg] = &[\n");
    for s in sensors {
        let kind_variant = match s.kind.as_str() {
            "bme688" => "Bme688",
            other => panic!("No SensorKind variant for '{other}'"),
        };
        let bus_id = s
            .bus
            .strip_prefix("I2C")
            .unwrap_or_else(|| panic!("unsupported bus '{}', expected I2Cn", s.bus))
            .parse::<u8>()
            .unwrap_or_else(|_| panic!("invalid bus id in '{}'", s.bus));
        code.push_str(&format!(
            "    SensorHwCfg {{ kind: SensorKind::{kind_variant}, bus_id: {bus_id}, addr: 0x{:02X} }},\n",
            s.addr
        ));
    }
    code.push_str("];\n");

    let path = out.join("sensor_table.rs");
    let mut f = File::create(&path).expect("create sensor_table.rs");
    f.write_all(code.as_bytes()).expect("write sensor_table.rs");
}
