// SPDX-License-Identifier: GPL-3.0-only
// Suppress dead-code / unused warnings from the imported build_support modules.
#![allow(dead_code, unused_imports, unused_variables)]

#[path = "../build_support/config.rs"]
mod config;

#[path = "../build_support/papk.rs"]
mod papk;

use std::env;
use std::fs;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // picodroid-esp lives one directory below the repo root.
    let root = manifest_dir
        .parent()
        .expect("picodroid-esp must be a direct subdirectory of the repo root");

    let is_embedded = matches!(
        env::var("CARGO_CFG_TARGET_ARCH")
            .unwrap_or_default()
            .as_str(),
        "arm" | "xtensa"
    );

    // ESP32-S3 memory map — consumed by xtensa-lx-rt's link.x via link-search.
    emit_esp_memory_x(out, "esp32s3");

    // Board capability cfgs — T-Deck Plus M1 has no peripherals enabled yet;
    // emit check-cfg declarations so rustc accepts the cfg names in hal/esp/*.rs.
    for cfg in &[
        "has_display",
        "has_touch",
        "has_network",
        "has_buttons",
        "any_sensor",
        "sensor_bme688",
        "sensor_ltr559",
        "network_cyw43",
    ] {
        println!("cargo:rustc-check-cfg=cfg({cfg})");
    }

    // display_config.rs — included by hal/esp/display.rs.
    // T-Deck Plus M1 board.toml has no [display] section; emit defaults.
    emit_display_config_defaults(out);

    // APK embedding and PAPK flash init.
    papk::embed_apk(out, is_embedded);
    papk::embed_papk_flash_init(out, is_embedded);
    // Framework mapping version for compat check in app.rs.
    papk::emit_framework_map_version(out, root);

    // LVGL: vendor/lvgl/src is relative to picodroid-esp/ and does not exist
    // in M1 (the submodule lives in the root workspace).  lvgl::build returns
    // early when the path is absent — no LVGL link step for M1 ESP builds.
    // No LVGL functions are called in M1 ESP, so unresolved extern symbols do
    // not appear.  A vendor/ symlink or submodule copy enables LVGL for M2+.
}

fn emit_esp_memory_x(out: &std::path::Path, mcu_name: &str) {
    let memory_x = match mcu_name {
        "esp32s3" => concat!(
            "MEMORY {\n",
            "  /* Xtensa exception/interrupt vectors — first 4 KiB of IRAM */\n",
            "  vectors_seg (rx) : ORIGIN = 0x40370000, LENGTH = 4K\n",
            "  /* IRAM: code/data that must run from RAM (interrupt handlers, cache-unsafe) */\n",
            "  RWTEXT (rwx)     : ORIGIN = 0x40371000, LENGTH = 316K\n",
            "  /* 8 MiB flash accessed via cache (XIP read-only) */\n",
            "  ROTEXT (rx)      : ORIGIN = 0x42000000, LENGTH = 4M\n",
            "  RODATA (r)       : ORIGIN = 0x42400000, LENGTH = 4M\n",
            "  /* 512 KiB DRAM (data RAM, read-write) */\n",
            "  RWDATA (rw)      : ORIGIN = 0x3FC80000, LENGTH = 512K\n",
            "}\n",
            "_stack_start_cpu0 = ORIGIN(RWDATA) + LENGTH(RWDATA);\n",
        ),
        other => panic!("No memory.x template for ESP MCU '{other}'"),
    };
    let path = out.join("memory.x");
    let mut f = File::create(&path).expect("create memory.x");
    f.write_all(memory_x.as_bytes()).expect("write memory.x");
    println!("cargo:rustc-link-search={}", out.display());
}

/// Emit display_config.rs with defaults (320×240, band_height=20, scroll_limit=30).
/// T-Deck Plus M1 has no [display] section in board.toml; real values land in M2.
fn emit_display_config_defaults(out: &std::path::Path) {
    println!("cargo:rustc-check-cfg=cfg(has_display)");
    let code = concat!(
        "// Generated by picodroid-esp/build.rs — defaults for M1\n",
        "pub const SCREEN_WIDTH: u16 = 320;\n",
        "pub const SCREEN_HEIGHT: u16 = 240;\n",
        "pub const BAND_HEIGHT: usize = 20;\n",
        "pub const SCROLL_LIMIT: u8 = 30;\n",
    );
    fs::write(out.join("display_config.rs"), code).expect("write display_config.rs");
}
