// SPDX-License-Identifier: GPL-3.0-only
//! Framework class, member and descriptor names as the loaded framework
//! spells them — `c::picodroid_view_View`, `m::setText`, `d::Intent__V`.
//!
//! Generated by `build.rs` (`build_support/names.rs`) from the committed
//! `sdk/class-names.tsv`, `sdk/member-names.tsv`, `sdk/api-contract.tsv`
//! and `sdk/descriptors.tsv`, through the same active shrink map the
//! embedded corpus was rewritten with. Every native-dispatch arm, every
//! `DISPATCH_SITES` row, every `PICODROID_NATIVE_CLASSES` entry and every
//! Rust-side allocation names its Java counterpart through one of these
//! consts, so a `match` arm written `c::picodroid_pio_Gpio =>` compiles to
//! the same code as the literal it replaced in a no-shrink build and to the
//! map's target under `--shrink`. There is no run-time translation in either
//! direction — the `unshrink_class` / `shrink_class` pair this module used to
//! generate is gone, along with the second copy of every name it carried.
//!
//! `pico_jvm::names` is the same module generated into the JVM's `OUT_DIR`
//! from the same inputs; `names_agree_with_pico_jvm` proves the two match.
//! The `#[cfg(test)]` reverse translators (`unshrink_class`, …) serve the
//! tests that compare loaded names against original-name tables.

include!(concat!(env!("OUT_DIR"), "/names.rs"));

#[cfg(test)]
mod tests {
    use super::{c, d, m, unshrink_descriptor, SHRINK_ACTIVE};

    /// Both crates generate their consts from the same inputs through the
    /// same map; a disagreement would be a native miss the shrink lane
    /// alone can catch.
    #[test]
    fn names_agree_with_pico_jvm() {
        assert_eq!(SHRINK_ACTIVE, pico_jvm::names::SHRINK_ACTIVE);
        assert_eq!(c::java_lang_String, pico_jvm::names::c::java_lang_String);
        assert_eq!(c::java_lang_Object, pico_jvm::names::c::java_lang_Object);
        assert_eq!(
            c::picodroid_view_View,
            pico_jvm::names::c::picodroid_view_View
        );
        assert_eq!(m::toString, pico_jvm::names::m::toString);
        assert_eq!(m::onCreate, pico_jvm::names::m::onCreate);
        assert_eq!(d::String__V, pico_jvm::names::d::String__V);
        assert_eq!(
            c::picodroid_concurrent_Thread,
            pico_jvm::names::c::picodroid_concurrent_Thread
        );
        assert_eq!(
            c::java_lang_NullPointerException,
            pico_jvm::names::c::java_lang_NullPointerException
        );
        assert_eq!(m::hashCode, pico_jvm::names::m::hashCode);
        assert_eq!(d::__Class, pico_jvm::names::d::__Class);
    }

    /// `unshrink_descriptor` must invert whatever the active shrink map did
    /// to a descriptor.
    #[test]
    fn unshrink_descriptor_inverts_active_map() {
        assert_eq!(unshrink_descriptor("(IJ)Z"), "(IJ)Z");
        let input = format!(
            "(L{};I)L{};",
            c::picodroid_content_Intent,
            c::picodroid_view_View
        );
        assert_eq!(
            unshrink_descriptor(&input),
            "(Lpicodroid/content/Intent;I)Lpicodroid/view/View;"
        );
        assert_eq!(unshrink_descriptor(d::String__V), "(Ljava/lang/String;)V");
    }

    /// Over the whole embedded corpus no shrunk segment — `a/` or `b/` —
    /// survives `unshrink_descriptor`, and once the active map carries `b/`
    /// entries at least one `java/**` descriptor was actually translated
    /// (otherwise the shrink lane would be silently vacuous).
    #[test]
    fn unshrink_descriptor_covers_java_names_in_the_corpus() {
        let mut shrunk_java_seen = 0;
        for bytes in crate::framework_classes::FRAMEWORK_CLASSES {
            let cf = pico_jvm::class_file::ClassFile::parse(bytes).expect("parse framework class");
            for m in cf.methods() {
                let raw = core::str::from_utf8(cf.cp_utf8(m.descriptor_index).unwrap()).unwrap();
                let un = unshrink_descriptor(raw);
                assert!(
                    !un.contains("La/") && !un.contains("Lb/"),
                    "shrunk segment survived: {raw} -> {un}"
                );
                if raw.contains("Lb/") {
                    shrunk_java_seen += 1;
                    assert!(un.contains("Ljava/"), "{raw} -> {un}");
                }
            }
        }
        if SHRINK_ACTIVE && !crate::framework_classes::FRAMEWORK_CLASSES.is_empty() {
            assert!(
                shrunk_java_seen > 0,
                "the active map shrinks java/** but no framework descriptor carries a b/ name"
            );
        }
    }
}
