// SPDX-License-Identifier: GPL-3.0-only
//! Generates `$OUT_DIR/tunables.rs` from `PICODROID_JVM_*` environment
//! variables. Defaults reproduce the previously-hardcoded values bit-for-bit,
//! so a build without any env override is identical to the pre-tunables JVM.
//!
//! The values are emitted as `pub const`s and `include!`'d into
//! `jvm/src/tunables.rs`, so every use site inlines an immediate operand at
//! compile time — zero RAM cost, no runtime indirection.

use std::env;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));

    println!("cargo:rerun-if-env-changed=PICODROID_JVM_GC_ALLOC_THRESHOLD");
    println!("cargo:rerun-if-env-changed=PICODROID_JVM_SLOT_CHUNK_SHIFT");
    println!("cargo:rerun-if-env-changed=PICODROID_JVM_INLINE_ARRAY_DATA");

    let gc_threshold = read_env_u32("PICODROID_JVM_GC_ALLOC_THRESHOLD", 256, 16, 8192);
    let chunk_shift = read_env_u32("PICODROID_JVM_SLOT_CHUNK_SHIFT", 6, 3, 8);
    let inline_data = read_env_u32("PICODROID_JVM_INLINE_ARRAY_DATA", 8, 0, 32);

    let mut code = String::from("// Generated by jvm/build.rs — do not edit.\n\n");
    code.push_str(&format!("pub const GC_THRESHOLD: u16 = {gc_threshold};\n"));
    code.push_str(&format!("pub const CHUNK_SHIFT: u8 = {chunk_shift};\n"));
    code.push_str("pub const CHUNK_SIZE: usize = 1usize << CHUNK_SHIFT;\n");
    code.push_str("pub const CHUNK_MASK: usize = CHUNK_SIZE - 1;\n");
    code.push_str(&format!("pub const INLINE_DATA: usize = {inline_data};\n"));

    let path = out_dir.join("tunables.rs");
    let mut f = File::create(&path).expect("create tunables.rs");
    f.write_all(code.as_bytes()).expect("write tunables.rs");
}

fn read_env_u32(name: &str, default: u32, min: u32, max: u32) -> u32 {
    let raw = match env::var(name) {
        Ok(v) => v,
        Err(_) => return default,
    };
    let v: u32 = raw
        .parse()
        .unwrap_or_else(|e| panic!("{name}={raw:?}: not a valid u32 ({e})"));
    if v < min || v > max {
        panic!("{name}={v}: out of range (allowed {min}..={max})");
    }
    v
}
