// SPDX-License-Identifier: GPL-3.0-only
//! Generates `$OUT_DIR/tunables.rs` from `PICODROID_JVM_*` environment
//! variables. Defaults reproduce the previously-hardcoded values bit-for-bit,
//! so a build without any env override is identical to the pre-tunables JVM.
//!
//! The values are emitted as `pub const`s and `include!`'d into
//! `jvm/src/tunables.rs`, so every use site inlines an immediate operand at
//! compile time — zero RAM cost, no runtime indirection.

use std::env;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));

    println!("cargo:rerun-if-env-changed=PICODROID_JVM_GC_ALLOC_THRESHOLD");
    println!("cargo:rerun-if-env-changed=PICODROID_JVM_SLOT_CHUNK_SHIFT");
    println!("cargo:rerun-if-env-changed=PICODROID_JVM_INLINE_ARRAY_DATA");

    let gc_threshold = read_env_u32("PICODROID_JVM_GC_ALLOC_THRESHOLD", 256, 16, 8192);
    let chunk_shift = read_env_u32("PICODROID_JVM_SLOT_CHUNK_SHIFT", 6, 3, 8);
    let inline_data = read_env_u32("PICODROID_JVM_INLINE_ARRAY_DATA", 8, 0, 32);

    // Embed per-const rustdoc so `cargo doc` and source readers see purpose +
    // range without bouncing through the markdown guide. The guide remains the
    // single source of truth for tuning recipes and worked examples.
    const GUIDE: &str =
        "See the [JVM tunables guide](https://shivrajora.github.io/picodroid-rs/reference/jvm-tunables/) \
         for the full schema, tuning workflow, and worked recipes.";
    let mut code = String::from("// Generated by jvm/build.rs — do not edit.\n\n");
    code.push_str(&format!(
        "/// Allocations between automatic GC cycles. Range 16..=8192 \
         (default {default}). Lower = more frequent GC, smaller peak heap, \
         more pauses. Higher = fewer pauses, larger peak heap.\n\
         ///\n\
         /// {guide}\n\
         pub const GC_THRESHOLD: u16 = {gc_threshold};\n\n",
        default = 256,
        guide = GUIDE,
    ));
    code.push_str(&format!(
        "/// Log2 of the slot-storage chunk size used by `ChunkedSlots`. \
         Range 3..=8 (default {default}). Lower = smaller worst-case \
         contiguous allocation, better fragmentation tolerance.\n\
         ///\n\
         /// {guide}\n\
         pub const CHUNK_SHIFT: u8 = {chunk_shift};\n\n",
        default = 6,
        guide = GUIDE,
    ));
    code.push_str(
        "/// Chunk size in slots = `1 << CHUNK_SHIFT`. Derived from \
         [`CHUNK_SHIFT`].\n\
         pub const CHUNK_SIZE: usize = 1usize << CHUNK_SHIFT;\n\n",
    );
    code.push_str(
        "/// Bitmask for `idx % CHUNK_SIZE` in chunked-slot index math. \
         Derived from [`CHUNK_SIZE`].\n\
         pub const CHUNK_MASK: usize = CHUNK_SIZE - 1;\n\n",
    );
    code.push_str(&format!(
        "/// Max array length (in `i32`-slots) stored inline rather than in \
         the shared arena. Range 0..=32 (default {default}). Raise to keep \
         short arrays out of the arena; lower to shrink each slot's struct.\n\
         ///\n\
         /// {guide}\n\
         pub const INLINE_DATA: usize = {inline_data};\n",
        default = 8,
        guide = GUIDE,
    ));

    let path = out_dir.join("tunables.rs");
    let mut f = File::create(&path).expect("create tunables.rs");
    f.write_all(code.as_bytes()).expect("write tunables.rs");
}

fn read_env_u32(name: &str, default: u32, min: u32, max: u32) -> u32 {
    let raw = match env::var(name) {
        Ok(v) => v,
        Err(_) => return default,
    };
    let v: u32 = raw
        .parse()
        .unwrap_or_else(|e| panic!("{name}={raw:?}: not a valid u32 ({e})"));
    if v < min || v > max {
        panic!("{name}={v}: out of range (allowed {min}..={max})");
    }
    v
}
