// SPDX-License-Identifier: GPL-3.0-only
//! Generates `$OUT_DIR/tunables.rs` from `PICODROID_JVM_*` environment
//! variables. Defaults reproduce the previously-hardcoded values bit-for-bit,
//! so a build without any env override is identical to the pre-tunables JVM.
//!
//! The values are emitted as `pub const`s and `include!`'d into
//! `jvm/src/tunables.rs`, so every use site inlines an immediate operand at
//! compile time — zero RAM cost, no runtime indirection.
//!
//! Defaults and accepted ranges live in `build_support/jvm_defaults.rs` (shared
//! with `platforms/rp/build.rs::emit_jvm_config`) so the two build scripts cannot
//! drift apart.
//!
//! Also generates `$OUT_DIR/names.rs` — the `c::` / `m::` / `d::` constants
//! `jvm/src/names.rs` exposes (`build_support/names.rs`), spelled through the
//! active shrink map when `PICODROID_SHRINK=1` (the same gate
//! `build_support/papk.rs` applies to the framework corpus).

#[path = "../build_support/jvm_defaults.rs"]
mod jvm_defaults;
// The shrink-map readers, shared with `tools/class-shrink` by inclusion so
// this crate takes no build-dependency on a path crate (see `emit_java_names`).
#[allow(dead_code)]
#[path = "../tools/class-shrink/src/mapping.rs"]
mod cs_mapping;
#[allow(dead_code)]
#[path = "../tools/class-shrink/src/rename.rs"]
mod cs_rename;
#[allow(dead_code)]
#[path = "../tools/class-shrink/src/version.rs"]
mod cs_version;
#[allow(dead_code)]
#[path = "../build_support/names.rs"]
mod names;

use jvm_defaults::{GC_ALLOC_THRESHOLD, INLINE_ARRAY_DATA, SLOT_CHUNK_SHIFT};
use std::env;
use std::fs::File;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    emit_names(&out_dir);

    println!("cargo:rerun-if-env-changed=PICODROID_JVM_GC_ALLOC_THRESHOLD");
    println!("cargo:rerun-if-env-changed=PICODROID_JVM_SLOT_CHUNK_SHIFT");
    println!("cargo:rerun-if-env-changed=PICODROID_JVM_INLINE_ARRAY_DATA");

    let gc_threshold = read_env_u32("PICODROID_JVM_GC_ALLOC_THRESHOLD", &GC_ALLOC_THRESHOLD);
    let chunk_shift = read_env_u32("PICODROID_JVM_SLOT_CHUNK_SHIFT", &SLOT_CHUNK_SHIFT);
    let inline_data = read_env_u32("PICODROID_JVM_INLINE_ARRAY_DATA", &INLINE_ARRAY_DATA);

    // Embed per-const rustdoc so `cargo doc` and source readers see purpose +
    // range without bouncing through the markdown guide. The guide remains the
    // single source of truth for tuning recipes and worked examples.
    const GUIDE: &str =
        "See the [JVM tunables guide](https://shivrajora.github.io/picodroid-rs/reference/jvm-tunables/) \
         for the full schema, tuning workflow, and worked recipes.";
    let mut code = String::from("// Generated by jvm/build.rs — do not edit.\n\n");
    code.push_str(&format!(
        "/// Allocations between automatic GC cycles. Range {min}..={max} \
         (default {default}). Lower = more frequent GC, smaller peak heap, \
         more pauses. Higher = fewer pauses, larger peak heap.\n\
         ///\n\
         /// {guide}\n\
         pub const GC_THRESHOLD: u16 = {gc_threshold};\n\n",
        default = GC_ALLOC_THRESHOLD.default,
        min = GC_ALLOC_THRESHOLD.min,
        max = GC_ALLOC_THRESHOLD.max,
        guide = GUIDE,
    ));
    code.push_str(&format!(
        "/// Log2 of the slot-storage chunk size used by `ChunkedSlots`. \
         Range {min}..={max} (default {default}). Lower = smaller worst-case \
         contiguous allocation, better fragmentation tolerance.\n\
         ///\n\
         /// {guide}\n\
         pub const CHUNK_SHIFT: u8 = {chunk_shift};\n\n",
        default = SLOT_CHUNK_SHIFT.default,
        min = SLOT_CHUNK_SHIFT.min,
        max = SLOT_CHUNK_SHIFT.max,
        guide = GUIDE,
    ));
    code.push_str(
        "/// Chunk size in slots = `1 << CHUNK_SHIFT`. Derived from \
         [`CHUNK_SHIFT`].\n\
         pub const CHUNK_SIZE: usize = 1usize << CHUNK_SHIFT;\n\n",
    );
    code.push_str(
        "/// Bitmask for `idx % CHUNK_SIZE` in chunked-slot index math. \
         Derived from [`CHUNK_SIZE`].\n\
         pub const CHUNK_MASK: usize = CHUNK_SIZE - 1;\n\n",
    );
    code.push_str(&format!(
        "/// Max array length (in `i32`-slots) stored inline rather than in \
         the shared arena. Range {min}..={max} (default {default}). Raise to keep \
         short arrays out of the arena; lower to shrink each slot's struct.\n\
         ///\n\
         /// {guide}\n\
         pub const INLINE_DATA: usize = {inline_data};\n",
        default = INLINE_ARRAY_DATA.default,
        min = INLINE_ARRAY_DATA.min,
        max = INLINE_ARRAY_DATA.max,
        guide = GUIDE,
    ));

    let path = out_dir.join("tunables.rs");
    let mut f = File::create(&path).expect("create tunables.rs");
    f.write_all(code.as_bytes()).expect("write tunables.rs");
}

fn read_env_u32(name: &str, spec: &jvm_defaults::JvmTunable) -> u32 {
    let raw = match env::var(name) {
        Ok(v) => v,
        Err(_) => return spec.default,
    };
    let v: u32 = raw
        .parse()
        .unwrap_or_else(|e| panic!("{name}={raw:?}: not a valid u32 ({e})"));
    if v < spec.min || v > spec.max {
        panic!(
            "{name}={v}: out of range (allowed {min}..={max})",
            min = spec.min,
            max = spec.max,
        );
    }
    v
}

/// Emit `names.rs`: the `c::` / `m::` / `d::` name-constant modules
/// (`build_support/names.rs`), spelled through the active shrink map.
/// Resolution mirrors `build_support/papk.rs::apply_active_shrink`: the
/// highest committed `sdk/shrink-maps/v*.toml` not newer than
/// `platforms/rp/Cargo.toml`'s version. Anything short of "shrink on, map
/// active, dir present" yields the original spellings, so a standalone
/// build of this crate still compiles.
fn emit_names(out_dir: &Path) {
    println!("cargo:rerun-if-env-changed=PICODROID_SHRINK");
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..");
    let maps_dir = root.join("sdk").join("shrink-maps");
    let cargo_toml = {
        let rp = root.join("platforms/rp/Cargo.toml");
        if rp.exists() {
            rp
        } else {
            root.join("Cargo.toml")
        }
    };
    println!("cargo:rerun-if-changed={}", maps_dir.display());
    println!("cargo:rerun-if-changed={}", cargo_toml.display());

    let mut map: Option<cs_mapping::ShrinkMap> = None;
    let shrink_on = env::var("PICODROID_SHRINK").as_deref() == Ok("1");
    if shrink_on && maps_dir.is_dir() {
        if let Ok(pkg) = cs_version::read_picodroid_version(&cargo_toml) {
            let active = cs_version::resolve_active_version(&pkg, &maps_dir);
            if active != "0.0.0" {
                let path = maps_dir.join(format!("v{active}.toml"));
                println!("cargo:rerun-if-changed={}", path.display());
                map = Some(
                    cs_mapping::ShrinkMap::load(&path)
                        .unwrap_or_else(|e| panic!("failed to load {}: {e}", path.display())),
                );
            }
        }
    }
    let class = |name: &str| -> Option<String> {
        map.as_ref()
            .and_then(|m| m.classes.get(name))
            .map(String::from)
    };
    let member = |name: &str| -> Option<String> {
        map.as_ref()
            .and_then(|m| m.member_target(name))
            .map(String::from)
    };
    names::emit_names(
        out_dir,
        &root,
        &names::Targets {
            class: &class,
            member: &member,
        },
        map.is_some(),
    );
}
