// SPDX-License-Identifier: GPL-3.0-only
#[cfg(not(test))]
use alloc::boxed::Box;
#[cfg(not(test))]
use pico_jvm::apk::Papk;
#[cfg(not(test))]
use pico_jvm::types::JvmError;
#[cfg(not(test))]
use pico_jvm::{Jvm, SharedJvmHeap};

// APK accessor, generated by build.rs from the PICODROID_APK_PATH env var.
// Defines: pub fn apk_data() -> &'static [u8]. Embedded builds get an empty
// slice (APK lives in PAPK_FLASH); sim builds read the .papk from disk at
// startup so Java-only changes don't force a Rust rebuild; other host builds
// (cargo test) embed it via include_bytes!.
#[cfg(not(test))]
include!(concat!(env!("OUT_DIR"), "/apk_data.rs"));

// Framework class bytecode lives in its own ungated module so that the
// dispatch-site regression test (see `crate::dispatch_sites`) can parse it
// under `cfg(test)`. Re-exported here for the existing load path.
#[cfg(not(test))]
use crate::framework_classes::FRAMEWORK_CLASSES;

// Active shrink-map version for this firmware build. Set by build.rs from the
// highest committed sdk/shrink-maps/v<semver>.toml ≤ the picodroid Cargo.toml
// version; falls back to "0.0.0" (no shrinking) when none exists.
// Defines: pub const FRAMEWORK_MAP_VERSION: &str = "...";
#[cfg(not(test))]
include!(concat!(env!("OUT_DIR"), "/framework_mapping_version.rs"));

// ── Shared heap ──────────────────────────────────────────────────────────────
//
// All JVM threads share a single heap (objects, arrays, strings), matching the
// standard Java memory model.  On the single-core RP2040/RP2350 only one
// FreeRTOS task runs at a time, so concurrent access is safe without a global
// lock.  Allocation paths are short critical regions protected by the
// single-core scheduling guarantee.

// SAFETY: single-core Cortex-M; only one FreeRTOS task executes at a time.
#[cfg(not(test))]
struct SharedHeapCell(core::cell::UnsafeCell<SharedJvmHeap>);
#[cfg(not(test))]
unsafe impl Sync for SharedHeapCell {}

#[cfg(not(test))]
static SHARED_HEAP: SharedHeapCell =
    SharedHeapCell(core::cell::UnsafeCell::new(SharedJvmHeap::new()));

/// Return a mutable reference to the process-wide shared JVM heap.
///
/// # Safety
/// Must only be called from FreeRTOS task context on the single core used by
/// picodroid (never from an ISR).  Alloc operations inside ObjectHeap and
/// ArrayHeap are short enough that a task switch mid-alloc cannot occur on
/// cooperative yield points (sleep / UART read).
#[cfg(not(test))]
pub fn shared_heap() -> &'static mut SharedJvmHeap {
    unsafe { &mut *SHARED_HEAP.0.get() }
}

// ── Class loader registration ─────────────────────────────────────────────────
//
// The `Thread.start()` native handler spawns a new FreeRTOS task that creates
// a fresh Jvm and must load all application classes before invoking Runnable.run().
// A universal loader function reads all classes directly from the embedded APK,
// so every app (including threaddemo) works without special-casing.

#[cfg(not(test))]
type ClassLoaderFn = fn(&mut Jvm) -> Result<(), JvmError>;

// SAFETY: single-core Cortex-M; only one FreeRTOS task executes at a time.
// register_class_loader() is called once from the JVM bootstrap task before
// any Thread.start() dispatch can occur.
#[cfg(not(test))]
struct ClassLoaderCell(core::cell::UnsafeCell<Option<ClassLoaderFn>>);
#[cfg(not(test))]
unsafe impl Sync for ClassLoaderCell {}

#[cfg(not(test))]
static CLASS_LOADER: ClassLoaderCell = ClassLoaderCell(core::cell::UnsafeCell::new(None));

#[cfg(not(test))]
#[allow(dead_code)]
pub fn register_class_loader(f: ClassLoaderFn) {
    unsafe { *CLASS_LOADER.0.get() = Some(f) }
}

#[cfg(not(test))]
#[cfg_attr(feature = "sim", allow(dead_code))]
pub fn load_classes(jvm: &mut Jvm) -> Result<(), JvmError> {
    unsafe {
        match *CLASS_LOADER.0.get() {
            Some(f) => f(jvm),
            None => Ok(()),
        }
    }
}

// ── Framework class loading ───────────────────────────────────────────────────

/// Loads all picodroid framework classes into `jvm`.
///
/// Framework classes (`picodroid.*`) are compiled by `build.rs` and embedded
/// directly in firmware Flash — they are platform code, not app code.
/// This mirrors Android's boot classpath model.
#[cfg(not(test))]
fn load_framework_classes(jvm: &mut Jvm) -> Result<(), JvmError> {
    for class_data in FRAMEWORK_CLASSES {
        jvm.load_class(class_data)?;
    }
    Ok(())
}

// ── Active APK pointer ────────────────────────────────────────────────────────
//
// run_jvm_with() stores a pointer to the current APK here so that
// load_classes_from_apk() (a bare fn, not a closure) can serve both the
// built-in apk_data() and a dynamically-installed PAPK for Thread.start()
// spawned tasks without needing a global allocator or closure captures.
//
// SAFETY: single-core Cortex-M; only one FreeRTOS task writes (jvm_task) and
// only one reads (jvm_task or jvm-t spawned tasks) at a time.
#[cfg(not(test))]
struct ActiveApkCell(core::cell::UnsafeCell<(*const u8, usize)>);
#[cfg(not(test))]
unsafe impl Sync for ActiveApkCell {}

#[cfg(not(test))]
static ACTIVE_APK: ActiveApkCell =
    ActiveApkCell(core::cell::UnsafeCell::new((core::ptr::null(), 0)));

// ── APK-driven class loading ──────────────────────────────────────────────────

/// Loads all classes from the active APK into `jvm`.
///
/// Used both during initial JVM startup and by the `Thread.start()` native
/// handler when it spawns a fresh `Jvm` for a new thread.  Reads the APK
/// pointer set by `run_jvm_with()` so that dynamically-installed PAPKs
/// are loaded correctly in child threads without closure captures.
#[cfg(not(test))]
fn load_classes_from_apk(jvm: &mut Jvm) -> Result<(), JvmError> {
    let apk_data: &[u8] = unsafe {
        let (ptr, len) = *ACTIVE_APK.0.get();
        assert!(!ptr.is_null(), "ACTIVE_APK not set");
        core::slice::from_raw_parts(ptr, len)
    };
    let apk = Papk::parse(apk_data).map_err(|_| JvmError::InvalidBytecode)?;
    for entry in apk.classes().map_err(|_| JvmError::InvalidBytecode)? {
        jvm.load_class(entry.data)?;
    }
    Ok(())
}

/// Loads framework classes then app classes — used by `Thread.start()` spawned
/// tasks that need a fully-populated fresh `Jvm`.
#[cfg(not(test))]
fn load_all_classes(jvm: &mut Jvm) -> Result<(), JvmError> {
    load_framework_classes(jvm)?;
    load_classes_from_apk(jvm)
}

// ── run_jvm_with / run_jvm ────────────────────────────────────────────────────

/// Run the JVM with a specific APK slice.
///
/// Resets the shared heap (clearing previous app state), loads framework and
/// app classes, then either launches an Activity (if the manifest declares one)
/// or falls back to `<main_class>.main()`.  Returns when execution completes
/// naturally or is interrupted by `pdb install` (cooperative stop).
/// `JvmError::Interrupted` is silently ignored — it is a clean exit signal.
#[cfg(not(test))]
pub fn run_jvm_with(apk_data: &[u8]) {
    // Publish the APK pointer so load_classes_from_apk (a bare fn) picks it up
    // even when called from Thread.start()-spawned child tasks.
    unsafe { *ACTIVE_APK.0.get() = (apk_data.as_ptr(), apk_data.len()) };

    // Clear previous app's heap state before running a new app.
    shared_heap().reset();
    crate::system::picodroid::graphics::widgets::reset_button_state();
    crate::system::picodroid::graphics::widgets::reset_progress_bar_state();
    crate::system::picodroid::graphics::widgets::reset_toggle_button_state();
    crate::system::picodroid::graphics::widgets::reset_switch_state();
    crate::system::picodroid::graphics::widgets::reset_seek_bar_state();
    crate::system::picodroid::graphics::widgets::reset_check_box_state();
    crate::system::picodroid::graphics::widgets::reset_spinner_state();
    crate::system::picodroid::graphics::widgets::reset_toast_state();
    crate::system::picodroid::graphics::widgets::reset_snackbar_state();
    crate::system::picodroid::graphics::widgets::reset_alert_dialog_state();
    crate::system::picodroid::graphics::widgets::reset_date_picker_state();
    crate::system::picodroid::graphics::widgets::reset_time_picker_state();
    crate::system::picodroid::graphics::widgets::reset_swipe_refresh_state();
    crate::system::picodroid::graphics::widgets::reset_animation_state();
    crate::system::picodroid::graphics::widgets::reset_keyboard_state();
    crate::system::picodroid::graphics::widgets::reset_edit_text_state();
    crate::system::picodroid::graphics::widgets::reset_list_view_state();
    crate::system::picodroid::graphics::widgets::reset_number_picker_state();
    crate::system::picodroid::graphics::view::reset_key_listener_state();
    crate::system::picodroid::graphics::view::reset_touch_listener_state();
    crate::system::picodroid::graphics::view::reset_swipe_listener_state();
    crate::system::picodroid::graphics::view::reset_focus_change_listener_state();
    crate::system::picodroid::graphics::lvgl::events::reset_key_event_queue();
    crate::system::picodroid::graphics::lvgl::events::reset_edit_mode();
    crate::system::picodroid::graphics::lvgl::events::reset_activity_groups();
    crate::system::picodroid::graphics::lvgl::handle_table::reset();
    crate::system::picodroid::graphics::assets::clear();
    #[cfg(not(feature = "sim"))]
    crate::system::monitor_store::clear();

    // Parse the APK once up front so we can pre-size the class table to the
    // exact framework + app class count.  Avoids 7 Vec doubling reallocations
    // (and their transient double-buffering) during framework registration.
    let apk_for_count = match Papk::parse(apk_data) {
        Ok(a) => a,
        Err(e) => {
            #[cfg(not(feature = "sim"))]
            defmt::error!(
                "PAPK parse failed during pre-sizing: {}",
                defmt::Debug2Format(&e)
            );
            #[cfg(feature = "sim")]
            eprintln!("[sim] PAPK parse failed during pre-sizing: {:?}", e);
            return;
        }
    };
    let apk_class_count = apk_for_count.classes().map(|it| it.count()).unwrap_or(0);
    let mut jvm = Box::new(Jvm::with_capacity(
        FRAMEWORK_CLASSES.len() + apk_class_count,
    ));
    let heap = shared_heap();
    let mut handler = crate::system::native_handler::PicodroidNativeHandler::new();
    #[cfg(feature = "sim")]
    crate::sim_allocator::checkpoint("post-jvm-new");

    // Register the combined loader so Thread.start() spawned tasks load both
    // framework and app classes into their fresh Jvm instances.
    register_class_loader(load_all_classes);

    // Load platform (framework) classes first, then app classes from the APK.
    load_framework_classes(&mut jvm).unwrap();
    #[cfg(feature = "sim")]
    crate::sim_allocator::checkpoint("post-framework-load");
    load_classes_from_apk(&mut jvm).unwrap();
    #[cfg(feature = "sim")]
    crate::sim_allocator::checkpoint("post-app-load");

    // Determine the entry point from the APK manifest. The earlier
    // pre-sizing parse already returned-on-error, so a second failure here
    // is a fresh-bytes anomaly; bail cleanly rather than panic on-device.
    let apk = match Papk::parse(apk_data) {
        Ok(a) => a,
        Err(e) => {
            #[cfg(not(feature = "sim"))]
            defmt::error!(
                "PAPK parse failed during entry-point lookup: {}",
                defmt::Debug2Format(&e)
            );
            #[cfg(feature = "sim")]
            eprintln!("[sim] PAPK parse failed during entry-point lookup: {:?}", e);
            return;
        }
    };

    // Reject PAPKs built against a newer shrink-map release than the firmware
    // knows about. Maps are append-only per release, so older PAPKs are always
    // accepted; only a forward-incompatible PAPK fails here. Log + return
    // cleanly rather than panic on-device: a bad APK shouldn't take down the
    // boot path before pdb can recover.
    if let Err(e) = apk.verify_compat(FRAMEWORK_MAP_VERSION) {
        #[cfg(not(feature = "sim"))]
        defmt::error!(
            "PAPK framework-map-version incompatible with firmware (firmware = {}): {}",
            FRAMEWORK_MAP_VERSION,
            defmt::Debug2Format(&e)
        );
        #[cfg(feature = "sim")]
        eprintln!(
            "[sim] PAPK framework-map-version incompatible with firmware (firmware = {}): {:?}",
            FRAMEWORK_MAP_VERSION, e
        );
        return;
    }

    // Build the bundled-asset registry from this papk's ASSETS section so
    // `ImageView.setImageSource("name.png")` resolves at runtime. Empty for
    // legacy v1.0 papks and any v1.1 papk built without `--assets-dir`.
    crate::system::picodroid::graphics::assets::init_from_papk(&apk);

    #[cfg(feature = "sim")]
    let start = std::time::Instant::now();

    if let Some(application_class) = apk.application() {
        // The APK data is &'static [u8] (Flash-backed), so the parsed
        // class name string is also 'static.  Transmute the lifetime so
        // alloc() can store it in the object heap.
        let static_name: &'static str =
            unsafe { core::mem::transmute::<&str, &'static str>(application_class) };
        crate::lifecycle::run_application(&mut jvm, static_name, heap, &mut handler);
    } else if let Some(activity_class) = apk.activity() {
        let static_name: &'static str =
            unsafe { core::mem::transmute::<&str, &'static str>(activity_class) };
        let obj_ref = heap
            .objects
            .alloc(static_name)
            .expect("OOM allocating Activity");
        crate::lifecycle::run_activity(&mut jvm, static_name, obj_ref, heap, &mut handler);
    } else {
        let main_class = apk
            .main_class()
            .expect("APK manifest is missing 'main-class'");

        // Interrupted is a clean cooperative stop — not a real error.
        match jvm.invoke_static(main_class, "main", heap, &mut handler) {
            Ok(_) | Err(JvmError::Interrupted) => {}
            #[cfg(not(feature = "sim"))]
            Err(e) => defmt::error!("JVM error: {}", defmt::Display2Format(&e)),
            #[cfg(feature = "sim")]
            Err(e) => eprintln!("[jvm] error: {}", e),
        }
    }

    #[cfg(feature = "sim")]
    {
        crate::sim_allocator::checkpoint("post-onCreate");
        let (gc_ns, gc_count, gc_freed) = handler.gc_stats();
        let (parsed, total) = jvm.count_parsed();
        println!(
            "[sim] JVM wall-clock: {} ms, gc: {} collections, {} freed, {} us, \
             lazy-load: {}/{} classes parsed",
            start.elapsed().as_millis(),
            gc_count,
            gc_freed,
            gc_ns / 1000,
            parsed,
            total,
        );
    }
}

/// Run the JVM with the built-in APK (sim entry point).
#[cfg(not(test))]
#[cfg_attr(not(feature = "sim"), allow(dead_code))]
pub fn run_jvm() {
    run_jvm_with(apk_data());

    #[cfg(all(not(feature = "sim"), feature = "family-rp"))]
    loop {
        freertos_rust::CurrentTask::delay(freertos_rust::Duration::ms(60_000));
    }
}
