// SPDX-License-Identifier: GPL-3.0-only
#![cfg_attr(not(any(test, feature = "sim")), no_std)]
#![cfg_attr(not(any(test, feature = "sim")), no_main)]

extern crate alloc;

mod app;
// Active-board Rust glue. Generated by build.rs (empty no-op when no board
// is active). Only pulled in on hardware builds.
#[cfg(not(any(test, feature = "sim")))]
mod boards;
pub use picodroid_core::dispatch_sites;
#[allow(dead_code)]
pub use picodroid_core::drivers;
pub use picodroid_core::framework_classes;
#[allow(dead_code)]
#[cfg(not(test))]
mod fs;
// Shared boot memory budget (device task stacks / sim pre-charge — M4).
#[cfg_attr(test, allow(dead_code))]
mod boot_budget;
#[allow(dead_code)]
mod hal;
// Binds picodroid-core's HAL / RTOS / platform-hook seam to this family.
// The single file a new MCU family reimplements.
mod glue;
// Registers this crate's GC root providers with picodroid_core::gc_roots.
// Always compiled: the registration itself is cfg(not(test))-gated inside
// (it names LVGL/HAL modules), but its completeness guard is a source scan
// that must run under scripts/test.sh.
mod gc_root_registration;
#[cfg(not(test))]
pub use picodroid_core::lifecycle;
#[cfg(not(test))]
pub use picodroid_core::lvgl_ffi;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
mod packagemanager;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
mod pdb;
#[cfg(not(test))]
pub use picodroid_core::service_lifecycle;
pub use picodroid_core::shrink_names;
// The capped simulator heap and its heap_4 arena live in picodroid-core now;
// only the `#[global_allocator]` attribute has to stay in a binary crate, so
// this is a forwarder rather than a copy. Unarmed the allocator is a
// pass-through to the system one, so plain host tests are unaffected.
#[cfg(any(test, feature = "sim"))]
use picodroid_core::hal::sim::allocator as sim_allocator;
pub use picodroid_core::task_priority;

/// Routes every allocation to the simulator's capped allocator in
/// picodroid-core.
///
/// A `#[global_allocator]` must be a `static` of the binary crate, so the
/// instance cannot simply be core's. All four methods are forwarded rather
/// than leaning on the trait defaults: the defaults would re-enter *this*
/// type, which happens to be equivalent today only because `CappedAllocator`
/// also takes them — forwarding explicitly keeps that a non-question if it
/// ever overrides `realloc`.
#[cfg(any(test, feature = "sim"))]
struct SimGlobalAlloc;

#[cfg(any(test, feature = "sim"))]
unsafe impl core::alloc::GlobalAlloc for SimGlobalAlloc {
    unsafe fn alloc(&self, layout: core::alloc::Layout) -> *mut u8 {
        core::alloc::GlobalAlloc::alloc(&sim_allocator::GLOBAL, layout)
    }
    unsafe fn dealloc(&self, ptr: *mut u8, layout: core::alloc::Layout) {
        core::alloc::GlobalAlloc::dealloc(&sim_allocator::GLOBAL, ptr, layout)
    }
    unsafe fn realloc(
        &self,
        ptr: *mut u8,
        layout: core::alloc::Layout,
        new_size: usize,
    ) -> *mut u8 {
        core::alloc::GlobalAlloc::realloc(&sim_allocator::GLOBAL, ptr, layout, new_size)
    }
    unsafe fn alloc_zeroed(&self, layout: core::alloc::Layout) -> *mut u8 {
        core::alloc::GlobalAlloc::alloc_zeroed(&sim_allocator::GLOBAL, layout)
    }
}

#[cfg(any(test, feature = "sim"))]
#[global_allocator]
static SIM_GLOBAL: SimGlobalAlloc = SimGlobalAlloc;

// Host-testable pure-logic slices of RP HAL drivers. The rest of `hal::rp`
// is ARM-only and cfg-gated out on the host; these modules have no
// `rp-pico`/`rp235x-hal` deps, so pulling them in directly via `#[path]`
// lets their `#[cfg(test)]` blocks run under `scripts/test.sh`.
#[cfg(test)]
#[path = "hal/rp/i2c/protocol.rs"]
mod hal_rp_i2c_protocol_tests;
#[cfg(test)]
#[path = "hal/rp/pdb_usb/protocol.rs"]
mod hal_rp_pdb_usb_protocol_tests;
#[cfg(test)]
#[path = "hal/rp/spi/protocol.rs"]
mod hal_rp_spi_protocol_tests;
// The native_handler test shims moved to picodroid-core along with the
// module; its pure-logic submodules are re-exposed there now.

// Family-rp hardware imports (Cortex-M-specific via cortex-m-rt + the
// generic-FreeRTOS rust bindings).
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use cortex_m::asm;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use cortex_m_rt::{entry, exception, ExceptionFrame};
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use defmt_rtt as _;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use freertos_rust::*;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use panic_probe as _;

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[global_allocator]
static GLOBAL: FreeRtosAllocator = FreeRtosAllocator;

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[entry]
fn main() -> ! {
    hal::boot::clock_init();

    let boot_apk: &'static [u8] =
        unsafe { hal::flash::read_flash_papk() }.expect("PAPK flash region invalid");

    // Mount LittleFS on the FS_FLASH region.  Runs pre-scheduler (single-core),
    // formats on first boot or after corruption.  A failure here is non-fatal
    // for the JVM — persistence simply remains unavailable until the next boot.
    if let Err(e) = fs::init() {
        defmt::warn!("[fs] init failed: {}", defmt::Display2Format(&e));
    }

    hal::boot::start_tasks(boot_apk)
}

#[cfg(feature = "sim")]
fn main() {
    // Start device-heap accounting at the sim's "reset vector". Everything
    // before this is host-runtime noise; everything after is charged to the
    // heap_4 arena exactly as the device charges its FreeRTOS heap.
    sim_allocator::arm();
    // Charge the FreeRTOS boot structures (task stacks, TCBs, queues) the
    // device allocates from this same arena — measured at ~85 KB on HW (V4).
    boot_budget::precharge_boot_budget();
    sim_allocator::checkpoint("baseline");

    if let Err(e) = fs::init() {
        eprintln!("[sim][fs] init failed: {}", e);
    }
    sim_allocator::checkpoint("post-fs-init");

    app::run_jvm();

    sim_allocator::checkpoint("final");

    let (current, peak, limit) = sim_allocator::heap_stats();
    if limit == usize::MAX {
        println!("[sim] heap: peak {} KB (unlimited)", peak / 1024);
    } else {
        println!(
            "[sim] heap: peak {} KB / {} KB limit ({} KB current)",
            peak / 1024,
            limit / 1024,
            current / 1024,
        );
    }
}

// Cortex-M exception handlers and FreeRTOS application hooks (family-rp only).
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[exception]
unsafe fn DefaultHandler(_irqn: i16) {
    asm::bkpt();
    #[allow(clippy::empty_loop)]
    loop {}
}

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[exception]
unsafe fn HardFault(_ef: &ExceptionFrame) -> ! {
    // On RP2040 (Cortex-M0+) bkpt halts cleanly with a debugger attached.
    // On RP2350 (Cortex-M33) bkpt without a debugger causes a re-entrant
    // fault → lockup, so we skip it.
    #[cfg(not(feature = "chip-rp2350"))]
    asm::bkpt();
    #[allow(clippy::empty_loop)]
    loop {}
}

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[no_mangle]
fn vApplicationMallocFailedHook() {
    // Intentionally a no-op: pvPortMalloc returns NULL after this hook,
    // allowing Rust's try_reserve_exact to return Err and trigger GC.
    // Non-try allocations still abort via Rust's handle_alloc_error.
}

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[no_mangle]
fn vApplicationStackOverflowHook(_pxTask: FreeRtosTaskHandle, _pcTaskName: FreeRtosCharPtr) {
    asm::bkpt();
    #[allow(clippy::empty_loop)]
    loop {}
}
