// SPDX-License-Identifier: GPL-3.0-only
#![cfg_attr(not(any(test, feature = "sim")), no_std)]
#![cfg_attr(not(any(test, feature = "sim")), no_main)]

extern crate alloc;

mod app;
// Active-board Rust glue. Generated by build.rs (empty no-op when no board
// is active). Only pulled in on hardware builds.
#[cfg(not(any(test, feature = "sim")))]
mod boards;
pub use picodroid_core::dispatch_sites;
pub use picodroid_core::drivers;
pub use picodroid_core::framework_classes;
// Device-only: the simulator mounts its host-file image from
// `picodroid_core::sim_boot`, so nothing in a simulator build reaches this.
#[cfg(not(any(test, feature = "sim")))]
mod fs;
// Shared boot memory budget (device task stacks / sim pre-charge — M4).
mod boot_budget;
// Core placement for every task this family creates: the one spawn helper
// (create+pin as a scheduler-atomic step), the CORE0/CORE1 masks, and the
// source scan that keeps every spawn site honest (parity-audit THR-04 / X1).
// Always compiled, like gc_root_registration: the helper is device-only, but
// the guard must run under scripts/test.sh.
mod task_affinity;
// Task topology + the JVM supervisor loop. Bin-layer rather than HAL: it
// drives fs / pdb / boot_budget, and only sat under hal/rp because it starts
// the scheduler next to clock_init.
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
mod boot_tasks;
mod hal;
// Binds picodroid-core's HAL / RTOS / platform-hook seam to this family.
// The single file a new MCU family reimplements.
mod glue;
// Registers this crate's GC root providers with picodroid_core::gc_roots.
// Always compiled: the registration itself is cfg(not(test))-gated inside
// (it names LVGL/HAL modules), but its completeness guard is a source scan
// that must run under scripts/test.sh.
mod gc_root_registration;
#[cfg(not(test))]
pub use picodroid_core::lifecycle;
#[cfg(not(test))]
pub use picodroid_core::lvgl_ffi;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
mod packagemanager;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
mod pdb;
#[cfg(not(test))]
pub use picodroid_core::service_lifecycle;
pub use picodroid_core::shrink_names;
pub use picodroid_core::task_priority;

// The capped simulator heap and its heap_4 arena live in picodroid-core; only
// the `#[global_allocator]` attribute has to stay in a binary crate, so this
// is one macro call rather than a copy of the forwarder.
#[cfg(any(test, feature = "sim"))]
picodroid_core::declare_sim_global_allocator!();

// Host-testable pure-logic slices of RP HAL drivers. The rest of `hal::rp`
// is ARM-only and cfg-gated out on the host; these modules have no
// `rp-pico`/`rp235x-hal` deps, so pulling them in directly via `#[path]`
// lets their `#[cfg(test)]` blocks run under `scripts/test.sh`. A driver
// whose tests live in a file that is *not* listed here has tests that never
// run — `pwm` and `adc` were exactly that until 2026-09.
#[cfg(test)]
#[path = "hal/rp/adc/math.rs"]
mod hal_rp_adc_math_tests;
#[cfg(test)]
#[path = "hal/rp/i2c/timing.rs"]
mod hal_rp_i2c_timing_tests;
#[cfg(test)]
#[path = "hal/rp/pwm/math.rs"]
mod hal_rp_pwm_math_tests;
#[cfg(test)]
#[path = "hal/rp/spi/xfer.rs"]
mod hal_rp_spi_xfer_tests;
// Text scans over the cyw43 port's C config (no hardware deps).
#[cfg(test)]
#[path = "hal/rp/cyw43/config_guard.rs"]
mod hal_rp_cyw43_config_guard_tests;
// The native_handler test shims moved to picodroid-core along with the
// module; its pure-logic submodules are re-exposed there now.

// Family-rp hardware imports (Cortex-M-specific via cortex-m-rt + the
// generic-FreeRTOS rust bindings).
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use cortex_m::asm;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use cortex_m_rt::{entry, exception, ExceptionFrame};
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use defmt_rtt as _;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use freertos_rust::*;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use panic_probe as _;

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[global_allocator]
static GLOBAL: FreeRtosAllocator = FreeRtosAllocator;

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[entry]
fn main() -> ! {
    hal::boot::clock_init();

    let boot_apk: &'static [u8] =
        unsafe { hal::flash::read_flash_papk() }.expect("PAPK flash region invalid");

    // Mount LittleFS on the FS_FLASH region.  Runs pre-scheduler (single-core),
    // formats on first boot or after corruption.  A failure here is non-fatal
    // for the JVM — persistence simply remains unavailable until the next boot.
    if let Err(e) = fs::init() {
        defmt::warn!("[fs] init failed: {}", defmt::Display2Format(&e));
    }

    boot_tasks::start_tasks(boot_apk)
}

#[cfg(feature = "sim")]
fn main() {
    // Arming the heap model, the boot-budget precharge, the host filesystem
    // image, the scheduler handoff and the closing heap banner are the
    // simulator's own sequence (`picodroid_core::sim_boot::main`). This
    // family contributes its three leaves through `register_sim_platform!`
    // in `glue.rs`, which generates `sim_main`.
    glue::sim_main()
}

// Cortex-M exception handlers and FreeRTOS application hooks (family-rp only).
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[exception]
unsafe fn DefaultHandler(_irqn: i16) {
    asm::bkpt();
    #[allow(clippy::empty_loop)]
    loop {}
}

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[exception]
unsafe fn HardFault(_ef: &ExceptionFrame) -> ! {
    // On RP2040 (Cortex-M0+) bkpt halts cleanly with a debugger attached.
    // On RP2350 (Cortex-M33) bkpt without a debugger causes a re-entrant
    // fault → lockup, so we skip it.
    #[cfg(not(feature = "chip-rp2350"))]
    asm::bkpt();
    #[allow(clippy::empty_loop)]
    loop {}
}

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[no_mangle]
fn vApplicationMallocFailedHook() {
    // Intentionally a no-op: pvPortMalloc returns NULL after this hook,
    // allowing Rust's try_reserve_exact to return Err and trigger GC.
    // Non-try allocations still abort via Rust's handle_alloc_error.
}

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[no_mangle]
fn vApplicationStackOverflowHook(_pxTask: FreeRtosTaskHandle, _pcTaskName: FreeRtosCharPtr) {
    asm::bkpt();
    #[allow(clippy::empty_loop)]
    loop {}
}
