// SPDX-License-Identifier: GPL-3.0-only
//! Runtime reverse-translation for shrunk framework class names.
//!
//! Every native-dispatch match arm in `src/system/native_handler/**` and
//! the JVM's `class_name_to_static_in` fallback uses the ORIGINAL internal
//! class names (e.g. `"picodroid/pio/Gpio"`). When the active shrink map
//! is non-empty, the JVM hands dispatch the SHRUNK name (`"a/S"`). We
//! reverse-translate at dispatch entry so the literal match arms keep
//! working without mechanical churn.
//!
//! The table is generated by `build_support/papk.rs` from the active map.
//! When no map is active (default picodroid build), it's an identity
//! passthrough with zero overhead beyond a single function call.

// Defines: pub fn unshrink_class(name: &str) -> &str;
include!(concat!(env!("OUT_DIR"), "/framework_unshrink.rs"));
