// SPDX-License-Identifier: GPL-3.0-only
//! Board-derived configuration, generated by this crate's `build.rs` from the
//! active board's `board.toml`.
//!
//! The generators live in `build_support/board_cfg.rs` and are shared with
//! each `platforms/<family>/build.rs`, so a board.toml key is parsed in
//! exactly one place regardless of which crate consumes it. Boardless builds
//! (`cargo build -p picodroid-core` with no `board-*` feature) get the same
//! safe defaults the platform crate uses.
//!
//! Only *neutral* configuration lives here — sizes, counts, timings, and the
//! button table. Pin/SPI wiring stays with the family HAL. See
//! `docs/designs/shared-core-extraction.md` §3.D.

/// Display geometry. Pin and SPI wiring stay in the family HAL's own
/// `display_config.rs`; the platform crate asserts the two agree.
pub mod display {
    include!(concat!(env!("OUT_DIR"), "/display_dims.rs"));
}

/// FreeRTOS arena size for the active MCU — single-sourced with the C build's
/// `configTOTAL_HEAP_SIZE` (docs/parity-audit.md M2).
pub mod heap {
    include!(concat!(env!("OUT_DIR"), "/heap_config.rs"));
}

/// Activity-stack and pending-op FIFO depths.
pub mod jvm_state {
    include!(concat!(env!("OUT_DIR"), "/jvm_state_config.rs"));
}

/// Boot-time heap pre-reservation counts.
pub mod jvm_prereserve {
    include!(concat!(env!("OUT_DIR"), "/jvm_prereserve_config.rs"));
}

/// Background worker pool sizing.
pub mod background_pool {
    include!(concat!(env!("OUT_DIR"), "/background_pool_config.rs"));
}

/// LVGL widget handle-table slot count.
pub mod handle_table {
    include!(concat!(env!("OUT_DIR"), "/handle_table_config.rs"));
}

/// Idle-to-sleep timeout (`None` disables sleep).
pub mod sleep {
    include!(concat!(env!("OUT_DIR"), "/sleep_config.rs"));
}

/// Sensors declared by `[[sensor]]`, with their bus and address.
pub mod sensors {
    include!(concat!(env!("OUT_DIR"), "/sensor_table.rs"));
}

/// Hardware buttons as `(pin, LV_KEY_*, android_keycode)`.
///
/// The pin is the join key between `GpioEvent.pin` and Android keycodes, and
/// the simulator's keyboard emulation reads the same table — so it stays
/// shared, with pins opaque to this crate.
pub mod buttons {
    #[allow(unused_imports)]
    use crate::lvgl_ffi::*;
    include!(concat!(env!("OUT_DIR"), "/button_config.rs"));
}

#[cfg(test)]
mod tests {
    //! The board-config channel's own guard rails. These run boardless under
    //! `cargo test -p picodroid-core` and against the active board under the
    //! workspace test run, so both paths stay honest.

    #[test]
    fn display_geometry_is_sane() {
        assert!(super::display::SCREEN_WIDTH > 0);
        assert!(super::display::SCREEN_HEIGHT > 0);
        assert!(super::display::BAND_HEIGHT > 0);
        // A band must fit inside the screen, or the flush loop over-runs.
        assert!(
            super::display::BAND_HEIGHT <= super::display::SCREEN_HEIGHT as usize,
            "BAND_HEIGHT {} exceeds SCREEN_HEIGHT {}",
            super::display::BAND_HEIGHT,
            super::display::SCREEN_HEIGHT
        );
    }

    #[test]
    fn handle_slots_is_power_of_two() {
        // The table decodes a slot index by mask; a non-power-of-two would
        // silently alias handles onto the wrong slot.
        assert!(super::handle_table::HANDLE_SLOTS.is_power_of_two());
        assert!((32..=4096).contains(&super::handle_table::HANDLE_SLOTS));
    }

    #[test]
    fn jvm_state_depths_are_nonzero() {
        assert!(super::jvm_state::ACTIVITY_STACK_DEPTH > 0);
        assert!(super::jvm_state::PENDING_OP_QUEUE_DEPTH > 0);
    }

    #[test]
    fn background_pool_priority_in_bg_tier() {
        assert!((1..=10).contains(&super::background_pool::POOL_PRIORITY));
        assert!((1..=32).contains(&super::background_pool::POOL_THREADS));
    }

    #[test]
    fn heap_arena_is_plausible() {
        // Smallest supported part is the RP2040 at 128 KB.
        assert!(super::heap::DEVICE_HEAP_BYTES >= 64 * 1024);
    }

    #[test]
    fn button_table_matches_capability_cfg() {
        // has_buttons and a non-empty table are emitted from the same
        // board.toml section; a mismatch means the generator drifted.
        let declared = !super::buttons::BUTTONS.is_empty();
        let cfg_on = cfg!(has_buttons);
        assert_eq!(
            declared, cfg_on,
            "BUTTONS non-empty = {declared} but cfg(has_buttons) = {cfg_on}"
        );
    }

    #[test]
    fn sensor_table_matches_capability_cfg() {
        let declared = !super::sensors::SENSORS.is_empty();
        let cfg_on = cfg!(any_sensor);
        assert_eq!(
            declared, cfg_on,
            "SENSORS non-empty = {declared} but cfg(any_sensor) = {cfg_on}"
        );
    }
}
