// SPDX-License-Identifier: GPL-3.0-only
//! Board-derived configuration, generated by this crate's `build.rs` from the
//! active board's `board.toml`.
//!
//! The generators live in `build_support/board_cfg.rs` and are shared with
//! each `platforms/<family>/build.rs`, so a board.toml key is parsed in
//! exactly one place regardless of which crate consumes it. Boardless builds
//! (`cargo build -p picodroid-core` with no `board-*` feature) get the same
//! safe defaults the platform crate uses.
//!
//! Only *neutral* configuration lives here — sizes, counts, timings, and the
//! button table. Pin/SPI wiring stays with the family HAL. See
//! `docs/designs/shared-core-extraction.md` §3.D.

/// Display geometry. Pin and SPI wiring stay in the family HAL's own
/// `display_config.rs`; the platform crate asserts the two agree.
pub mod display {
    include!(concat!(env!("OUT_DIR"), "/display_dims.rs"));
}

/// FreeRTOS arena size for the active MCU — single-sourced with the C build's
/// `configTOTAL_HEAP_SIZE` (docs/parity-audit.md M2).
pub mod heap {
    include!(concat!(env!("OUT_DIR"), "/heap_config.rs"));
}

/// Activity-stack and pending-op FIFO depths.
pub mod jvm_state {
    include!(concat!(env!("OUT_DIR"), "/jvm_state_config.rs"));
}

/// Boot-time heap pre-reservation counts.
pub mod jvm_prereserve {
    include!(concat!(env!("OUT_DIR"), "/jvm_prereserve_config.rs"));
}

/// Background worker pool sizing.
pub mod background_pool {
    include!(concat!(env!("OUT_DIR"), "/background_pool_config.rs"));
}

/// LVGL widget handle-table slot count.
pub mod handle_table {
    include!(concat!(env!("OUT_DIR"), "/handle_table_config.rs"));
}

/// Idle-to-sleep timeout (`None` disables sleep).
pub mod sleep {
    include!(concat!(env!("OUT_DIR"), "/sleep_config.rs"));
}

/// Sensors declared by `[[sensor]]`, with their bus and address.
pub mod sensors {
    include!(concat!(env!("OUT_DIR"), "/sensor_table.rs"));
}

/// Hardware buttons as `(pin, LV_KEY_*, android_keycode)`.
///
/// The pin is the join key between `GpioEvent.pin` and Android keycodes, and
/// the simulator's keyboard emulation reads the same table — so it stays
/// shared, with pins opaque to this crate.
pub mod buttons {
    #[cfg_attr(not(has_buttons), allow(unused_imports))]
    use crate::lvgl_ffi::*;
    include!(concat!(env!("OUT_DIR"), "/button_config.rs"));

    /// GPIO pin of the first button declared with `keycode`, or `None` if this
    /// board has none.
    ///
    /// Lives beside the table rather than with any one caller because there
    /// are three — the LVGL event layer, the simulator's control channel, and
    /// the PDB `CMD_INPUT` handler — and the first two had each grown their
    /// own copy. Both had to, in fact: the graphics module is `cfg(not(test))`
    /// and the simulator front-end is not, so neither could use the other's.
    /// The table is always compiled, so this is.
    pub fn keycode_to_pin(keycode: i32) -> Option<u8> {
        BUTTONS
            .iter()
            .find(|&&(_, _, k)| k == keycode)
            .map(|&(p, _, _)| p)
    }
}

// ── Guard rails ──────────────────────────────────────────────────────────────
//
// Everything above is generated from board.toml, so every invariant worth
// checking is a compile-time constant. These are `const` assertions rather
// than tests on purpose: a malformed board fails the build it would break,
// including a firmware build on a machine that never runs the test suite.

const _: () = {
    assert!(display::SCREEN_WIDTH > 0);
    assert!(display::SCREEN_HEIGHT > 0);
    assert!(display::BAND_HEIGHT > 0);
    // A band must fit inside the screen, or the flush loop over-runs it.
    assert!(display::BAND_HEIGHT <= display::SCREEN_HEIGHT as usize);
};

const _: () = {
    // The handle table decodes a slot index by mask; a non-power-of-two
    // would silently alias handles onto the wrong slot.
    assert!(handle_table::HANDLE_SLOTS.is_power_of_two());
    assert!(handle_table::HANDLE_SLOTS >= 32 && handle_table::HANDLE_SLOTS <= 4096);
};

const _: () = {
    assert!(jvm_state::ACTIVITY_STACK_DEPTH > 0);
    assert!(jvm_state::PENDING_OP_QUEUE_DEPTH > 0);
};

const _: () = {
    // Workers live in the BG priority tier.
    assert!(background_pool::POOL_PRIORITY >= 1 && background_pool::POOL_PRIORITY <= 10);
    assert!(background_pool::POOL_THREADS >= 1 && background_pool::POOL_THREADS <= 32);
};

// Smallest supported part is the RP2040 at 128 KB.
const _: () = assert!(heap::DEVICE_HEAP_BYTES >= 64 * 1024);

// A capability cfg and its table are emitted from the same board.toml
// section, so disagreement means the generator drifted — and the symptom
// would be a board whose buttons or sensors silently do nothing.
const _: () = assert!(buttons::BUTTONS.is_empty() != cfg!(has_buttons));
const _: () = assert!(sensors::SENSORS.is_empty() != cfg!(any_sensor));
