// SPDX-License-Identifier: GPL-3.0-only
//! Runtime reverse-translation for shrunk framework class names.
//!
//! Every native-dispatch match arm in `src/system/native_handler/**` and
//! the JVM's `class_name_to_static_in` fallback uses the ORIGINAL internal
//! class names (e.g. `"picodroid/pio/Gpio"`). When the active shrink map
//! is non-empty, the JVM hands dispatch the SHRUNK name (`"a/S"`). We
//! reverse-translate at dispatch entry so the literal match arms keep
//! working without mechanical churn.
//!
//! The table is generated by `build_support/papk.rs` from the active map.
//! When no map is active (default picodroid build), it's an identity
//! passthrough with zero overhead beyond a single function call.

// Defines: pub fn unshrink_class(name: &str) -> &str;
include!(concat!(env!("OUT_DIR"), "/framework_unshrink.rs"));

/// Un-shrink every `L<class>;` chunk of a descriptor. Class files loaded
/// under `PICODROID_SHRINK=1` embed *shrunk* class names in descriptors
/// (tools/class-shrink rewrites them), so a test that compares loaded
/// descriptors against original names — `method_tables.rs`, the API
/// contract generator — must run them through this first, or every
/// object-typed row fails only in the shrink lane of `scripts/test.sh`.
///
/// Both namespaces are undone: `a/` (framework, this crate's table) and
/// `b/` (`java/**`, pico-jvm's table — the JVM translates those at its
/// class-file boundary for names, but descriptors are read raw).
#[cfg(test)]
pub fn unshrink_descriptor(desc: &str) -> String {
    let mut out = String::with_capacity(desc.len());
    let mut rest = desc;
    while let Some(pos) = rest.find('L') {
        let (head, tail) = rest.split_at(pos);
        out.push_str(head);
        let end = tail
            .find(';')
            .unwrap_or_else(|| panic!("unterminated class ref in descriptor {desc:?}"));
        out.push('L');
        out.push_str(pico_jvm::unshrink_java_str(unshrink_class(&tail[1..end])));
        out.push(';');
        rest = &tail[end + 1..];
    }
    out.push_str(rest);
    out
}

#[cfg(test)]
mod tests {
    use super::{shrink_class, unshrink_descriptor};

    /// `unshrink_descriptor` must invert whatever the active shrink map did
    /// to a descriptor — constructed via `shrink_class` so it exercises the
    /// real map in the shrink lane and identity in the no-shrink lane.
    #[test]
    fn unshrink_descriptor_inverts_active_map() {
        assert_eq!(unshrink_descriptor("(IJ)Z"), "(IJ)Z");
        let intent = shrink_class("picodroid/content/Intent");
        let view = shrink_class("picodroid/view/View");
        let input = format!("(L{intent};I)L{view};");
        assert_eq!(
            unshrink_descriptor(&input),
            "(Lpicodroid/content/Intent;I)Lpicodroid/view/View;"
        );
    }

    /// Over the whole embedded corpus no shrunk segment — `a/` or `b/` —
    /// survives `unshrink_descriptor`, and once the active map carries `b/`
    /// entries at least one `java/**` descriptor was actually translated
    /// (otherwise the shrink lane would be silently vacuous).
    #[test]
    fn unshrink_descriptor_covers_java_names_in_the_corpus() {
        let mut shrunk_java_seen = 0;
        for bytes in crate::framework_classes::FRAMEWORK_CLASSES {
            let cf = pico_jvm::class_file::ClassFile::parse(bytes).expect("parse framework class");
            for m in cf.methods() {
                let raw = core::str::from_utf8(cf.cp_utf8(m.descriptor_index).unwrap()).unwrap();
                let un = unshrink_descriptor(raw);
                assert!(
                    !un.contains("La/") && !un.contains("Lb/"),
                    "shrunk segment survived: {raw} -> {un}"
                );
                if raw.contains("Lb/") {
                    shrunk_java_seen += 1;
                    assert!(un.contains("Ljava/"), "{raw} -> {un}");
                }
            }
        }
        let java_map_active = pico_jvm::unshrink_java_str("b/A") != "b/A";
        if java_map_active && !crate::framework_classes::FRAMEWORK_CLASSES.is_empty() {
            assert!(
                shrunk_java_seen > 0,
                "the active map shrinks java/** but no framework descriptor carries a b/ name"
            );
        }
    }
}
