// SPDX-License-Identifier: GPL-3.0-only
//! Simulator display backend using minifb to render LVGL output in a desktop
//! window.  Replaces the previous no-op stubs so that graphical apps (e.g.
//! `displaydemo`) can be tested without hardware.

use core::sync::atomic::{AtomicBool, AtomicU32, Ordering};
use minifb::{Key, MouseButton, MouseMode, Scale, ScaleMode, Window, WindowOptions};

// Display geometry from [display] in board.toml. This reads the *neutral*
// `display_dims.rs` rather than the family HAL's pin-bearing
// `display_config.rs`: a window on the host has no backlight pin, reset pin
// or MADCTL, so the simulator never needed that half — and depending on it
// would have tied this module back to one family's build script.
pub use crate::board_cfg::display::BAND_HEIGHT;
pub use crate::board_cfg::display::DRAW_BUFFERS;
pub use crate::board_cfg::display::SCREEN_HEIGHT as HEIGHT;
pub use crate::board_cfg::display::SCREEN_WIDTH as WIDTH;
pub use crate::board_cfg::display::SCROLL_LIMIT;

// Button table generated by build.rs from `[[button]]` in board.toml — drives
// the sim's keyboard + control-channel button emulation (see the "Button
// emulation" section). Absent on boards without `[[button]]` entries (then
// `has_buttons` is unset and none of the button code below compiles).
#[cfg(has_buttons)]
mod button_generated {
    use crate::lvgl_ffi::*;
    include!(concat!(env!("OUT_DIR"), "/button_config.rs"));
}
#[cfg(has_buttons)]
use button_generated::BUTTONS;

const NUM_PIXELS: usize = WIDTH as usize * HEIGHT as usize;

/// Enter a simulated-heap-cap bypass region for host-only minifb allocations
/// (the full-screen window buffer, X11 image buffers) until the returned guard
/// drops. See `sim_allocator::bypass`.
///
/// `sim_allocator` carries the `#[global_allocator]` and is only compiled with
/// the `sim` feature, but this module also builds under `cfg(test)` so its unit
/// tests run — there the cap doesn't exist, so the guard is a no-op.
#[cfg(feature = "sim")]
fn heap_cap_bypass() -> impl Drop {
    crate::host::heap_bypass()
}
#[cfg(not(feature = "sim"))]
fn heap_cap_bypass() -> impl Drop {
    struct Noop;
    impl Drop for Noop {
        fn drop(&mut self) {}
    }
    Noop
}

// ── Statics (single-threaded sim — safe) ────────────────────────────────────

static mut WINDOW: Option<Window> = None;
static mut FRAMEBUF: [u32; NUM_PIXELS] = [0u32; NUM_PIXELS];

/// Current draw region set by `set_window()`.
static mut WIN_X0: u16 = 0;
static mut WIN_Y0: u16 = 0;
static mut WIN_X1: u16 = 0;
static mut WIN_Y1: u16 = 0;

/// The panel's vertical-scroll registers, emulated (ST7796 VSCRDEF and
/// VSCRSADD; `hal::display::set_vertical_scroll_*`). `FRAMEBUF` above is the
/// panel's frame memory, written through the window exactly as the device
/// writes RAMWR; what the glass shows is composed from it in
/// [`update_window`] through this mapping, so a wrong wrap or a stale strip
/// in `graphics/lvgl/hw_scroll.rs` is a wrong picture in the sim window, not
/// a hardware-only bug. `VSCROLL_ROWS == 0` means no area is defined —
/// identity, the panel's power-on state.
static mut VSCROLL_TOP: u16 = 0;
static mut VSCROLL_ROWS: u16 = 0;
static mut VSCROLL_START: u16 = 0;

/// Mouse state sampled during `update_window()`. Atomic because the touch
/// sampler reads it from its own task on boards where that runs, while
/// `update_window` writes it from the UI task; the position is one word so a
/// reader never sees an X from one frame with a Y from another.
static MOUSE_PRESSED: AtomicBool = AtomicBool::new(false);
static MOUSE_POS: AtomicU32 = AtomicU32::new(0);

/// Scripted-touch override (control channel `touch down|move|up`). While
/// engaged it replaces the mouse sample in [`mouse_state`], so scripted
/// touches run the exact same XPT2046-emulation pipeline as real mouse
/// input. The state machine is core's, the same one the RP family's touch
/// driver uses; the control channel reader drives it from its own thread.
use crate::hal::touch_override::{OverrideSample, TouchOverride};
static TOUCH_OVERRIDE: TouchOverride = TouchOverride::new();

// ── Public API (matches hal::display contract) ──────────────────────────────

pub fn init() {
    // The control channel works even headless (no window needed), so
    // start it before the window/headless branch below.
    #[cfg(any(has_buttons, has_touch))]
    spawn_control_channel();

    // Headless mode: requested explicitly, or no DISPLAY/WAYLAND_DISPLAY in
    // env (common in CI). `WINDOW` stays `None` — `update_window` /
    // `mouse_state` / `is_window_open` already handle that branch, and the
    // framebuffer writes are harmless no-ops. Lets sim-run.sh exercise
    // Activity-based apps (displaydemo, callbacktest) under the shrink
    // matrix without an X server.
    let force_headless = std::env::var("PICODROID_SIM_HEADLESS")
        .map(|v| v == "1")
        .unwrap_or(false);
    let no_display = std::env::var("DISPLAY").is_err() && std::env::var("WAYLAND_DISPLAY").is_err();
    if force_headless || no_display {
        println!("[sim] Display: headless (no window)");
        return;
    }

    // Double small panels so they are comfortable to look at, but only while
    // the result still fits on an ordinary screen. The 240- and 320-pixel
    // boards all double to at most 640x480; a 320x480 panel would become
    // 640x960, taller than the usable height of most 1080p displays, and
    // `ScaleMode` cannot rescue that — minifb's `Scale` is what sets the
    // multiplier, and the window is simply that many pixels tall.
    const MAX_SCALED_EDGE: u32 = 720;
    let doubles = (WIDTH as u32) * 2 <= MAX_SCALED_EDGE && (HEIGHT as u32) * 2 <= MAX_SCALED_EDGE;
    let opts = WindowOptions {
        scale: if doubles { Scale::X2 } else { Scale::X1 },
        scale_mode: ScaleMode::AspectRatioStretch,
        ..WindowOptions::default()
    };

    // Treat window-creation failure the same as headless — never panic, so a
    // local run without a working display still boots the JVM and flushes
    // logs instead of aborting before any Log.i() fires.
    //
    // Bypass the simulated-heap cap while minifb allocates its full-screen
    // backing buffer (≈900 KB at Scale::X2) — a host rendering artifact with no
    // MCU counterpart. See `sim_allocator::bypass`.
    let win_result = {
        let _bypass = heap_cap_bypass();
        Window::new("picodroid", WIDTH as usize, HEIGHT as usize, opts)
    };
    let mut win = match win_result {
        Ok(w) => w,
        Err(e) => {
            println!("[sim] Display: headless (window creation failed: {e})");
            return;
        }
    };

    // Limit update rate to ~60 fps
    win.set_target_fps(60);

    unsafe {
        WINDOW = Some(win);
    }
}

pub fn set_window(x0: u16, y0: u16, x1: u16, y1: u16) {
    unsafe {
        WIN_X0 = x0;
        WIN_Y0 = y0;
        WIN_X1 = x1;
        WIN_Y1 = y1;
    }
}

/// Write byte-swapped RGB565 pixel data into the framebuffer at the region
/// previously set by `set_window()`.
pub fn write_pixels(data: &[u8]) {
    unsafe {
        let x0 = WIN_X0 as usize;
        let y0 = WIN_Y0 as usize;
        let x1 = WIN_X1 as usize;
        let _w = x1 - x0 + 1;
        let stride = WIDTH as usize;

        let mut i = 0; // byte index into data
        let mut row = y0;
        let mut col = x0;

        while i + 1 < data.len() {
            // LV_COLOR_16_SWAP=1: bytes arrive big-endian
            let raw = u16::from_be_bytes([data[i], data[i + 1]]);
            let r = ((raw >> 11) & 0x1F) as u32;
            let g = ((raw >> 5) & 0x3F) as u32;
            let b = (raw & 0x1F) as u32;
            let argb = 0xFF00_0000 | (r * 255 / 31) << 16 | (g * 255 / 63) << 8 | (b * 255 / 31);

            FRAMEBUF[row * stride + col] = argb;

            col += 1;
            if col > x1 {
                col = x0;
                row += 1;
            }
            i += 2;
        }
    }
}

/// There is no transfer to overlap here: a band is in the frame memory by
/// the time [`write_pixels`] returns, so the asynchronous pair collapses to
/// the synchronous call. LVGL still alternates its two buffers on a
/// `draw_buffers = 2` board, so the swap logic is exercised; only the overlap
/// is hardware's.
pub fn write_pixels_start(data: &[u8]) {
    write_pixels(data)
}

pub fn write_pixels_wait() {}

pub fn set_backlight(on: bool) {
    println!("[sim] Display: backlight {}", if on { "ON" } else { "OFF" });
}

/// Emulated VSCRDEF: memory lines `[top_fixed, top_fixed + rows)` scroll.
pub fn set_vertical_scroll_area(top_fixed: u16, rows: u16) {
    unsafe {
        VSCROLL_TOP = top_fixed;
        VSCROLL_ROWS = rows.min(HEIGHT.saturating_sub(top_fixed));
    }
}

/// Emulated VSCRSADD: the memory line shown at the first row of the area.
pub fn set_vertical_scroll_start(line: u16) {
    unsafe {
        VSCROLL_START = line;
    }
}

/// The memory row the panel shows at display row `y`, under the emulated
/// scroll registers. Rows outside the scroll area, and every row while no
/// area is defined, map to themselves.
fn memory_row_for(y: usize, top: usize, rows: usize, start: usize) -> usize {
    if rows == 0 || y < top || y >= top + rows {
        return y;
    }
    // The start line is taken modulo the area, which is also what keeps an
    // out-of-range register value from indexing past the buffer.
    top + (start.wrapping_sub(top) + (y - top)) % rows
}

/// Whether the emulated scroll registers map any row somewhere other than
/// itself — the test for needing a composed frame in [`update_window`].
fn vscroll_is_identity() -> bool {
    unsafe { VSCROLL_ROWS == 0 || VSCROLL_START == VSCROLL_TOP }
}

/// Compose what the glass shows into `dst` from the frame memory `src`,
/// through the emulated scroll registers.
fn compose_scrolled(dst: &mut [u32], src: &[u32]) {
    let stride = WIDTH as usize;
    let (top, rows, start) = unsafe {
        (
            VSCROLL_TOP as usize,
            VSCROLL_ROWS as usize,
            VSCROLL_START as usize,
        )
    };
    for y in 0..HEIGHT as usize {
        let src_row = memory_row_for(y, top, rows, start);
        dst[y * stride..(y + 1) * stride]
            .copy_from_slice(&src[src_row * stride..(src_row + 1) * stride]);
    }
}

pub fn display_sleep() {
    println!("[sim] Display: sleep");
}

pub fn display_wake() {
    println!("[sim] Display: wake");
}

// ── Emulator-specific functions ─────────────────────────────────────────────

/// Blit the framebuffer to the minifb window and sample mouse state.
///
/// Call once per frame after `with_gfx(|g| g.tick(16))`.
pub fn update_window() {
    unsafe {
        if let Some(ref mut win) = WINDOW {
            // The frame memory is shown through a copy when the picture is
            // not the memory: the emulated scroll registers move rows
            // (`compose_scrolled`), and PICODROID_SIM_TAP_DEBUG=1 paints a
            // red crosshair at the raw mouse and a green one at the
            // post-XPT2046-pipeline coordinate, to see exactly what the
            // dispatcher will receive vs where you clicked when chasing
            // widget hit-test bugs that only repro on device.
            let scrolled = !vscroll_is_identity();
            let buf: &[u32] = if scrolled || tap_debug_enabled() {
                let dst_ptr = core::ptr::addr_of_mut!(COMPOSE_BUF) as *mut u32;
                let dst = core::slice::from_raw_parts_mut(dst_ptr, NUM_PIXELS);
                let src_ptr = core::ptr::addr_of!(FRAMEBUF) as *const u32;
                let src = core::slice::from_raw_parts(src_ptr, NUM_PIXELS);
                if scrolled {
                    compose_scrolled(dst, src);
                } else {
                    dst.copy_from_slice(src);
                }
                if tap_debug_enabled() {
                    paint_tap_debug(dst);
                }
                dst
            } else {
                let ptr = core::ptr::addr_of!(FRAMEBUF) as *const u32;
                core::slice::from_raw_parts(ptr, NUM_PIXELS)
            };
            // Bypass the heap cap: minifb may reallocate its host-only backing
            // buffer here (e.g. on an X11 ConfigureNotify). See
            // `sim_allocator::bypass`.
            {
                let _bypass = heap_cap_bypass();
                win.update_with_buffer(buf, WIDTH as usize, HEIGHT as usize)
                    .unwrap_or(());
            }

            // Sample mouse state for touch emulation
            MOUSE_PRESSED.store(win.get_mouse_down(MouseButton::Left), Ordering::Relaxed);
            if let Some((mx, my)) = win.get_mouse_pos(MouseMode::Clamp) {
                let x = (mx as u16).min(WIDTH - 1) as u32;
                let y = (my as u16).min(HEIGHT - 1) as u32;
                MOUSE_POS.store((x << 16) | y, Ordering::Relaxed);
            }

            // Synthesize button GPIO edges from the host keyboard. Sampled here,
            // right after `update_with_buffer`, while minifb's per-frame key
            // state is fresh (each press/release edge is reported for exactly
            // one frame).
            #[cfg(has_buttons)]
            poll_keyboard(win);
        }
    }
}

/// Scratch for a composed frame: the scrolled picture, the tap-debug
/// crosshairs, or both.
static mut COMPOSE_BUF: [u32; NUM_PIXELS] = [0u32; NUM_PIXELS];

// ── Tap-debug overlay (PICODROID_SIM_TAP_DEBUG=1) ───────────────────────────

static TAP_DEBUG_INIT: std::sync::Once = std::sync::Once::new();
static mut TAP_DEBUG_ON: bool = false;

fn tap_debug_enabled() -> bool {
    unsafe {
        TAP_DEBUG_INIT.call_once(|| {
            TAP_DEBUG_ON = std::env::var("PICODROID_SIM_TAP_DEBUG")
                .map(|v| v == "1")
                .unwrap_or(false);
            if TAP_DEBUG_ON {
                println!("[sim] Tap debug overlay: ON (red=raw mouse, green=post-driver)");
            }
        });
        TAP_DEBUG_ON
    }
}

unsafe fn paint_tap_debug(buf: &mut [u32]) {
    let pos = MOUSE_POS.load(Ordering::Relaxed);
    let (mx, my) = ((pos >> 16) as u16, (pos & 0xFFFF) as u16);
    if !MOUSE_PRESSED.load(Ordering::Relaxed) {
        return;
    }
    // Red crosshair at the raw mouse position.
    paint_crosshair(buf, mx, my, 0xFFFF_0000);
    // Green crosshair at what the touch driver actually emits — same call
    // path the JVM dispatcher uses. Through the sampler, because where that
    // runs it is the panel's only reader.
    if let Some((tx, ty)) = crate::hal::touch_sampler::latest() {
        paint_crosshair(buf, tx, ty, 0xFF00_FF00);
    }
}

fn paint_crosshair(buf: &mut [u32], cx: u16, cy: u16, color: u32) {
    let stride = WIDTH as usize;
    let cx = cx as i32;
    let cy = cy as i32;
    for d in -4i32..=4 {
        let x = cx + d;
        if (0..WIDTH as i32).contains(&x) {
            buf[cy as usize * stride + x as usize] = color;
        }
        let y = cy + d;
        if (0..HEIGHT as i32).contains(&y) {
            buf[y as usize * stride + cx as usize] = color;
        }
    }
}

/// Returns `true` if the emulator window is still open (user hasn't closed it).
pub fn is_window_open() -> bool {
    unsafe {
        let ptr = &raw const WINDOW;
        match &*ptr {
            // Escape is the sim-close key and is therefore reserved — the button
            // emulation keymap (`key_to_pin`) must never map it.
            Some(win) => win.is_open() && !win.is_key_down(Key::Escape),
            None => true, // no window yet — don't block
        }
    }
}

/// Engage the scripted-touch override at `(x, y)` (press or drag-move). While
/// active it replaces the mouse sample in [`mouse_state`]. Shared by the
/// control channel and the `hal::sim::touch` override shims (HAL contract).
pub fn set_touch_override(x: u16, y: u16) {
    TOUCH_OVERRIDE.inject(x, y)
}

/// Lift the scripted touch but keep the override engaged, so the RELEASE edge
/// is observed from the scripted position before mouse sampling resumes.
pub fn touch_override_release() {
    TOUCH_OVERRIDE.release()
}

/// Disengage the override entirely; [`mouse_state`] returns to the real mouse.
pub fn clear_touch_override() {
    TOUCH_OVERRIDE.clear()
}

/// Returns `(pressed, x, y)` — the most recent mouse state sampled by
/// `update_window()`.
pub fn mouse_state() -> (bool, u16, u16) {
    match TOUCH_OVERRIDE.sample() {
        OverrideSample::Inactive => {
            let pos = MOUSE_POS.load(Ordering::Relaxed);
            (
                MOUSE_PRESSED.load(Ordering::Relaxed),
                (pos >> 16) as u16,
                (pos & 0xFFFF) as u16,
            )
        }
        OverrideSample::Pressed(x, y) => (true, x, y),
        OverrideSample::Lifted(x, y) => (false, x, y),
    }
}

// ── Button emulation (sim only) ─────────────────────────────────────────────
//
// picoenvmon-class boards have physical buttons and no touchscreen, so the
// sim can't read GPIO. Two front-ends synthesize button edges into the shared
// `hal::sim::gpio` queue, from where the real on-device pipeline takes over
// unchanged: LVGL keypad indev → focus navigation / ENTER activation → the
// phantom-release filter → Java `View.fireKey` → BACK routing. Both front-ends
// resolve a button to a GPIO pin via the generated `BUTTONS` table, so any
// `[[button]]` board is drivable, not just picoenvmon.

/// LVGL key code (`LV_KEY_*`) → GPIO pin of the first button declared with it.
#[cfg(has_buttons)]
fn lvkey_to_pin(lv_key: u32) -> Option<u8> {
    BUTTONS
        .iter()
        .find(|&&(_, k, _)| k == lv_key)
        .map(|&(p, _, _)| p)
}

/// Host keyboard key → button pin. Named keys mirror the navigation semantics
/// (`↑`=PREV, `↓`=NEXT, `Enter`=ENTER, `Backspace`=BACK); the digit keys are a
/// board-generic fallback (`1` → first declared button, `2` → second, …).
/// `Escape` is deliberately unmapped — it closes the sim (`is_window_open`).
#[cfg(has_buttons)]
fn key_to_pin(key: Key) -> Option<u8> {
    use crate::lvgl_ffi::{LV_KEY_ENTER, LV_KEY_ESC, LV_KEY_NEXT, LV_KEY_PREV};
    match key {
        Key::Up => lvkey_to_pin(LV_KEY_PREV),
        Key::Down => lvkey_to_pin(LV_KEY_NEXT),
        Key::Enter => lvkey_to_pin(LV_KEY_ENTER),
        Key::Backspace => lvkey_to_pin(LV_KEY_ESC),
        Key::Key1 => BUTTONS.first().map(|&(p, _, _)| p),
        Key::Key2 => BUTTONS.get(1).map(|&(p, _, _)| p),
        Key::Key3 => BUTTONS.get(2).map(|&(p, _, _)| p),
        Key::Key4 => BUTTONS.get(3).map(|&(p, _, _)| p),
        _ => None,
    }
}

/// Sample the host keyboard and inject button edges. Active-low: key-down is a
/// PRESS (falling, `rising=false`), key-up a RELEASE (rising). A tap therefore
/// produces one clean PRESS/RELEASE pair through the phantom-release filter.
#[cfg(has_buttons)]
fn poll_keyboard(win: &Window) {
    for key in win.get_keys_pressed(minifb::KeyRepeat::No) {
        if let Some(pin) = key_to_pin(key) {
            super::gpio::inject(pin, false);
        }
    }
    for key in win.get_keys_released() {
        if let Some(pin) = key_to_pin(key) {
            super::gpio::inject(pin, true);
        }
    }
}

/// Control-channel button token → pin: silkscreen letters (`A`/`B`/`X`/`Y` →
/// 1st/2nd/3rd/4th declared button), semantic names (`PREV`/`NEXT`/`ENTER`/
/// `ESC`/`BACK`/…), or a bare GPIO pin number.
#[cfg(has_buttons)]
fn name_to_pin(tok: &str) -> Option<u8> {
    use crate::lvgl_ffi::{LV_KEY_ENTER, LV_KEY_ESC, LV_KEY_NEXT, LV_KEY_PREV};
    let nth = |i: usize| BUTTONS.get(i).map(|&(p, _, _)| p);
    match tok.trim().to_ascii_uppercase().as_str() {
        "A" => nth(0),
        "B" => nth(1),
        "X" => nth(2),
        "Y" => nth(3),
        "PREV" | "UP" => lvkey_to_pin(LV_KEY_PREV),
        "NEXT" | "DOWN" => lvkey_to_pin(LV_KEY_NEXT),
        "ENTER" | "OK" | "SELECT" => lvkey_to_pin(LV_KEY_ENTER),
        "ESC" | "BACK" => lvkey_to_pin(LV_KEY_ESC),
        other => other.parse::<u8>().ok(),
    }
}

/// Parse and apply one control-channel line: `down|up|press|tap <button>` or
/// `touch down <x> <y>` / `touch move <x> <y>` / `touch up`.
#[cfg(any(has_buttons, has_touch))]
fn handle_control_line(line: &str) {
    let mut it = line.split_whitespace();
    let Some(cmd) = it.next() else {
        return; // blank line — ignore
    };

    if cmd.eq_ignore_ascii_case("memstats") {
        // Heap access belongs to the main task — just raise the request
        // flag; the monitor prints the snapshot on the next 16 ms tick.
        #[cfg(feature = "mem-diag")]
        crate::mem_diag::request_memstats();
        #[cfg(not(feature = "mem-diag"))]
        println!("[sim] memstats: built without mem-diag (rebuild with sim.sh --mem-diag)");
        return;
    }

    if cmd.eq_ignore_ascii_case("heapcensus") {
        // Same request-flag discipline as `memstats`: the census walks the
        // heaps, so only the main task may run it.
        #[cfg(feature = "mem-diag")]
        crate::mem_diag::request_census();
        #[cfg(not(feature = "mem-diag"))]
        println!("[sim] heapcensus: built without mem-diag (rebuild with sim.sh --mem-diag)");
        return;
    }

    if cmd.eq_ignore_ascii_case("touch") {
        handle_touch_command(&mut it);
        return;
    }

    // `apps list|install <papk>|uninstall <package>` — the package
    // directory's verbs, queued here and served on the JVM task.
    if cmd.eq_ignore_ascii_case("apps") {
        #[cfg(feature = "sim")]
        super::app_region::request(&it.collect::<Vec<&str>>().join(" "));
        #[cfg(not(feature = "sim"))]
        println!("[sim] apps: not available in this build");
        return;
    }

    // `input …` — the same Android verbs the PDB `CMD_INPUT` handler accepts on
    // real hardware (`pdb input tap|swipe|keyevent|dpad|back`), so a script or
    // AI agent drives sim and device through one vocabulary.
    if cmd.eq_ignore_ascii_case("input") {
        handle_input_command(&mut it);
        return;
    }

    #[cfg(has_buttons)]
    {
        let Some(btn) = it.next() else {
            return; // missing argument — ignore
        };
        let Some(pin) = name_to_pin(btn) else {
            println!("[sim] control channel: unknown button '{btn}'");
            return;
        };
        match cmd.to_ascii_lowercase().as_str() {
            "down" => super::gpio::inject(pin, false),
            "up" => super::gpio::inject(pin, true),
            // The gap lets a PRESSED frame render before the release, so
            // focus-highlight movement is visible and the two edges land in
            // distinct ticks — the same reason the device handler pauses.
            "press" | "tap" => crate::input_inject::press_release::<SimSink>(pin),
            other => println!("[sim] control channel: unknown command '{other}'"),
        }
    }
    #[cfg(not(has_buttons))]
    {
        println!("[sim] control channel: unknown command '{cmd}' (no buttons on this board)");
    }
}

/// `touch down <x> <y>` — press at (x, y); `touch move <x> <y>` — drag while
/// pressed; `touch up` — release and hand control back to the mouse. The
/// override feeds [`mouse_state`], so the scripted press runs the full
/// XPT2046-emulation pipeline (median filter, calibration) like real input.
#[cfg(any(has_buttons, has_touch))]
fn handle_touch_command(it: &mut core::str::SplitWhitespace<'_>) {
    let Some(sub) = it.next() else {
        println!("[sim] control channel: touch needs down|move|up");
        return;
    };
    let parse_xy = |it: &mut core::str::SplitWhitespace<'_>| -> Option<(u16, u16)> {
        let x = it.next()?.parse::<u16>().ok()?;
        let y = it.next()?.parse::<u16>().ok()?;
        Some((x.min(WIDTH - 1), y.min(HEIGHT - 1)))
    };
    match sub.to_ascii_lowercase().as_str() {
        "down" | "move" => {
            let Some((x, y)) = parse_xy(it) else {
                println!("[sim] control channel: touch {sub} needs <x> <y>");
                return;
            };
            set_touch_override(x, y);
        }
        "up" => {
            touch_override_release();
            // Keep the override active for a few frames so the release edge
            // is observed from the scripted position, then return control to
            // the mouse. Same settle the gesture helpers use — a different
            // verb shape, but the identical reason, so it takes the shared
            // constant rather than another literal.
            std::thread::sleep(std::time::Duration::from_millis(
                crate::input_inject::TOUCH_SETTLE_MS as u64,
            ));
            clear_touch_override();
        }
        other => println!("[sim] control channel: unknown touch subcommand '{other}'"),
    }
}

/// Resolve an `input keyevent` token to an Android keycode: a known
/// `KEYCODE_*` name (with or without the prefix, case-insensitive) or a bare
/// integer. The name table is `pdb_protocol::keycodes` — the same one the
/// host `pdb input` resolves with, so scripts move between the two front-ends
/// unchanged.
#[cfg(has_buttons)]
fn input_keycode(tok: &str) -> Option<i32> {
    pdb_protocol::keycodes::keycode_from_name(tok).or_else(|| tok.trim().parse::<i32>().ok())
}

/// `input dpad <dir>` → Android keycode.
#[cfg(has_buttons)]
fn input_dpad_keycode(dir: &str) -> Option<i32> {
    pdb_protocol::keycodes::dpad_keycode(dir)
}

/// Android keycode → button pin. Shared with the graphics event layer and
/// the PDB input handler; it sits beside the generated table because the
/// three callers cannot reach each other's copies (see
/// [`crate::board_cfg::buttons::keycode_to_pin`]).
#[cfg(has_buttons)]
use crate::board_cfg::buttons::keycode_to_pin;

/// Handle `input keyevent|dpad|back` — resolve to a button pin and inject a
/// press/release. `verb` is the already-lowercased subcommand.
#[cfg(has_buttons)]
fn handle_key_verb(verb: &str, it: &mut core::str::SplitWhitespace<'_>) {
    let code = match verb {
        "keyevent" => it.next().and_then(input_keycode),
        "dpad" => it.next().and_then(input_dpad_keycode),
        "back" => Some(pdb_protocol::keycodes::KEYCODE_BACK),
        _ => None,
    };
    match code.and_then(keycode_to_pin) {
        Some(pin) => crate::input_inject::press_release::<SimSink>(pin),
        None => println!("[sim] control channel: input {verb} — no button for that keycode"),
    }
}

/// Button-less board: `input keyevent|dpad|back` have nothing to drive.
#[cfg(not(has_buttons))]
#[cfg_attr(test, allow(dead_code))]
fn handle_key_verb(verb: &str, _it: &mut core::str::SplitWhitespace<'_>) {
    println!("[sim] control channel: input {verb} — no buttons on this board");
}

#[cfg(any(has_buttons, has_touch))]
fn clamp_xy(x: u16, y: u16) -> (u16, u16) {
    (x.min(WIDTH - 1), y.min(HEIGHT - 1))
}

/// Injects straight into this module's siblings.
///
/// Deliberately not through [`crate::hal`]'s facade: inside this crate that
/// would route out through the platform's registration and back into these
/// same functions. The device-side handler uses the facade, which is correct
/// there — see [`crate::input_inject`].
#[cfg(any(has_buttons, has_touch))]
struct SimSink;

#[cfg(any(has_buttons, has_touch))]
impl crate::input_inject::InputSink for SimSink {
    fn gpio_inject(pin: u8, rising: bool) {
        super::gpio::inject(pin, rising)
    }
    fn touch_set(x: u16, y: u16) {
        set_touch_override(x, y)
    }
    fn touch_release() {
        touch_override_release()
    }
    fn touch_clear() {
        clear_touch_override()
    }
    fn delay_ms(ms: u32) {
        std::thread::sleep(std::time::Duration::from_millis(ms as u64))
    }
}

/// Parse and apply one `input …` line — the Android verb family:
/// `keyevent <KEYCODE|n>`, `dpad <dir>`, `back`, `tap <x> <y>`,
/// `swipe <x1> <y1> <x2> <y2> [ms]`.
#[cfg(any(has_buttons, has_touch))]
fn handle_input_command(it: &mut core::str::SplitWhitespace<'_>) {
    use crate::input_inject as inject;

    let Some(sub) = it.next() else {
        println!("[sim] control channel: input needs keyevent|dpad|back|tap|swipe");
        return;
    };
    let parse_u16 =
        |it: &mut core::str::SplitWhitespace<'_>| it.next().and_then(|s| s.parse().ok());

    let verb = sub.to_ascii_lowercase();
    match verb.as_str() {
        "keyevent" | "dpad" | "back" => handle_key_verb(&verb, it),
        "tap" => {
            let (Some(x), Some(y)) = (parse_u16(it), parse_u16(it)) else {
                println!("[sim] control channel: input tap needs <x> <y>");
                return;
            };
            let (x, y) = clamp_xy(x, y);
            inject::tap::<SimSink>(x, y);
        }
        "swipe" => {
            let (Some(x1), Some(y1), Some(x2), Some(y2)) =
                (parse_u16(it), parse_u16(it), parse_u16(it), parse_u16(it))
            else {
                println!("[sim] control channel: input swipe needs <x1> <y1> <x2> <y2> [ms]");
                return;
            };
            let dur: u32 = parse_u16(it)
                .map(u32::from)
                .unwrap_or(inject::SWIPE_DEFAULT_MS);
            let (x1, y1) = clamp_xy(x1, y1);
            let (x2, y2) = clamp_xy(x2, y2);
            inject::swipe::<SimSink>(x1, y1, x2, y2, dur);
        }
        other => println!("[sim] control channel: unknown input subcommand '{other}'"),
    }
}

/// Spawn the background reader that turns text commands into button edges.
/// Reads stdin by default, or the FIFO named by `PICODROID_SIM_CTRL_FIFO`.
/// Works headless — the deterministic path for scripted / CI button sequences.
#[cfg(any(has_buttons, has_touch))]
fn spawn_control_channel() {
    use std::io::BufRead;
    // Host-only I/O thread: keep pthread internals and the reader's buffers
    // off the simulated heap (no device analog; the device side is a GPIO
    // ISR with zero allocation).
    let _spawn_bypass = heap_cap_bypass();
    std::thread::spawn(|| {
        let _bypass = heap_cap_bypass();
        let reader: Box<dyn BufRead> = match std::env::var("PICODROID_SIM_CTRL_FIFO") {
            // Open the FIFO read+write so the reader itself holds a writer end:
            // reads then never hit EOF when an external `echo > fifo` writer
            // closes, so each command sent as a separate `echo` is delivered.
            // (A read-only open would end the loop after the first writer left.)
            Ok(path) => match std::fs::OpenOptions::new()
                .read(true)
                .write(true)
                .open(&path)
            {
                Ok(f) => Box::new(std::io::BufReader::new(f)),
                Err(e) => {
                    println!("[sim] control channel: cannot open FIFO '{path}': {e}");
                    return;
                }
            },
            Err(_) => Box::new(std::io::BufReader::new(std::io::stdin())),
        };
        for line in reader.lines().map_while(Result::ok) {
            handle_control_line(&line);
        }
    });
    println!(
        "[sim] control channel ready — commands: \
         'down|up|press|tap <A|B|X|Y|PREV|NEXT|ENTER|ESC|pin>', \
         'touch down|move <x> <y>', 'touch up', \
         'input keyevent|dpad|back|tap|swipe …' (Android-verb, matches 'pdb input'){}",
        if cfg!(feature = "mem-diag") {
            ", 'memstats', 'heapcensus'"
        } else {
            ""
        }
    );
}

#[cfg(test)]
mod vscroll_tests {
    use super::memory_row_for;

    #[test]
    fn rows_outside_the_area_and_an_undefined_area_map_to_themselves() {
        for y in [0usize, 43, 480] {
            assert_eq!(memory_row_for(y, 44, 436, 60), y);
        }
        assert_eq!(memory_row_for(200, 0, 0, 60), 200);
    }

    #[test]
    fn the_start_line_shows_at_the_top_of_the_area_and_wraps_at_its_end() {
        // VSCRSADD 44 + 47: display row 44 shows line 91, the last row wraps.
        assert_eq!(memory_row_for(44, 44, 436, 91), 91);
        assert_eq!(memory_row_for(479, 44, 436, 91), 44 + (47 + 435) % 436);
        // The identity when the start line is the top of the area.
        assert_eq!(memory_row_for(300, 44, 436, 44), 300);
    }
}
