//! Active board's Rust glue (e.g. board-level pin constants). Generated by
//! `build_support/boards.rs::emit_board_imports`. Empty when no board is
//! active — `src/main.rs` only pulls this module in on hardware builds.

include!(concat!(env!("OUT_DIR"), "/board_imports.rs"));
