// SPDX-License-Identifier: GPL-3.0-only
//! Active board's Rust glue. Generated by `build_support/boards::emit_board_imports`.
//! Empty when no board is active or the board has no Rust-side glue.
include!(concat!(env!("OUT_DIR"), "/board_imports.rs"));
