// SPDX-License-Identifier: GPL-3.0-only
// Generated by protoc-gen-picodroid from usage.proto. DO NOT EDIT.
package claudeusage.proto;

import java.io.IOException;
import picodroid.protobuf.CodedInputStream;
import picodroid.protobuf.CodedOutputStream;
import picodroid.protobuf.InvalidProtocolBufferException;
import picodroid.protobuf.MessageLite;

/** Proto message {@code claudeusage.ModelShare}. */
public final class ModelShare implements MessageLite {
  private String name_ = "";
  private int pct_ = 0;

  public ModelShare() {}

  public String getName() {
    return name_;
  }

  public ModelShare setName(String value) {
    if (value == null) {
      throw new NullPointerException("name");
    }
    name_ = value;
    return this;
  }

  public ModelShare clearName() {
    name_ = "";
    return this;
  }

  public int getPct() {
    return pct_;
  }

  public ModelShare setPct(int value) {
    pct_ = value;
    return this;
  }

  public ModelShare clearPct() {
    pct_ = 0;
    return this;
  }

  public static ModelShare parseFrom(byte[] data) throws InvalidProtocolBufferException {
    return parseFrom(data, 0, data.length);
  }

  public static ModelShare parseFrom(byte[] data, int off, int len)
      throws InvalidProtocolBufferException {
    return parseFrom(CodedInputStream.newInstance(data, off, len));
  }

  public static ModelShare parseFrom(CodedInputStream input) throws InvalidProtocolBufferException {
    ModelShare message = new ModelShare();
    try {
      message.mergeFrom(input);
    } catch (InvalidProtocolBufferException e) {
      throw e;
    } catch (IOException e) {
      throw new InvalidProtocolBufferException(e.getMessage());
    }
    return message;
  }

  /** Reads fields from {@code input} until its end or limit, on top of what is set. */
  public ModelShare mergeFrom(CodedInputStream input) throws IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        case 10:
          name_ = input.readString();
          break;
        case 16:
          pct_ = input.readInt32();
          break;
        default:
          input.skipField(tag);
      }
    }
  }

  @Override
  public void writeTo(CodedOutputStream output) throws IOException {
    if (!name_.isEmpty()) {
      output.writeString(1, name_);
    }
    if (pct_ != 0) {
      output.writeInt32(2, pct_);
    }
  }

  @Override
  public int getSerializedSize() {
    int size = 0;
    if (!name_.isEmpty()) {
      size += CodedOutputStream.computeStringSize(1, name_);
    }
    if (pct_ != 0) {
      size += CodedOutputStream.computeInt32Size(2, pct_);
    }
    return size;
  }

  @Override
  public byte[] toByteArray() {
    byte[] result = new byte[getSerializedSize()];
    try {
      CodedOutputStream output = CodedOutputStream.newInstance(result);
      writeTo(output);
      output.checkNoSpaceLeft();
    } catch (IOException e) {
      throw new RuntimeException(
          "Serializing to a byte array threw an IOException (should never happen).");
    }
    return result;
  }
}
