// SPDX-License-Identifier: GPL-3.0-only
// Generated by protoc-gen-picodroid from usage.proto. DO NOT EDIT.
package claudeusage.proto;

import java.io.IOException;
import picodroid.protobuf.CodedInputStream;
import picodroid.protobuf.CodedOutputStream;
import picodroid.protobuf.InvalidProtocolBufferException;
import picodroid.protobuf.MessageLite;

/** Proto message {@code claudeusage.Today}. */
public final class Today implements MessageLite {
  private int tokensK_ = 0;
  private int cents_ = 0;
  private int messages_ = 0;

  public Today() {}

  public int getTokensK() {
    return tokensK_;
  }

  public Today setTokensK(int value) {
    tokensK_ = value;
    return this;
  }

  public Today clearTokensK() {
    tokensK_ = 0;
    return this;
  }

  public int getCents() {
    return cents_;
  }

  public Today setCents(int value) {
    cents_ = value;
    return this;
  }

  public Today clearCents() {
    cents_ = 0;
    return this;
  }

  public int getMessages() {
    return messages_;
  }

  public Today setMessages(int value) {
    messages_ = value;
    return this;
  }

  public Today clearMessages() {
    messages_ = 0;
    return this;
  }

  public static Today parseFrom(byte[] data) throws InvalidProtocolBufferException {
    return parseFrom(data, 0, data.length);
  }

  public static Today parseFrom(byte[] data, int off, int len)
      throws InvalidProtocolBufferException {
    return parseFrom(CodedInputStream.newInstance(data, off, len));
  }

  public static Today parseFrom(CodedInputStream input) throws InvalidProtocolBufferException {
    Today message = new Today();
    try {
      message.mergeFrom(input);
    } catch (InvalidProtocolBufferException e) {
      throw e;
    } catch (IOException e) {
      throw new InvalidProtocolBufferException(e.getMessage());
    }
    return message;
  }

  /** Reads fields from {@code input} until its end or limit, on top of what is set. */
  public Today mergeFrom(CodedInputStream input) throws IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        case 8:
          tokensK_ = input.readInt32();
          break;
        case 16:
          cents_ = input.readInt32();
          break;
        case 24:
          messages_ = input.readInt32();
          break;
        default:
          input.skipField(tag);
      }
    }
  }

  @Override
  public void writeTo(CodedOutputStream output) throws IOException {
    if (tokensK_ != 0) {
      output.writeInt32(1, tokensK_);
    }
    if (cents_ != 0) {
      output.writeInt32(2, cents_);
    }
    if (messages_ != 0) {
      output.writeInt32(3, messages_);
    }
  }

  @Override
  public int getSerializedSize() {
    int size = 0;
    if (tokensK_ != 0) {
      size += CodedOutputStream.computeInt32Size(1, tokensK_);
    }
    if (cents_ != 0) {
      size += CodedOutputStream.computeInt32Size(2, cents_);
    }
    if (messages_ != 0) {
      size += CodedOutputStream.computeInt32Size(3, messages_);
    }
    return size;
  }

  @Override
  public byte[] toByteArray() {
    byte[] result = new byte[getSerializedSize()];
    try {
      CodedOutputStream output = CodedOutputStream.newInstance(result);
      writeTo(output);
      output.checkNoSpaceLeft();
    } catch (IOException e) {
      throw new RuntimeException(
          "Serializing to a byte array threw an IOException (should never happen).");
    }
    return result;
  }
}
