// SPDX-License-Identifier: GPL-3.0-only
// Generated by protoc-gen-picodroid from usage.proto. DO NOT EDIT.
package claudeusage.proto;

import java.io.IOException;
import java.util.Arrays;
import picodroid.protobuf.CodedInputStream;
import picodroid.protobuf.CodedOutputStream;
import picodroid.protobuf.InvalidProtocolBufferException;
import picodroid.protobuf.MessageLite;
import picodroid.protobuf.WireFormat;

/** Proto message {@code claudeusage.UsageReply}. */
public final class UsageReply implements MessageLite {
  private int version_ = 0;
  private long bridgeTime_ = 0L;
  private int tzMinutes_ = 0;
  private boolean ok_ = false;
  private String err_ = "";
  private int ageS_ = 0;
  private String plan_ = "";
  private Window session_;
  private Window weekly_;
  private ModelCap[] modelCaps_;
  private int modelCapsCount_;
  private int ratePerHour_ = 0;
  private int etaMinutes_ = 0;
  private Today today_;
  private int[] dayTokensK_;
  private int dayTokensKCount_;
  private String dayLetters_ = "";
  private ModelShare[] mix_;
  private int mixCount_;

  public UsageReply() {}

  public int getVersion() {
    return version_;
  }

  public UsageReply setVersion(int value) {
    version_ = value;
    return this;
  }

  public UsageReply clearVersion() {
    version_ = 0;
    return this;
  }

  public long getBridgeTime() {
    return bridgeTime_;
  }

  public UsageReply setBridgeTime(long value) {
    bridgeTime_ = value;
    return this;
  }

  public UsageReply clearBridgeTime() {
    bridgeTime_ = 0L;
    return this;
  }

  public int getTzMinutes() {
    return tzMinutes_;
  }

  public UsageReply setTzMinutes(int value) {
    tzMinutes_ = value;
    return this;
  }

  public UsageReply clearTzMinutes() {
    tzMinutes_ = 0;
    return this;
  }

  public boolean getOk() {
    return ok_;
  }

  public UsageReply setOk(boolean value) {
    ok_ = value;
    return this;
  }

  public UsageReply clearOk() {
    ok_ = false;
    return this;
  }

  public String getErr() {
    return err_;
  }

  public UsageReply setErr(String value) {
    if (value == null) {
      throw new NullPointerException("err");
    }
    err_ = value;
    return this;
  }

  public UsageReply clearErr() {
    err_ = "";
    return this;
  }

  public int getAgeS() {
    return ageS_;
  }

  public UsageReply setAgeS(int value) {
    ageS_ = value;
    return this;
  }

  public UsageReply clearAgeS() {
    ageS_ = 0;
    return this;
  }

  public String getPlan() {
    return plan_;
  }

  public UsageReply setPlan(String value) {
    if (value == null) {
      throw new NullPointerException("plan");
    }
    plan_ = value;
    return this;
  }

  public UsageReply clearPlan() {
    plan_ = "";
    return this;
  }

  public boolean hasSession() {
    return session_ != null;
  }

  public Window getSession() {
    return session_;
  }

  public UsageReply setSession(Window value) {
    session_ = value;
    return this;
  }

  public UsageReply clearSession() {
    session_ = null;
    return this;
  }

  public boolean hasWeekly() {
    return weekly_ != null;
  }

  public Window getWeekly() {
    return weekly_;
  }

  public UsageReply setWeekly(Window value) {
    weekly_ = value;
    return this;
  }

  public UsageReply clearWeekly() {
    weekly_ = null;
    return this;
  }

  public int getModelCapsCount() {
    return modelCapsCount_;
  }

  public ModelCap getModelCaps(int index) {
    if (index < 0 || index >= modelCapsCount_) {
      throw new IndexOutOfBoundsException(String.valueOf(index));
    }
    return modelCaps_[index];
  }

  public UsageReply addModelCaps(ModelCap value) {
    if (value == null) {
      throw new NullPointerException("model_caps");
    }
    if (modelCaps_ == null || modelCapsCount_ == modelCaps_.length) {
      int capacity = modelCapsCount_ == 0 ? 4 : modelCapsCount_ * 2;
      ModelCap[] grown = new ModelCap[capacity];
      if (modelCaps_ != null) {
        System.arraycopy(modelCaps_, 0, grown, 0, modelCapsCount_);
      }
      modelCaps_ = grown;
    }
    modelCaps_[modelCapsCount_++] = value;
    return this;
  }

  public UsageReply clearModelCaps() {
    modelCaps_ = null;
    modelCapsCount_ = 0;
    return this;
  }

  public int getRatePerHour() {
    return ratePerHour_;
  }

  public UsageReply setRatePerHour(int value) {
    ratePerHour_ = value;
    return this;
  }

  public UsageReply clearRatePerHour() {
    ratePerHour_ = 0;
    return this;
  }

  public int getEtaMinutes() {
    return etaMinutes_;
  }

  public UsageReply setEtaMinutes(int value) {
    etaMinutes_ = value;
    return this;
  }

  public UsageReply clearEtaMinutes() {
    etaMinutes_ = 0;
    return this;
  }

  public boolean hasToday() {
    return today_ != null;
  }

  public Today getToday() {
    return today_;
  }

  public UsageReply setToday(Today value) {
    today_ = value;
    return this;
  }

  public UsageReply clearToday() {
    today_ = null;
    return this;
  }

  public int getDayTokensKCount() {
    return dayTokensKCount_;
  }

  public int getDayTokensK(int index) {
    if (index < 0 || index >= dayTokensKCount_) {
      throw new IndexOutOfBoundsException(String.valueOf(index));
    }
    return dayTokensK_[index];
  }

  public UsageReply addDayTokensK(int value) {
    if (dayTokensK_ == null || dayTokensKCount_ == dayTokensK_.length) {
      int capacity = dayTokensKCount_ == 0 ? 4 : dayTokensKCount_ * 2;
      dayTokensK_ = dayTokensK_ == null ? new int[capacity] : Arrays.copyOf(dayTokensK_, capacity);
    }
    dayTokensK_[dayTokensKCount_++] = value;
    return this;
  }

  public UsageReply clearDayTokensK() {
    dayTokensK_ = null;
    dayTokensKCount_ = 0;
    return this;
  }

  public String getDayLetters() {
    return dayLetters_;
  }

  public UsageReply setDayLetters(String value) {
    if (value == null) {
      throw new NullPointerException("day_letters");
    }
    dayLetters_ = value;
    return this;
  }

  public UsageReply clearDayLetters() {
    dayLetters_ = "";
    return this;
  }

  public int getMixCount() {
    return mixCount_;
  }

  public ModelShare getMix(int index) {
    if (index < 0 || index >= mixCount_) {
      throw new IndexOutOfBoundsException(String.valueOf(index));
    }
    return mix_[index];
  }

  public UsageReply addMix(ModelShare value) {
    if (value == null) {
      throw new NullPointerException("mix");
    }
    if (mix_ == null || mixCount_ == mix_.length) {
      int capacity = mixCount_ == 0 ? 4 : mixCount_ * 2;
      ModelShare[] grown = new ModelShare[capacity];
      if (mix_ != null) {
        System.arraycopy(mix_, 0, grown, 0, mixCount_);
      }
      mix_ = grown;
    }
    mix_[mixCount_++] = value;
    return this;
  }

  public UsageReply clearMix() {
    mix_ = null;
    mixCount_ = 0;
    return this;
  }

  public static UsageReply parseFrom(byte[] data) throws InvalidProtocolBufferException {
    return parseFrom(data, 0, data.length);
  }

  public static UsageReply parseFrom(byte[] data, int off, int len)
      throws InvalidProtocolBufferException {
    return parseFrom(CodedInputStream.newInstance(data, off, len));
  }

  public static UsageReply parseFrom(CodedInputStream input) throws InvalidProtocolBufferException {
    UsageReply message = new UsageReply();
    try {
      message.mergeFrom(input);
    } catch (InvalidProtocolBufferException e) {
      throw e;
    } catch (IOException e) {
      throw new InvalidProtocolBufferException(e.getMessage());
    }
    return message;
  }

  /** Reads fields from {@code input} until its end or limit, on top of what is set. */
  public UsageReply mergeFrom(CodedInputStream input) throws IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        case 8:
          version_ = input.readUInt32();
          break;
        case 16:
          bridgeTime_ = input.readInt64();
          break;
        case 24:
          tzMinutes_ = input.readSInt32();
          break;
        case 32:
          ok_ = input.readBool();
          break;
        case 42:
          err_ = input.readString();
          break;
        case 48:
          ageS_ = input.readInt32();
          break;
        case 58:
          plan_ = input.readString();
          break;
        case 66:
          {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            Window value = new Window();
            value.mergeFrom(input);
            input.popLimit(limit);
            session_ = value;
          }
          break;
        case 74:
          {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            Window value = new Window();
            value.mergeFrom(input);
            input.popLimit(limit);
            weekly_ = value;
          }
          break;
        case 82:
          {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            ModelCap value = new ModelCap();
            value.mergeFrom(input);
            input.popLimit(limit);
            addModelCaps(value);
          }
          break;
        case 88:
          ratePerHour_ = input.readInt32();
          break;
        case 96:
          etaMinutes_ = input.readInt32();
          break;
        case 106:
          {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            Today value = new Today();
            value.mergeFrom(input);
            input.popLimit(limit);
            today_ = value;
          }
          break;
        case 112:
          addDayTokensK(input.readInt32());
          break;
        case 114:
          {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            while (input.getBytesUntilLimit() > 0) {
              addDayTokensK(input.readInt32());
            }
            input.popLimit(limit);
          }
          break;
        case 122:
          dayLetters_ = input.readString();
          break;
        case 130:
          {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            ModelShare value = new ModelShare();
            value.mergeFrom(input);
            input.popLimit(limit);
            addMix(value);
          }
          break;
        default:
          input.skipField(tag);
      }
    }
  }

  @Override
  public void writeTo(CodedOutputStream output) throws IOException {
    if (version_ != 0) {
      output.writeUInt32(1, version_);
    }
    if (bridgeTime_ != 0L) {
      output.writeInt64(2, bridgeTime_);
    }
    if (tzMinutes_ != 0) {
      output.writeSInt32(3, tzMinutes_);
    }
    if (ok_) {
      output.writeBool(4, ok_);
    }
    if (!err_.isEmpty()) {
      output.writeString(5, err_);
    }
    if (ageS_ != 0) {
      output.writeInt32(6, ageS_);
    }
    if (!plan_.isEmpty()) {
      output.writeString(7, plan_);
    }
    if (session_ != null) {
      output.writeMessage(8, session_);
    }
    if (weekly_ != null) {
      output.writeMessage(9, weekly_);
    }
    for (int i = 0; i < modelCapsCount_; i++) {
      output.writeMessage(10, modelCaps_[i]);
    }
    if (ratePerHour_ != 0) {
      output.writeInt32(11, ratePerHour_);
    }
    if (etaMinutes_ != 0) {
      output.writeInt32(12, etaMinutes_);
    }
    if (today_ != null) {
      output.writeMessage(13, today_);
    }
    if (dayTokensKCount_ > 0) {
      output.writeTag(14, WireFormat.WIRETYPE_LENGTH_DELIMITED);
      output.writeUInt32NoTag(packedDayTokensKSize());
      for (int i = 0; i < dayTokensKCount_; i++) {
        output.writeInt32NoTag(dayTokensK_[i]);
      }
    }
    if (!dayLetters_.isEmpty()) {
      output.writeString(15, dayLetters_);
    }
    for (int i = 0; i < mixCount_; i++) {
      output.writeMessage(16, mix_[i]);
    }
  }

  @Override
  public int getSerializedSize() {
    int size = 0;
    if (version_ != 0) {
      size += CodedOutputStream.computeUInt32Size(1, version_);
    }
    if (bridgeTime_ != 0L) {
      size += CodedOutputStream.computeInt64Size(2, bridgeTime_);
    }
    if (tzMinutes_ != 0) {
      size += CodedOutputStream.computeSInt32Size(3, tzMinutes_);
    }
    if (ok_) {
      size += CodedOutputStream.computeBoolSize(4, ok_);
    }
    if (!err_.isEmpty()) {
      size += CodedOutputStream.computeStringSize(5, err_);
    }
    if (ageS_ != 0) {
      size += CodedOutputStream.computeInt32Size(6, ageS_);
    }
    if (!plan_.isEmpty()) {
      size += CodedOutputStream.computeStringSize(7, plan_);
    }
    if (session_ != null) {
      size += CodedOutputStream.computeMessageSize(8, session_);
    }
    if (weekly_ != null) {
      size += CodedOutputStream.computeMessageSize(9, weekly_);
    }
    for (int i = 0; i < modelCapsCount_; i++) {
      size += CodedOutputStream.computeMessageSize(10, modelCaps_[i]);
    }
    if (ratePerHour_ != 0) {
      size += CodedOutputStream.computeInt32Size(11, ratePerHour_);
    }
    if (etaMinutes_ != 0) {
      size += CodedOutputStream.computeInt32Size(12, etaMinutes_);
    }
    if (today_ != null) {
      size += CodedOutputStream.computeMessageSize(13, today_);
    }
    if (dayTokensKCount_ > 0) {
      int packed = packedDayTokensKSize();
      size +=
          CodedOutputStream.computeTagSize(14)
              + CodedOutputStream.computeUInt32SizeNoTag(packed)
              + packed;
    }
    if (!dayLetters_.isEmpty()) {
      size += CodedOutputStream.computeStringSize(15, dayLetters_);
    }
    for (int i = 0; i < mixCount_; i++) {
      size += CodedOutputStream.computeMessageSize(16, mix_[i]);
    }
    return size;
  }

  private int packedDayTokensKSize() {
    int size = 0;
    for (int i = 0; i < dayTokensKCount_; i++) {
      size += CodedOutputStream.computeInt32SizeNoTag(dayTokensK_[i]);
    }
    return size;
  }

  @Override
  public byte[] toByteArray() {
    byte[] result = new byte[getSerializedSize()];
    try {
      CodedOutputStream output = CodedOutputStream.newInstance(result);
      writeTo(output);
      output.checkNoSpaceLeft();
    } catch (IOException e) {
      throw new RuntimeException(
          "Serializing to a byte array threw an IOException (should never happen).");
    }
    return result;
  }
}
