// SPDX-License-Identifier: GPL-3.0-only
// Generated by protoc-gen-picodroid from usage.proto. DO NOT EDIT.
package claudeusage.proto;

import java.io.IOException;
import picodroid.protobuf.CodedInputStream;
import picodroid.protobuf.CodedOutputStream;
import picodroid.protobuf.InvalidProtocolBufferException;
import picodroid.protobuf.MessageLite;

/** Proto message {@code claudeusage.Window}. */
public final class Window implements MessageLite {
  private int pct_ = 0;
  private long reset_ = 0L;

  public Window() {}

  public int getPct() {
    return pct_;
  }

  public Window setPct(int value) {
    pct_ = value;
    return this;
  }

  public Window clearPct() {
    pct_ = 0;
    return this;
  }

  public long getReset() {
    return reset_;
  }

  public Window setReset(long value) {
    reset_ = value;
    return this;
  }

  public Window clearReset() {
    reset_ = 0L;
    return this;
  }

  public static Window parseFrom(byte[] data) throws InvalidProtocolBufferException {
    return parseFrom(data, 0, data.length);
  }

  public static Window parseFrom(byte[] data, int off, int len)
      throws InvalidProtocolBufferException {
    return parseFrom(CodedInputStream.newInstance(data, off, len));
  }

  public static Window parseFrom(CodedInputStream input) throws InvalidProtocolBufferException {
    Window message = new Window();
    try {
      message.mergeFrom(input);
    } catch (InvalidProtocolBufferException e) {
      throw e;
    } catch (IOException e) {
      throw new InvalidProtocolBufferException(e.getMessage());
    }
    return message;
  }

  /** Reads fields from {@code input} until its end or limit, on top of what is set. */
  public Window mergeFrom(CodedInputStream input) throws IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        case 8:
          pct_ = input.readInt32();
          break;
        case 16:
          reset_ = input.readInt64();
          break;
        default:
          input.skipField(tag);
      }
    }
  }

  @Override
  public void writeTo(CodedOutputStream output) throws IOException {
    if (pct_ != 0) {
      output.writeInt32(1, pct_);
    }
    if (reset_ != 0L) {
      output.writeInt64(2, reset_);
    }
  }

  @Override
  public int getSerializedSize() {
    int size = 0;
    if (pct_ != 0) {
      size += CodedOutputStream.computeInt32Size(1, pct_);
    }
    if (reset_ != 0L) {
      size += CodedOutputStream.computeInt64Size(2, reset_);
    }
    return size;
  }

  @Override
  public byte[] toByteArray() {
    byte[] result = new byte[getSerializedSize()];
    try {
      CodedOutputStream output = CodedOutputStream.newInstance(result);
      writeTo(output);
      output.checkNoSpaceLeft();
    } catch (IOException e) {
      throw new RuntimeException(
          "Serializing to a byte array threw an IOException (should never happen).");
    }
    return result;
  }
}
