// SPDX-License-Identifier: GPL-3.0-only
use crate::{
    array_heap::ArrayHeap,
    class_file::ClassFile,
    class_objects::ClassObjectCache,
    frame::Frame,
    gc::GcState,
    heap::StringTable,
    native::NativeMethodHandler,
    object_heap::ObjectHeap,
    static_fields::StaticFieldStore,
    types::{JvmError, StackTraceEntry, Value},
};
use alloc::vec::Vec;

mod helpers;
mod ops_arrays;
mod ops_constants;
mod ops_control;
mod ops_convert;
mod ops_exceptions;
mod ops_fields;
mod ops_invoke;
mod ops_locals;
mod ops_math;
mod ops_monitor;
mod ops_stack;
mod ops_wide;

#[cfg(test)]
mod tests;

pub(crate) use helpers::array_class_name;
/// The classfile-less hierarchy tables, exported so an embedder's tests can
/// cross-check the classes its Kotlin/Java surface names against what the
/// JVM serves (picodroid-core's API contract generator, `api_contract.rs`).
pub use helpers::{BUILTIN_INTERFACES, BUILTIN_SUPER};

use crate::tunables::GC_THRESHOLD;

/// Java frame-stack depth beyond which a push throws `StackOverflowError`.
///
/// Not a `tunables.rs` constant: that module is generated by `build.rs` from
/// each board's `board.toml` `[jvm]` section, and this needs no per-board
/// tuning. Before this cap existed the frame stack was unbounded, so runaway
/// recursion exhausted the *heap* first and surfaced as a bare allocation
/// failure — poisoning every other allocation on the way down — rather than
/// as the catchable `StackOverflowError` the JVMS specifies.
const MAX_FRAME_DEPTH: usize = 256;

/// Rust-stack nesting limit for synchronous native→Java upcalls.
///
/// Each level costs a full `run` → `op_invoke` → `dispatch_native` → native
/// arm → `invoke_java` chain on the JVM task stack, which is
/// `JVM_THREAD_STACK_WORDS` (16 KB) on `Thread.start` children and half that
/// again on rp2040. There is no guard page under FreeRTOS, so overflowing it
/// is silent corruption rather than a fault — keep this conservative.
///
/// Lives on [`Executor`] rather than `GcState` deliberately: `GcState` is
/// shared between the main JVM task and `Thread.start` children, so a counter
/// there would sum two independent Rust stacks and trip spuriously.
const MAX_UPCALL_DEPTH: u8 = 4;

/// Re-enter the interpreter from a native arm — the implementation behind
/// [`crate::native::NativeMethodHandler::invoke_java`].
///
/// `handler` is the arm's own `&mut self`, lent back so the nested executor
/// reborrows the *same* handler rather than acquiring a second one. Every
/// other piece of executor state comes from `ctx` and its `upcall` env, which
/// is why that env deliberately does not carry a handler of its own.
pub(crate) fn upcall_from_native<H: NativeMethodHandler>(
    handler: &mut H,
    ctx: &mut crate::native::NativeContext<'_>,
    recv: Value,
    method_name: &str,
    descriptor: &str,
    args: &[Value],
) -> Result<Option<Value>, JvmError> {
    // Destructured rather than accessed through `ctx.field`: the nested
    // executor needs several of these at once, and only separate bindings
    // give the borrow checker disjoint field borrows.
    let crate::native::NativeContext {
        classes,
        strings,
        objects,
        arrays,
        upcall,
        ..
    } = ctx;
    let Some(env) = upcall.as_deref_mut() else {
        // Driven from outside the interpreter — there is no frame stack to
        // push onto and no bytecode to return to.
        return Err(JvmError::NoSuchMethod);
    };
    let crate::native::UpcallEnv {
        statics,
        gc_state,
        class_objects,
        frames,
        upcall_depth,
    } = env;

    let mut ex = Executor {
        classes,
        strings,
        objects,
        arrays,
        statics,
        gc_state,
        class_objects,
        handler,
        // Fresh caches: they key on pointer identity and are cheap to rebuild
        // (`Vec::new` does not allocate). Threading the outer executor's
        // caches through would mean handing out a fourth mutable borrow of it.
        field_cache: Vec::new(),
        method_cache: Vec::new(),
        static_field_cache: Vec::new(),
        pending_frame: None,
        pending_clinit_frames: Vec::new(),
        insn_count: 0,
        upcall_depth: *upcall_depth,
    };
    ex.invoke_java(frames, recv, method_name, descriptor, args)
}

pub(crate) struct Executor<'a, H: NativeMethodHandler> {
    pub classes: &'a [ClassFile],
    pub strings: &'a mut StringTable,
    pub objects: &'a mut ObjectHeap,
    pub arrays: &'a mut ArrayHeap,
    pub statics: &'a mut StaticFieldStore,
    pub gc_state: &'a mut GcState,
    pub class_objects: &'a mut ClassObjectCache,
    pub handler: &'a mut H,
    /// Cache: (class_name ptr, field_name ptr) → field slot index.
    pub field_cache: Vec<(*const u8, *const u8, *const u8, usize)>,
    /// Cache: (class_name ptr, method_name ptr, desc ptr) → (class_idx, method_idx).
    pub method_cache: Vec<helpers::MethodCacheEntry>,
    /// Cache: (class_name ptr, field_name ptr) → index in StaticFieldStore entries.
    pub static_field_cache: Vec<(*const u8, *const u8, usize)>,
    /// Set by `op_invoke` when a Java method should be called; the main loop
    /// pushes this frame onto the frame stack on the next iteration.
    pub pending_frame: Option<Frame>,
    /// `<clinit>` frames queued by `ensure_class_initialized`.  Popped onto
    /// the frame stack so the interpreter runs them before resuming the
    /// triggering instruction.
    pub pending_clinit_frames: Vec<Frame>,
    /// Instruction counter for batched interrupt checking (checks every 256 insns).
    pub insn_count: u8,
    /// How many synchronous native→Java upcalls are live on *this* Rust stack.
    /// Seeded from the enclosing executor by `invoke_java`, so it counts Rust
    /// recursion depth rather than anything heap-wide. See [`MAX_UPCALL_DEPTH`].
    pub upcall_depth: u8,
}

impl<'a, H: NativeMethodHandler> Executor<'a, H> {
    /// Allocation counter for GC triggering.  Stored on the shared `GcState`
    /// so it persists across nested `execute()` calls — without this, every
    /// native-driven callback (e.g. `onSensorChanged`) starts a fresh
    /// `Executor` with `alloc_count = 0` and the 256-alloc GC threshold is
    /// never reached when allocations are spread across many short calls.
    #[inline]
    pub fn alloc_count(&self) -> u16 {
        self.gc_state.alloc_count
    }

    #[inline]
    pub fn bump_alloc_count(&mut self, n: u16) {
        #[cfg(feature = "parity-metrics")]
        crate::parity::count_allocs(n as usize);
        #[cfg(feature = "mem-diag")]
        {
            self.gc_state.alloc_total = self.gc_state.alloc_total.wrapping_add(n as u32);
        }
        self.gc_state.alloc_count = self.gc_state.alloc_count.saturating_add(n);
    }

    /// Fold the heaps' own allocation counters into GC pacing. The heaps
    /// count every allocation at the source — including ones minted by
    /// native handlers and builtins (getBytes, toString interning, sensor
    /// events), which never pass through the bytecode alloc opcodes and
    /// were historically invisible to the GC threshold. First bitten by the
    /// picoenvmon dashboard: its page bodies were built almost entirely by
    /// builtins, so KB-scale garbage accumulated with the counter near
    /// zero until a table-growth step OOM'd. Called after every invoke
    /// opcode and at the 256-instruction checkpoint.
    #[inline]
    pub fn fold_native_alloc_events(&mut self) {
        let n = self
            .objects
            .take_alloc_events()
            .saturating_add(self.arrays.take_alloc_events())
            .saturating_add(self.strings.take_alloc_events());
        if n > 0 {
            self.bump_alloc_count(n);
        }
    }

    #[inline]
    pub fn need_gc(&self) -> bool {
        self.gc_state.need_gc
    }

    #[inline]
    pub fn set_need_gc(&mut self, v: bool) {
        self.gc_state.need_gc = v;
    }
}

impl<'a, H: NativeMethodHandler> Executor<'a, H> {
    /// If `class_name` (or any superclass in the loaded class set) has not been
    /// initialized, queue their `<clinit>` frames and return `true`.  The caller
    /// must rewind `frame.pc` to `frame.inst_pc` and return `Ok(())` so the main
    /// loop executes the clinit frames first.
    ///
    /// Returns `false` when the class is already initialized (caller proceeds
    /// normally).
    pub(crate) fn ensure_class_initialized(
        &mut self,
        class_name: &'static [u8],
    ) -> Result<bool, JvmError> {
        if self.statics.is_initialized(class_name) {
            return Ok(false);
        }

        // Build superclass chain, root-first: [Object, ..., Parent, class_name]
        let chain = helpers::superclass_chain(self.classes, class_name);

        let mut clinit_frames: Vec<Frame> = Vec::new();
        for &cn in &chain {
            if self.statics.is_initialized(cn) {
                continue;
            }
            // Mark immediately to prevent re-entrant clinit.
            self.statics.mark_initialized(cn);
            // JVMS §5.5 step 2: preparation — every static field gets its
            // typed default before `<clinit>` runs.  Putstatic in `<clinit>`
            // then overwrites these with any explicit initializers.
            if let Some(cf) = self.classes.iter().find(|c| c.class_name() == Some(cn)) {
                for fi in cf.static_fields() {
                    if let (Some(name), Some(desc)) =
                        (cf.cp_utf8(fi.name_index), cf.field_descriptor(fi))
                    {
                        self.statics
                            .set(cn, name, crate::types::default_for_descriptor(desc))
                            .ok_or(JvmError::StackOverflow)?;
                    }
                }
            }
            if let Some((ci, mi)) = helpers::find_clinit(self.classes, cn) {
                if self.classes[ci].methods()[mi].code_offset != 0 {
                    let cm = &self.classes[ci].methods()[mi];
                    clinit_frames.push(Frame::new(ci, mi, &[], cm.max_locals, cm.max_stack)?);
                }
            }
        }

        if clinit_frames.is_empty() {
            return Ok(false);
        }

        // Reverse so root clinit is on top (LIFO — top executes first).
        clinit_frames.reverse();
        self.pending_clinit_frames = clinit_frames;
        Ok(true)
    }
}

/// Search `method`'s exception table for a handler covering `inst_pc` that
/// catches the class of `obj_idx`.  Returns the handler bytecode offset on
/// a match, or `None` if no handler applies.
fn find_exception_handler(
    cf: &ClassFile,
    method: &crate::class_file::MethodInfo,
    inst_pc: usize,
    obj_idx: u16,
    objects: &ObjectHeap,
    classes: &[ClassFile],
) -> Option<usize> {
    let exception_class = objects.class_name(obj_idx)?;
    for entry in &method.exception_table {
        let start = entry.start_pc as usize;
        let end = entry.end_pc as usize;
        if inst_pc >= start && inst_pc < end {
            if entry.catch_type_index == 0 {
                // catch-all (finally)
                return Some(entry.handler_pc as usize);
            }
            if let Some(class_bytes) = cf.cp_class_name(entry.catch_type_index) {
                if let Ok(catch_class) = core::str::from_utf8(class_bytes) {
                    if helpers::is_instance_of(classes, exception_class, catch_class) {
                        return Some(entry.handler_pc as usize);
                    }
                }
            }
        }
    }
    None
}

/// Handle a Java exception by walking the frame stack for a matching handler.
/// Returns `Ok(())` if a handler was found and the frame stack is set up to
/// continue execution, or `Err` if the exception should propagate to the caller.
///
/// When no handler is found the error includes a stack trace captured from the
/// frame stack before unwinding.
///
/// `floor` bounds the search and every truncation: frames below it belong to a
/// *caller* of this run — under a native→Java upcall that caller is a native
/// arm mid-execution, so unwinding into its frames would strip state the arm
/// still owns and resume Java without ever giving the arm control. At the
/// top-level `execute()` call `floor` is 0 and this is the historical
/// whole-stack behaviour.
fn handle_exception<H: NativeMethodHandler>(
    ex: &mut Executor<'_, H>,
    frames: &mut Vec<Frame>,
    obj_idx: u16,
    floor: usize,
) -> Result<(), JvmError> {
    let mut obj_idx = obj_idx;
    loop {
        // First pass: search for a handler without popping frames.
        let handler_frame_idx = (floor..frames.len()).rev().find(|&i| {
            let f = &frames[i];
            let cf = &ex.classes[f.class_idx];
            let method = &cf.methods()[f.method_idx];
            find_exception_handler(cf, method, f.inst_pc, obj_idx, ex.objects, ex.classes).is_some()
        });

        // JVMS §5.5: a non-Error exception escaping a `<clinit>` frame is
        // wrapped in ExceptionInInitializerError. Look for the outermost
        // clinit frame the unwind to the chosen handler (or to uncaught)
        // would cross; wrap there, drop the clinit frame, and continue the
        // handler search below it with the wrapper. Errors — including a
        // wrapper minted by a nested clinit — cross unwrapped, which also
        // bounds this loop: each wrap removes at least one frame and the
        // wrapper itself is an Error.
        let unwind_floor = handler_frame_idx.map_or(floor, |i| i + 1);
        let crossed_clinit = (unwind_floor..frames.len()).find(|&i| {
            let f = &frames[i];
            let cf = &ex.classes[f.class_idx];
            let method = &cf.methods()[f.method_idx];
            cf.cp_utf8(method.name_index) == Some(b"<clinit>")
        });
        if let Some(clinit_idx) = crossed_clinit {
            let exc_class = ex.objects.class_name(obj_idx).unwrap_or("");
            let is_error = helpers::is_instance_of(ex.classes, exc_class, "java/lang/Error");
            if !is_error {
                if let Some(wrapper) = ex.objects.alloc("java/lang/ExceptionInInitializerError") {
                    ex.objects.register_exception_cause(wrapper, obj_idx);
                    // Synthesize "<original class>: <msg>" so uncaught traces
                    // stay readable without calling getCause().
                    let mut msg: Vec<u8> = Vec::with_capacity(exc_class.len() + 32);
                    msg.extend_from_slice(exc_class.as_bytes());
                    if let Some(mi) = ex.objects.get_exception_message(obj_idx) {
                        if let Some(s) = ex.strings.resolve(mi) {
                            msg.extend_from_slice(b": ");
                            msg.extend_from_slice(s.as_bytes());
                        }
                    }
                    if let Some(midx) = ex.strings.intern_dyn_owned(msg) {
                        ex.objects.register_exception_message(wrapper, midx);
                    }
                    // `crossed_clinit` searched from `unwind_floor`, which is
                    // itself `>= floor`, so this can never cut below the floor.
                    debug_assert!(clinit_idx >= floor);
                    truncate_frames(ex, frames, clinit_idx);
                    obj_idx = wrapper;
                    continue;
                }
                // Allocation failed mid-unwind (OOM): propagate the original
                // unwrapped rather than lose the exception entirely.
            }
        }

        return deliver_exception(ex, frames, obj_idx, handler_frame_idx, floor);
    }
}

/// Deliver `obj_idx` to the handler at `handler_frame_idx`, or build the
/// uncaught-exception error when there is none.
fn deliver_exception<H: NativeMethodHandler>(
    ex: &mut Executor<'_, H>,
    frames: &mut Vec<Frame>,
    obj_idx: u16,
    handler_frame_idx: Option<usize>,
    floor: usize,
) -> Result<(), JvmError> {
    if let Some(idx) = handler_frame_idx {
        // Found a handler — truncate to that frame and set up for execution.
        truncate_frames(ex, frames, idx + 1);
        let f = frames.last_mut().unwrap();
        let cf = &ex.classes[f.class_idx];
        let method = &cf.methods()[f.method_idx];
        let handler_pc =
            find_exception_handler(cf, method, f.inst_pc, obj_idx, ex.objects, ex.classes).unwrap();
        f.stack.clear();
        f.push(Value::ObjectRef(obj_idx))?;
        f.pc = handler_pc;
        return Ok(());
    }

    // No handler *in this run*. Above a floor the frames below belong to a
    // caller that has not had its turn yet — a native arm mid-upcall, whose
    // own caller may well have the `catch`. Hand the exception back as a
    // Java exception so it resumes the search there; only the outermost run
    // (floor 0) can conclude that nothing caught it.
    if floor > 0 {
        truncate_frames(ex, frames, floor);
        return Err(JvmError::Exception(obj_idx));
    }

    // No handler anywhere — build the stack trace from the intact frame stack.
    let trace: Vec<StackTraceEntry> = frames[floor..]
        .iter()
        .rev()
        .filter_map(|f| {
            let cf = &ex.classes[f.class_idx];
            let cn = core::str::from_utf8(cf.class_name()?).ok()?;
            let method = &cf.methods()[f.method_idx];
            let mn = core::str::from_utf8(cf.cp_utf8(method.name_index)?).ok()?;
            Some(StackTraceEntry {
                class_name: cn,
                method_name: mn,
                pc: f.inst_pc,
                #[cfg(debug_assertions)]
                line: cf.pc_to_line(method, f.inst_pc),
            })
        })
        .collect();
    let exception_class = ex.objects.class_name(obj_idx).unwrap_or("<unknown>");
    let message = ex
        .objects
        .get_exception_message(obj_idx)
        .and_then(|msg_idx| ex.strings.resolve_static(msg_idx));
    truncate_frames(ex, frames, floor);
    Err(JvmError::UncaughtException {
        exception_class,
        message,
        trace,
    })
}

const ACC_STATIC: u16 = 0x0008;
const ACC_SYNCHRONIZED: u16 = 0x0020;

/// `ACC_SYNCHRONIZED` (JVMS §2.11.10): before a synchronized method's frame
/// goes on the stack, take the monitor it holds for its whole activation —
/// the receiver for an instance method, the Class object for a static one —
/// and record it on the frame so every exit path releases it. javac emits
/// no `monitorenter`/`monitorexit` for the method form; only the block form
/// is bytecode, so without this a `synchronized void inc()` ran unlocked.
#[inline(never)]
fn enter_synchronized<H: NativeMethodHandler>(
    ex: &mut Executor<'_, H>,
    frame: &mut Frame,
) -> Result<(), JvmError> {
    let cf = &ex.classes[frame.class_idx];
    let m = &cf.methods()[frame.method_idx];
    if m.access_flags & ACC_SYNCHRONIZED == 0 {
        return Ok(());
    }
    let key = if m.access_flags & ACC_STATIC != 0 {
        let name = cf.class_name().ok_or(JvmError::InvalidBytecode)?;
        match helpers::class_object_for_name(
            ex.classes,
            ex.strings,
            ex.objects,
            ex.class_objects,
            name,
        )? {
            Value::ObjectRef(class_obj) => crate::types::MonitorKey::Object(class_obj),
            _ => return Err(JvmError::InvalidBytecode),
        }
    } else {
        let this = frame
            .locals
            .first()
            .copied()
            .ok_or(JvmError::InvalidBytecode)?;
        ops_monitor::value_to_monitor_key(this)?
    };
    ex.handler.monitor_enter(key)?;
    frame.monitor = Some(key);
    Ok(())
}

/// Pop the top frame, releasing the monitor of a synchronized method. Every
/// pop in this module goes through here or [`truncate_frames`].
fn pop_frame<H: NativeMethodHandler>(
    ex: &mut Executor<'_, H>,
    frames: &mut Vec<Frame>,
) -> Result<(), JvmError> {
    if let Some(frame) = frames.pop() {
        if let Some(key) = frame.monitor {
            ex.handler.monitor_exit(key)?;
        }
    }
    Ok(())
}

/// Unwind to `len` frames, releasing monitors top-down. Used while an
/// exception is in flight, where a monitor the handler will not release
/// (an `IllegalMonitorStateException`-in-waiting) must not displace the
/// exception being delivered — so release failures are ignored here.
#[inline(never)]
fn truncate_frames<H: NativeMethodHandler>(
    ex: &mut Executor<'_, H>,
    frames: &mut Vec<Frame>,
    len: usize,
) {
    while frames.len() > len {
        let _ = pop_frame(ex, frames);
    }
}

/// Let the handler drop the monitors of entities a collection just freed
/// (see [`NativeMethodHandler::monitors_prune`]). Runs before any allocation
/// can recycle a slot, so "not live" means "freed by this collection".
pub(crate) fn prune_monitors<H: NativeMethodHandler>(
    handler: &mut H,
    objects: &ObjectHeap,
    arrays: &ArrayHeap,
    strings: &StringTable,
) {
    use crate::types::MonitorKey;
    handler.monitors_prune(&|key| match key {
        MonitorKey::Object(i) => objects.is_live(i),
        MonitorKey::Array(i) => arrays.is_live(i),
        // Static strings live in Flash and are never freed.
        MonitorKey::String(i) => (i as usize) < strings.dyn_start() || strings.is_dyn_live(i),
    });
}

#[allow(clippy::too_many_arguments)]
pub fn execute<H: NativeMethodHandler>(
    classes: &[ClassFile],
    strings: &mut StringTable,
    objects: &mut ObjectHeap,
    arrays: &mut ArrayHeap,
    statics: &mut StaticFieldStore,
    gc_state: &mut GcState,
    class_objects: &mut ClassObjectCache,
    handler: &mut H,
    class_idx: usize,
    method_idx: usize,
    args: &[Value],
) -> Result<Option<Value>, JvmError> {
    let m = &classes[class_idx].methods()[method_idx];
    let initial_frame = Frame::new(class_idx, method_idx, args, m.max_locals, m.max_stack)?;
    let mut frames: Vec<Frame> = Vec::new();
    frames.push(initial_frame);

    // Root this stack for GCs triggered by other executors on the same heap
    // while this task is parked at a blocking native (see GcState's
    // `parked_frames` docs). Deregistered on every return path below via
    // the wrapper around `execute_frames`.
    let frames_ptr: *const Vec<Frame> = &frames;
    gc_state.register_frames(frames_ptr);
    let result = execute_frames(
        classes,
        strings,
        objects,
        arrays,
        statics,
        gc_state,
        class_objects,
        handler,
        &mut frames,
    );
    gc_state.unregister_frames(frames_ptr);
    result
}

#[allow(clippy::too_many_arguments)]
fn execute_frames<H: NativeMethodHandler>(
    classes: &[ClassFile],
    strings: &mut StringTable,
    objects: &mut ObjectHeap,
    arrays: &mut ArrayHeap,
    statics: &mut StaticFieldStore,
    gc_state: &mut GcState,
    class_objects: &mut ClassObjectCache,
    handler: &mut H,
    frames: &mut Vec<Frame>,
) -> Result<Option<Value>, JvmError> {
    let mut ex = Executor {
        classes,
        strings,
        objects,
        arrays,
        statics,
        gc_state,
        class_objects,
        handler,
        field_cache: Vec::new(),
        method_cache: Vec::new(),
        static_field_cache: Vec::new(),
        pending_frame: None,
        pending_clinit_frames: Vec::new(),
        insn_count: 0,
        upcall_depth: 0,
    };
    ex.run(frames, 0)
}

impl<H: NativeMethodHandler> Executor<'_, H> {
    /// Run frames until the stack drops back to `base_depth`, returning the
    /// value the frame at `base_depth` returned.
    ///
    /// `base_depth == 0` is the top-level [`execute`] case. A synchronous
    /// native→Java upcall passes the depth the stack had *before* it pushed
    /// its callee, so the loop hands control back the moment that callee
    /// returns rather than running on into the caller's frames.
    fn run(
        &mut self,
        frames: &mut Vec<Frame>,
        base_depth: usize,
    ) -> Result<Option<Value>, JvmError> {
        let ex = self;

        // One-entry cache of the executing method's code slice.
        //
        // Without it every single bytecode re-derives `code` from scratch:
        // index `classes`, call `methods()` (a `OnceCell` load plus a `Box`
        // deref into the lazily-parsed metadata), index that, then reslice
        // `data()`. That is a lot of pointer chasing to answer a question whose
        // answer changes only when the frame changes -- which is to say, on
        // calls and returns, not on the long runs of straight-line bytecode in
        // between.
        //
        // Keying on `(class_idx, method_idx)` rather than on frame identity is
        // deliberate: a recursive call pushes a new frame for the *same* method,
        // and `method_code` is a pure function of that pair, so the cached slice
        // is still correct and recursion keeps the hit. `classes` is immutable
        // for the lifetime of the call, so nothing can invalidate the entry.
        let mut code_cache: Option<(usize, usize, &'static [u8])> = None;

        loop {
            // Cooperative stop-point: checked every 256 bytecode instructions.
            // Also folds heap-side alloc events so pure-bytecode alloc loops
            // can't outrun GC pacing between invokes.
            ex.insn_count = ex.insn_count.wrapping_add(1);
            if ex.insn_count == 0 {
                if ex.handler.interrupted() {
                    return Err(JvmError::Interrupted);
                }
                ex.fold_native_alloc_events();
            }
            #[cfg(feature = "parity-metrics")]
            crate::parity::count_insn();

            if frames.len() <= base_depth {
                return Ok(None);
            }
            let frame = match frames.last_mut() {
                Some(f) => f,
                None => return Ok(None),
            };

            let code = match code_cache {
                Some((ci, mi, code)) if ci == frame.class_idx && mi == frame.method_idx => code,
                _ => {
                    let cf = &ex.classes[frame.class_idx];
                    let code = cf.method_code(&cf.methods()[frame.method_idx]);
                    code_cache = Some((frame.class_idx, frame.method_idx, code));
                    code
                }
            };

            if frame.pc >= code.len() {
                pop_frame(ex, frames)?;
                if frames.len() == base_depth {
                    return Ok(None);
                }
                continue;
            }

            // Save instruction start PC for exception table lookup.
            frame.inst_pc = frame.pc;
            let opcode = code[frame.pc];
            frame.pc += 1;

            // Return opcodes are handled inline — they pop the frame stack.
            match opcode {
                0xac..=0xb0 => {
                    let mut v = frame.pop()?;
                    if frame.box_return != 0 {
                        v = helpers::box_primitive(ex.objects, frame.box_return, v)
                            .ok_or(JvmError::StackOverflow)?;
                    }
                    pop_frame(ex, frames)?;
                    if frames.len() == base_depth {
                        return Ok(Some(v));
                    }
                    frames.last_mut().unwrap().push(v)?;
                    continue;
                }
                0xb1 => {
                    pop_frame(ex, frames)?;
                    if frames.len() == base_depth {
                        return Ok(None);
                    }
                    continue;
                }
                _ => {}
            }

            let mut r: Result<(), JvmError> = match opcode {
                0x00..=0x14 => ex.op_constants(opcode, code, frame),
                0x15..=0x2d => ex.op_locals_load(opcode, code, frame),
                0x2e..=0x35 => ex.op_array_load(opcode, frame),
                0x36..=0x4e => ex.op_locals_store(opcode, code, frame),
                0x4f..=0x56 => ex.op_array_store(opcode, frame),
                0x57..=0x5f => ex.op_stack(opcode, frame),
                0x60..=0x84 => ex.op_math(opcode, code, frame),
                0x85..=0x98 => ex.op_convert(opcode, frame),
                0x99..=0xa7 | 0xaa | 0xab | 0xc0 | 0xc1 | 0xc6 | 0xc7 | 0xc8 => {
                    ex.op_control(opcode, code, frame)
                }
                0xb2..=0xb5 => ex.op_fields(opcode, code, frame),
                0xb6..=0xba => ex.op_invoke(opcode, code, frames),
                0xbb => ex.op_new(code, frame),
                0xbc..=0xbe | 0xc5 => ex.op_array_alloc(opcode, code, frame),
                0xbf => ex.op_athrow(frame),
                0xc2 => ex.op_monitorenter(frame),
                0xc3 => ex.op_monitorexit(frame),
                0xc4 => ex.op_wide(code, frame),
                op => Err(JvmError::UnsupportedOpcode(op)),
            };

            // Native dispatches mint allocations the bytecode opcodes never see —
            // fold them into GC pacing while they're fresh (the checkpoint above
            // covers pure-bytecode alloc loops).
            if matches!(opcode, 0xb6..=0xba) {
                ex.fold_native_alloc_events();
            }

            // If op_invoke resolved a Java method, push the new frame.
            if let Some(mut new_frame) = ex.pending_frame.take() {
                if r.is_ok() {
                    if frames.len() >= MAX_FRAME_DEPTH {
                        let e = ex.stack_overflow_error()?;
                        handle_exception(ex, frames, e, base_depth)?;
                        continue;
                    }
                    // A synchronized method takes its monitor before its
                    // frame exists on the stack; a failure to take it is the
                    // invoke's error and is handled below like any other.
                    match enter_synchronized(ex, &mut new_frame) {
                        Ok(()) => {
                            frames.push(new_frame);
                            continue;
                        }
                        Err(e) => r = Err(e),
                    }
                }
                // If the opcode errored, drop the pending frame and fall through
                // to exception handling below.
            }

            // If a trigger opcode detected an uninitialized class, push its
            // <clinit> frames.  The trigger already rewound its PC so the
            // instruction will re-execute once all clinits complete.
            if !ex.pending_clinit_frames.is_empty() && r.is_ok() {
                if frames.len() + ex.pending_clinit_frames.len() > MAX_FRAME_DEPTH {
                    ex.pending_clinit_frames.clear();
                    let e = ex.stack_overflow_error()?;
                    handle_exception(ex, frames, e, base_depth)?;
                    continue;
                }
                while let Some(cf) = ex.pending_clinit_frames.pop() {
                    frames.push(cf);
                }
                continue;
            }

            // Trigger GC when allocation counter crosses the threshold, or when
            // an allocator reported OOM (need_gc).  After an emergency GC the
            // opcode that failed has already been rewound and will re-execute.
            if r.is_ok() && (ex.alloc_count() >= GC_THRESHOLD || ex.need_gc()) {
                // Remember whether this collection was demanded by a failed
                // allocation (the opcode rewound itself for a retry) — if the
                // GC then frees nothing, the retry can never succeed and
                // would spin forever (bugbash J5's long[]-livelock).
                let for_failed_alloc = ex.need_gc();
                ex.set_need_gc(false);
                // Sample pre-sweep live bytes so handlers can track a heap
                // high-water mark — GC fires at peak pressure, so this is the
                // natural sample point.
                let pre_gc_used =
                    ex.objects.live_bytes() + ex.arrays.live_bytes() + ex.strings.live_bytes();
                let t0 = ex.handler.clock_nanos();
                let handler = &*ex.handler;
                let freed = crate::gc::collect(
                    frames,
                    ex.objects,
                    ex.arrays,
                    ex.strings,
                    ex.statics,
                    ex.class_objects,
                    ex.gc_state,
                    |visit| handler.gc_visit_roots(visit),
                );
                let t1 = ex.handler.clock_nanos();
                ex.handler
                    .report_gc(t1.wrapping_sub(t0), freed, pre_gc_used);
                prune_monitors(&mut *ex.handler, &*ex.objects, &*ex.arrays, &*ex.strings);
                ex.gc_state.alloc_count = 0;
                if for_failed_alloc && freed == 0 {
                    let e = ex.runtime_fault_obj("java/lang/OutOfMemoryError")?;
                    handle_exception(ex, frames, e, base_depth)?;
                    continue;
                }
                #[cfg(feature = "mem-diag")]
                {
                    let post_gc_live =
                        ex.objects.live_bytes() + ex.arrays.live_bytes() + ex.strings.live_bytes();
                    ex.gc_state.note_gc_cycle(freed, pre_gc_used, post_gc_live);
                    if crate::mem_diag::offensive() {
                        if let Err(m) =
                            crate::mem_diag::integrity_check(ex.objects, ex.arrays, ex.strings)
                        {
                            panic!("mem-diag post-GC integrity violation: {m}");
                        }
                    }
                }
            }

            match r {
                Ok(()) => {}
                Err(JvmError::Exception(obj_idx)) => {
                    handle_exception(ex, frames, obj_idx, base_depth)?;
                }
                // Bounds and size faults are catchable Java exceptions
                // (bugbash J4); translating here covers every array opcode
                // without touching each site. Other JvmErrors stay hard —
                // they signal interpreter/native bugs, not program faults.
                Err(JvmError::ArrayIndexOutOfBounds) => {
                    let e = ex.runtime_fault_obj("java/lang/ArrayIndexOutOfBoundsException")?;
                    handle_exception(ex, frames, e, base_depth)?;
                }
                Err(JvmError::NegativeArraySize) => {
                    let e = ex.runtime_fault_obj("java/lang/NegativeArraySizeException")?;
                    handle_exception(ex, frames, e, base_depth)?;
                }
                Err(e) => return Err(e),
            }
        }
    }

    /// Allocate the `StackOverflowError` thrown when a depth cap trips. If
    /// even that allocation fails the heap is exhausted, so fall back to the
    /// hard `JvmError::StackOverflow` (this crate's allocation-failure
    /// signal) rather than inventing an object index.
    /// Allocate a runtime-fault exception object by name, degrading to the
    /// hard `StackOverflow` signal only when even that allocation fails.
    fn runtime_fault_obj(&mut self, class: &'static str) -> Result<u16, JvmError> {
        self.objects.alloc(class).ok_or(JvmError::StackOverflow)
    }

    fn stack_overflow_error(&mut self) -> Result<u16, JvmError> {
        self.objects
            .alloc("java/lang/StackOverflowError")
            .ok_or(JvmError::StackOverflow)
    }
}
