// SPDX-License-Identifier: GPL-3.0-only
package picodroid.inject.compiler;

import java.io.IOException;
import java.io.Writer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeMirror;
import javax.tools.JavaFileObject;

/**
 * Shared pieces of the generated sources. Everything is emitted with fully-qualified names and no
 * imports, so a factory in one package can call one in another without collision handling, and the
 * output is byte-exact for the golden tests.
 */
final class SourceWriter {
  static final String HEADER =
      "// Generated by picodroid inject (picodroid.inject.compiler.InjectProcessor). Do not"
          + " edit.\n";

  private SourceWriter() {}

  static StringBuilder begin(TypeElement type) {
    StringBuilder sb = new StringBuilder(HEADER);
    String pkg = Names.packageOf(type).getQualifiedName().toString();
    if (!pkg.isEmpty()) {
      sb.append("package ").append(pkg).append(";\n");
    }
    sb.append('\n');
    return sb;
  }

  /** {@code pkg.Dep_Factory.get()} for a (validated, declared) dependency type. */
  static String factoryCall(TypeMirror dependency) {
    TypeElement te = (TypeElement) ((DeclaredType) dependency).asElement();
    return Names.generatedQualifiedName(te, Names.FACTORY_SUFFIX) + ".get()";
  }

  /** {@code pkg.Owner_MembersInjector.injectMembers(<expr>)}. */
  static String injectorCall(TypeElement owner, String expr) {
    return Names.generatedQualifiedName(owner, Names.MEMBERS_INJECTOR_SUFFIX)
        + ".injectMembers("
        + expr
        + ")";
  }

  static void emit(
      ProcessingEnvironment env, String qualifiedName, CharSequence source, TypeElement origin)
      throws IOException {
    JavaFileObject file = env.getFiler().createSourceFile(qualifiedName, origin);
    try (Writer w = file.openWriter()) {
      w.write(source.toString());
    }
  }
}
