#[cfg(not(test))]
extern crate alloc;

pub mod class_file;
pub mod frame;
pub mod heap;
pub mod interpreter;
pub mod native;
pub mod object_heap;
pub mod types;

#[cfg(not(test))]
use alloc::boxed::Box;
use class_file::ClassFile;
use heap::StringTable;
use heapless::Vec;
pub use native::NativeMethodHandler;
use object_heap::ObjectHeap;
use types::JvmError;

// Embedded .class bytes generated by build.rs from java/ sources
#[cfg(not(test))]
include!(concat!(env!("OUT_DIR"), "/java_classes.rs"));

pub struct Jvm {
    classes: Vec<ClassFile, 8>,
    pub strings: StringTable,
    pub objects: ObjectHeap,
}

impl Jvm {
    pub fn new() -> Self {
        Self {
            classes: Vec::new(),
            strings: StringTable::new(),
            objects: ObjectHeap::new(),
        }
    }

    pub fn load_class(&mut self, data: &'static [u8]) -> Result<(), JvmError> {
        let cf = ClassFile::parse(data).map_err(|_| JvmError::InvalidBytecode)?;
        self.classes.push(cf).map_err(|_| JvmError::ClassNotFound)
    }

    pub fn invoke_static(
        &mut self,
        class_name: &str,
        method_name: &str,
        handler: &mut impl NativeMethodHandler,
    ) -> Result<(), JvmError> {
        let (ci, mi) = self
            .classes
            .iter()
            .enumerate()
            .find_map(|(ci, cf)| {
                let cn = cf.class_name()?;
                if cn != class_name.as_bytes() {
                    return None;
                }
                cf.methods.iter().enumerate().find_map(|(mi, m)| {
                    let mn = cf.cp_utf8(m.name_index)?;
                    if mn == method_name.as_bytes() {
                        Some((ci, mi))
                    } else {
                        None
                    }
                })
            })
            .ok_or(JvmError::MethodNotFound)?;

        interpreter::execute(
            &self.classes,
            &mut self.strings,
            &mut self.objects,
            handler,
            ci,
            mi,
            &[],
        )?;
        Ok(())
    }
}

#[cfg(not(test))]
pub fn run_jvm() -> ! {
    let mut jvm = Box::new(Jvm::new());
    let mut handler = crate::system::native_handler::PicodroidNativeHandler;

    jvm.load_class(BLINKY_LEDBLINK_CLASS).unwrap();
    jvm.load_class(PICODROID_PIO_GPIO_CLASS).unwrap();
    jvm.load_class(PICODROID_PIO_PERIPHERALMANAGER_CLASS)
        .unwrap();
    jvm.load_class(PICODROID_PIO_UARTDEVICE_CLASS).unwrap();
    jvm.load_class(PICODROID_OS_SYSTEMCLOCK_CLASS).unwrap();
    jvm.load_class(PICODROID_UTIL_LOG_CLASS).unwrap();

    jvm.invoke_static("blinky/LedBlink", "main", &mut handler)
        .unwrap();

    loop {
        freertos_rust::CurrentTask::delay(freertos_rust::Duration::ms(60_000));
    }
}
