#!/usr/bin/env bash
# Regenerate the Java (and, for apps with a bridge/, the Python) that
# examples/*/proto/*.proto compile to, with protoc-gen-picodroid
# (tools/protoc-gen-picodroid/). Generated files are committed; `--check`
# regenerates into a scratch directory and fails when the committed copies
# differ, which is what pre-commit's `proto` stage and CI run.
#
# Needs the toolchain in tools/protoc-gen-picodroid/requirements.txt on
# PICODROID_PROTO_PYTHON (default: python3). protoc starts the plugin by its
# `#!/usr/bin/env python3` line, so that interpreter's directory goes first
# on PATH for the run.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PLUGIN="$REPO_ROOT/tools/protoc-gen-picodroid/protoc_gen_picodroid.py"
JAR="$REPO_ROOT/third_party/google-java-format-1.36.1-all-deps.jar"
PY="${PICODROID_PROTO_PYTHON:-python3}"

MODE=generate
[[ "${1:-}" == "--check" ]] && MODE=check

if ! "$PY" -c 'import grpc_tools.protoc, google.protobuf.compiler.plugin_pb2' 2>/dev/null; then
  echo "gen-proto: $PY lacks grpc_tools — pip install -r tools/protoc-gen-picodroid/requirements.txt" >&2
  echo "           (or point PICODROID_PROTO_PYTHON at an interpreter that has it)" >&2
  exit 2
fi
PY_BIN="$(cd "$(dirname "$("$PY" -c 'import sys; print(sys.executable)')")" && pwd)"
export PATH="$PY_BIN:$PATH"
[[ -f "$JAR" ]] || bash "$SCRIPT_DIR/format_java.sh" fetch >/dev/null

# One app's proto -> its java/ (and bridge/) trees under $dest_root, which is
# the repo for `generate` and a scratch tree for `check`.
gen_app() {
  local app="$1" dest_root="$2" proto_dir java_out py_out
  proto_dir="$REPO_ROOT/examples/$app/proto"
  java_out="$dest_root/examples/$app/java"
  mkdir -p "$java_out"
  local args=(-I"$proto_dir" "--plugin=protoc-gen-picodroid=$PLUGIN" "--picodroid_out=$java_out")
  if [[ -d "$REPO_ROOT/examples/$app/bridge" ]]; then
    py_out="$dest_root/examples/$app/bridge"
    mkdir -p "$py_out"
    args+=("--python_out=$py_out")
  fi
  local f
  for f in "$proto_dir"/*.proto; do
    "$PY" -m grpc_tools.protoc "${args[@]}" "$(basename "$f")"
  done
  find "$java_out" -name '*.java' -newer "$PLUGIN" -print0 2>/dev/null | xargs -0 -r java -jar "$JAR" --replace
}

# The files a .proto owns: every generated Java under the app's java tree
# (by its header line) and the *_pb2.py beside the bridge.
owned_files() {
  local app="$1" root="$2"
  grep -rl --include='*.java' '^// Generated by protoc-gen-picodroid' "$root/examples/$app/java" 2>/dev/null || true
  ls "$root/examples/$app/bridge/"*_pb2.py 2>/dev/null || true
}

apps=()
for d in "$REPO_ROOT"/examples/*/proto; do
  [[ -d "$d" ]] && apps+=("$(basename "$(dirname "$d")")")
done
if [[ ${#apps[@]} -eq 0 ]]; then
  echo "gen-proto: no examples/*/proto directories"
  exit 0
fi

if [[ "$MODE" == generate ]]; then
  for app in "${apps[@]}"; do
    gen_app "$app" "$REPO_ROOT"
    echo "gen-proto: $app regenerated"
  done
  exit 0
fi

scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"' EXIT
status=0
for app in "${apps[@]}"; do
  gen_app "$app" "$scratch"
  while IFS= read -r fresh; do
    [[ -z "$fresh" ]] && continue
    rel="${fresh#"$scratch"/}"
    if ! cmp -s "$fresh" "$REPO_ROOT/$rel"; then
      echo "gen-proto: STALE $rel"
      status=1
    fi
  done < <(owned_files "$app" "$scratch")
  # A committed generated file whose .proto no longer produces it.
  while IFS= read -r committed; do
    [[ -z "$committed" ]] && continue
    rel="${committed#"$REPO_ROOT"/}"
    if [[ ! -f "$scratch/$rel" ]]; then
      echo "gen-proto: ORPHAN $rel"
      status=1
    fi
  done < <(owned_files "$app" "$REPO_ROOT")
done
if [[ $status -ne 0 ]]; then
  echo "gen-proto: committed generated sources differ — run ./scripts/gen-proto.sh" >&2
else
  echo "gen-proto: generated sources are current (${apps[*]})"
fi
exit $status
