// SPDX-License-Identifier: GPL-3.0-only
//! The compiled-in trust store: root certificates a server chain may end
//! at. Generated by `build.rs` from `roots/*.der` plus the optional
//! `PICODROID_TLS_EXTRA_CA` (the nightly's test CA).

/// One trust anchor: its DER certificate and, precomputed, the Subject
/// `Name` TLV that a chain entry's Issuer must equal byte for byte.
pub struct Anchor {
    pub name: &'static str,
    pub subject: &'static [u8],
    pub der: &'static [u8],
}

include!(concat!(env!("OUT_DIR"), "/anchors.rs"));

/// Choose the anchor for a server chain, leaf first: the first entry whose
/// Issuer is an anchor's Subject decides, and the chain is cut after it
/// (`keep` entries) — the server's extra entries, typically a cross-signed
/// copy of the root, are never looked at. `None` when no entry is issued
/// by any anchor, or an entry is not a certificate the walker understands.
pub fn select<'a, 'e, I>(anchors: &'a [Anchor], entries: I) -> Option<(&'a Anchor, usize)>
where
    I: IntoIterator<Item = &'e [u8]>,
{
    for (i, der) in entries.into_iter().enumerate() {
        let names = crate::der_lite::cert_names(der)?;
        let issuer = &der[names.issuer];
        if let Some(a) = anchors.iter().find(|a| a.subject == issuer) {
            return Some((a, i + 1));
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn store_holds_the_committed_roots() {
        assert!(ANCHORS.len() >= 14, "{}", ANCHORS.len());
        for a in ANCHORS {
            let n = crate::der_lite::cert_names(a.der).unwrap();
            assert_eq!(&a.der[n.subject], a.subject, "{}", a.name);
        }
        assert!(ANCHORS.iter().any(|a| a.name == "gts_root_r4"));
        assert!(ANCHORS.iter().any(|a| a.name == "isrg_root_x1"));
    }

    /// A chain that ends in a cross-signed copy of the root (what
    /// api.anthropic.com serves) resolves at the intermediate and keeps two
    /// entries; the self-signed root itself resolves at itself.
    #[test]
    fn select_stops_at_the_first_anchor_issued_entry() {
        let r4 = ANCHORS.iter().find(|a| a.name == "gts_root_r4").unwrap();
        let x1 = ANCHORS.iter().find(|a| a.name == "isrg_root_x1").unwrap();
        // A root sent as its own chain: issued by itself.
        assert!(matches!(select(ANCHORS, [r4.der]), Some((a, 1)) if a.name == "gts_root_r4"));
        // Leaf-then-root order: the root entry decides at position 2.
        assert!(
            matches!(select(ANCHORS, [x1.der, r4.der]), Some((a, 1)) if a.name == "isrg_root_x1")
        );
        assert!(select(ANCHORS, [&[0x30, 0x00][..]]).is_none());
        assert!(select(&ANCHORS[..0], [r4.der]).is_none());
    }
}
