#[cfg(not(test))]
use alloc::boxed::Box;
#[cfg(not(test))]
use pico_jvm::types::JvmError;
#[cfg(not(test))]
use pico_jvm::{Jvm, SharedJvmHeap};

// Embedded .class bytes generated by build.rs from java/ sources
#[cfg(not(test))]
include!(concat!(env!("OUT_DIR"), "/java_classes.rs"));

// ── Shared heap ──────────────────────────────────────────────────────────────
//
// All JVM threads share a single heap (objects, arrays, strings), matching the
// standard Java memory model.  On the single-core RP2040/RP2350 only one
// FreeRTOS task runs at a time, so concurrent access is safe without a global
// lock.  Allocation paths are short critical regions protected by the
// single-core scheduling guarantee.

// SAFETY: single-core Cortex-M; only one FreeRTOS task executes at a time.
#[cfg(not(test))]
struct SharedHeapCell(core::cell::UnsafeCell<SharedJvmHeap>);
#[cfg(not(test))]
unsafe impl Sync for SharedHeapCell {}

#[cfg(not(test))]
static SHARED_HEAP: SharedHeapCell =
    SharedHeapCell(core::cell::UnsafeCell::new(SharedJvmHeap::new()));

/// Return a mutable reference to the process-wide shared JVM heap.
///
/// # Safety
/// Must only be called from FreeRTOS task context on the single core used by
/// picodroid (never from an ISR).  Alloc operations inside ObjectHeap and
/// ArrayHeap are short enough that a task switch mid-alloc cannot occur on
/// cooperative yield points (sleep / UART read).
#[cfg(not(test))]
pub fn shared_heap() -> &'static mut SharedJvmHeap {
    unsafe { &mut *SHARED_HEAP.0.get() }
}

// ── Class loader registration ─────────────────────────────────────────────────
//
// The `Thread.start()` native handler spawns a new FreeRTOS task that creates
// a fresh Jvm and must load all application classes before invoking Runnable.run().
// Rather than hard-coding a specific demo's class list in the framework,
// `run_jvm()` registers a loader function once before the scheduler yields to
// any thread task.

#[cfg(not(test))]
type ClassLoaderFn = fn(&mut Jvm) -> Result<(), JvmError>;

// SAFETY: single-core Cortex-M; only one FreeRTOS task executes at a time.
// register_class_loader() is called once from the JVM bootstrap task before
// any Thread.start() dispatch can occur.
#[cfg(not(test))]
struct ClassLoaderCell(core::cell::UnsafeCell<Option<ClassLoaderFn>>);
#[cfg(not(test))]
unsafe impl Sync for ClassLoaderCell {}

#[cfg(not(test))]
static CLASS_LOADER: ClassLoaderCell = ClassLoaderCell(core::cell::UnsafeCell::new(None));

#[cfg(not(test))]
#[allow(dead_code)]
pub fn register_class_loader(f: ClassLoaderFn) {
    unsafe { *CLASS_LOADER.0.get() = Some(f) }
}

#[cfg(not(test))]
pub fn load_classes(jvm: &mut Jvm) -> Result<(), JvmError> {
    unsafe {
        match *CLASS_LOADER.0.get() {
            Some(f) => f(jvm),
            None => Ok(()),
        }
    }
}

// ── run_jvm ───────────────────────────────────────────────────────────────────

#[cfg(not(test))]
pub fn run_jvm() -> ! {
    let mut jvm = Box::new(Jvm::new());
    let heap = shared_heap();
    let mut handler = crate::system::native_handler::PicodroidNativeHandler;

    #[cfg(not(any(
        feature = "helloworld",
        feature = "blinky",
        feature = "uart",
        feature = "arraydemo",
        feature = "inherit",
        feature = "interfacedemo",
        feature = "floatdemo",
        feature = "exceptiondemo",
        feature = "threaddemo",
        feature = "mathsdemo",
    )))]
    compile_error!(
        "No example feature selected. Use --app helloworld, blinky, uart, arraydemo, inherit, interfacedemo, floatdemo, exceptiondemo, threaddemo, or mathsdemo."
    );

    #[cfg(all(feature = "helloworld", feature = "blinky"))]
    compile_error!("Features 'helloworld' and 'blinky' are mutually exclusive.");

    #[cfg(all(feature = "helloworld", feature = "uart"))]
    compile_error!("Features 'helloworld' and 'uart' are mutually exclusive.");

    #[cfg(all(feature = "helloworld", feature = "arraydemo"))]
    compile_error!("Features 'helloworld' and 'arraydemo' are mutually exclusive.");

    #[cfg(all(feature = "blinky", feature = "uart"))]
    compile_error!("Features 'blinky' and 'uart' are mutually exclusive.");

    #[cfg(all(feature = "blinky", feature = "arraydemo"))]
    compile_error!("Features 'blinky' and 'arraydemo' are mutually exclusive.");

    #[cfg(all(feature = "uart", feature = "arraydemo"))]
    compile_error!("Features 'uart' and 'arraydemo' are mutually exclusive.");

    #[cfg(all(feature = "helloworld", feature = "inherit"))]
    compile_error!("Features 'helloworld' and 'inherit' are mutually exclusive.");

    #[cfg(all(feature = "blinky", feature = "inherit"))]
    compile_error!("Features 'blinky' and 'inherit' are mutually exclusive.");

    #[cfg(all(feature = "uart", feature = "inherit"))]
    compile_error!("Features 'uart' and 'inherit' are mutually exclusive.");

    #[cfg(all(feature = "arraydemo", feature = "inherit"))]
    compile_error!("Features 'arraydemo' and 'inherit' are mutually exclusive.");

    #[cfg(all(feature = "helloworld", feature = "interfacedemo"))]
    compile_error!("Features 'helloworld' and 'interfacedemo' are mutually exclusive.");

    #[cfg(all(feature = "blinky", feature = "interfacedemo"))]
    compile_error!("Features 'blinky' and 'interfacedemo' are mutually exclusive.");

    #[cfg(all(feature = "uart", feature = "interfacedemo"))]
    compile_error!("Features 'uart' and 'interfacedemo' are mutually exclusive.");

    #[cfg(all(feature = "arraydemo", feature = "interfacedemo"))]
    compile_error!("Features 'arraydemo' and 'interfacedemo' are mutually exclusive.");

    #[cfg(all(feature = "inherit", feature = "interfacedemo"))]
    compile_error!("Features 'inherit' and 'interfacedemo' are mutually exclusive.");

    #[cfg(all(feature = "helloworld", feature = "floatdemo"))]
    compile_error!("Features 'helloworld' and 'floatdemo' are mutually exclusive.");

    #[cfg(all(feature = "blinky", feature = "floatdemo"))]
    compile_error!("Features 'blinky' and 'floatdemo' are mutually exclusive.");

    #[cfg(all(feature = "uart", feature = "floatdemo"))]
    compile_error!("Features 'uart' and 'floatdemo' are mutually exclusive.");

    #[cfg(all(feature = "arraydemo", feature = "floatdemo"))]
    compile_error!("Features 'arraydemo' and 'floatdemo' are mutually exclusive.");

    #[cfg(all(feature = "inherit", feature = "floatdemo"))]
    compile_error!("Features 'inherit' and 'floatdemo' are mutually exclusive.");

    #[cfg(all(feature = "interfacedemo", feature = "floatdemo"))]
    compile_error!("Features 'interfacedemo' and 'floatdemo' are mutually exclusive.");

    #[cfg(all(feature = "helloworld", feature = "exceptiondemo"))]
    compile_error!("Features 'helloworld' and 'exceptiondemo' are mutually exclusive.");

    #[cfg(all(feature = "blinky", feature = "exceptiondemo"))]
    compile_error!("Features 'blinky' and 'exceptiondemo' are mutually exclusive.");

    #[cfg(all(feature = "uart", feature = "exceptiondemo"))]
    compile_error!("Features 'uart' and 'exceptiondemo' are mutually exclusive.");

    #[cfg(all(feature = "arraydemo", feature = "exceptiondemo"))]
    compile_error!("Features 'arraydemo' and 'exceptiondemo' are mutually exclusive.");

    #[cfg(all(feature = "inherit", feature = "exceptiondemo"))]
    compile_error!("Features 'inherit' and 'exceptiondemo' are mutually exclusive.");

    #[cfg(all(feature = "interfacedemo", feature = "exceptiondemo"))]
    compile_error!("Features 'interfacedemo' and 'exceptiondemo' are mutually exclusive.");

    #[cfg(all(feature = "floatdemo", feature = "exceptiondemo"))]
    compile_error!("Features 'floatdemo' and 'exceptiondemo' are mutually exclusive.");

    #[cfg(all(feature = "helloworld", feature = "threaddemo"))]
    compile_error!("Features 'helloworld' and 'threaddemo' are mutually exclusive.");

    #[cfg(all(feature = "blinky", feature = "threaddemo"))]
    compile_error!("Features 'blinky' and 'threaddemo' are mutually exclusive.");

    #[cfg(all(feature = "uart", feature = "threaddemo"))]
    compile_error!("Features 'uart' and 'threaddemo' are mutually exclusive.");

    #[cfg(all(feature = "arraydemo", feature = "threaddemo"))]
    compile_error!("Features 'arraydemo' and 'threaddemo' are mutually exclusive.");

    #[cfg(all(feature = "inherit", feature = "threaddemo"))]
    compile_error!("Features 'inherit' and 'threaddemo' are mutually exclusive.");

    #[cfg(all(feature = "interfacedemo", feature = "threaddemo"))]
    compile_error!("Features 'interfacedemo' and 'threaddemo' are mutually exclusive.");

    #[cfg(all(feature = "floatdemo", feature = "threaddemo"))]
    compile_error!("Features 'floatdemo' and 'threaddemo' are mutually exclusive.");

    #[cfg(all(feature = "exceptiondemo", feature = "threaddemo"))]
    compile_error!("Features 'exceptiondemo' and 'threaddemo' are mutually exclusive.");

    #[cfg(all(feature = "helloworld", feature = "mathsdemo"))]
    compile_error!("Features 'helloworld' and 'mathsdemo' are mutually exclusive.");

    #[cfg(all(feature = "blinky", feature = "mathsdemo"))]
    compile_error!("Features 'blinky' and 'mathsdemo' are mutually exclusive.");

    #[cfg(all(feature = "uart", feature = "mathsdemo"))]
    compile_error!("Features 'uart' and 'mathsdemo' are mutually exclusive.");

    #[cfg(all(feature = "arraydemo", feature = "mathsdemo"))]
    compile_error!("Features 'arraydemo' and 'mathsdemo' are mutually exclusive.");

    #[cfg(all(feature = "inherit", feature = "mathsdemo"))]
    compile_error!("Features 'inherit' and 'mathsdemo' are mutually exclusive.");

    #[cfg(all(feature = "interfacedemo", feature = "mathsdemo"))]
    compile_error!("Features 'interfacedemo' and 'mathsdemo' are mutually exclusive.");

    #[cfg(all(feature = "floatdemo", feature = "mathsdemo"))]
    compile_error!("Features 'floatdemo' and 'mathsdemo' are mutually exclusive.");

    #[cfg(all(feature = "exceptiondemo", feature = "mathsdemo"))]
    compile_error!("Features 'exceptiondemo' and 'mathsdemo' are mutually exclusive.");

    #[cfg(all(feature = "threaddemo", feature = "mathsdemo"))]
    compile_error!("Features 'threaddemo' and 'mathsdemo' are mutually exclusive.");

    #[cfg(feature = "helloworld")]
    {
        jvm.load_class(HELLOWORLD_HELLOWORLD_CLASS).unwrap();
        jvm.load_class(PICODROID_UTIL_LOG_CLASS).unwrap();
        jvm.invoke_static("helloworld/HelloWorld", "main", heap, &mut handler)
            .unwrap();
    }

    #[cfg(feature = "blinky")]
    {
        jvm.load_class(BLINKY_LEDBLINK_CLASS).unwrap();
        jvm.load_class(PICODROID_PIO_GPIO_CLASS).unwrap();
        jvm.load_class(PICODROID_PIO_PERIPHERALMANAGER_CLASS)
            .unwrap();
        jvm.load_class(PICODROID_OS_SYSTEMCLOCK_CLASS).unwrap();
        jvm.load_class(PICODROID_UTIL_LOG_CLASS).unwrap();
        jvm.invoke_static("blinky/LedBlink", "main", heap, &mut handler)
            .unwrap();
    }

    #[cfg(feature = "uart")]
    {
        jvm.load_class(UART_UARTECHO_CLASS).unwrap();
        jvm.load_class(PICODROID_PIO_PERIPHERALMANAGER_CLASS)
            .unwrap();
        jvm.load_class(PICODROID_PIO_UARTDEVICE_CLASS).unwrap();
        jvm.load_class(PICODROID_UTIL_LOG_CLASS).unwrap();
        jvm.invoke_static("uart/UartEcho", "main", heap, &mut handler)
            .unwrap();
    }

    #[cfg(feature = "arraydemo")]
    {
        jvm.load_class(ARRAYDEMO_ARRAYDEMO_CLASS).unwrap();
        jvm.load_class(PICODROID_PIO_PERIPHERALMANAGER_CLASS)
            .unwrap();
        jvm.load_class(PICODROID_PIO_UARTDEVICE_CLASS).unwrap();
        jvm.load_class(PICODROID_UTIL_LOG_CLASS).unwrap();
        jvm.invoke_static("arraydemo/ArrayDemo", "main", heap, &mut handler)
            .unwrap();
    }

    #[cfg(feature = "inherit")]
    {
        // Load Animal before Dog so field_slot() can walk the hierarchy
        jvm.load_class(INHERIT_ANIMAL_CLASS).unwrap();
        jvm.load_class(INHERIT_DOG_CLASS).unwrap();
        jvm.load_class(INHERIT_INHERITDEMO_CLASS).unwrap();
        jvm.load_class(PICODROID_UTIL_LOG_CLASS).unwrap();
        jvm.invoke_static("inherit/InheritDemo", "main", heap, &mut handler)
            .unwrap();
    }

    #[cfg(feature = "interfacedemo")]
    {
        // Load interface and abstract base before concrete subclasses
        jvm.load_class(INTERFACEDEMO_SPEAKABLE_CLASS).unwrap();
        jvm.load_class(INTERFACEDEMO_ANIMAL_CLASS).unwrap();
        jvm.load_class(INTERFACEDEMO_DOG_CLASS).unwrap();
        jvm.load_class(INTERFACEDEMO_CAT_CLASS).unwrap();
        jvm.load_class(INTERFACEDEMO_INTERFACEDEMO_CLASS).unwrap();
        jvm.load_class(PICODROID_UTIL_LOG_CLASS).unwrap();
        jvm.invoke_static("interfacedemo/InterfaceDemo", "main", heap, &mut handler)
            .unwrap();
    }

    #[cfg(feature = "floatdemo")]
    {
        jvm.load_class(FLOATDEMO_FLOATDEMO_CLASS).unwrap();
        jvm.load_class(PICODROID_UTIL_LOG_CLASS).unwrap();
        jvm.invoke_static("floatdemo/FloatDemo", "main", heap, &mut handler)
            .unwrap();
    }

    #[cfg(feature = "exceptiondemo")]
    {
        // Load exception class before the main class so the hierarchy is known
        jvm.load_class(EXCEPTIONDEMO_APPEXCEPTION_CLASS).unwrap();
        jvm.load_class(EXCEPTIONDEMO_EXCEPTIONDEMO_CLASS).unwrap();
        jvm.load_class(PICODROID_UTIL_LOG_CLASS).unwrap();
        jvm.invoke_static("exceptiondemo/ExceptionDemo", "main", heap, &mut handler)
            .unwrap();
    }

    #[cfg(feature = "threaddemo")]
    {
        fn load_threaddemo(jvm: &mut Jvm) -> Result<(), JvmError> {
            jvm.load_class(THREADDEMO_THREADDEMO_CLASS)?;
            jvm.load_class(THREADDEMO_TASK1_CLASS)?;
            jvm.load_class(THREADDEMO_TASK2_CLASS)?;
            jvm.load_class(PICODROID_CONCURRENT_THREAD_CLASS)?;
            jvm.load_class(PICODROID_OS_SYSTEMCLOCK_CLASS)?;
            jvm.load_class(PICODROID_UTIL_LOG_CLASS)?;
            Ok(())
        }
        register_class_loader(load_threaddemo);
        load_threaddemo(&mut jvm).unwrap();
        jvm.invoke_static("threaddemo/ThreadDemo", "main", heap, &mut handler)
            .unwrap();
    }

    #[cfg(feature = "mathsdemo")]
    {
        jvm.load_class(MATHSDEMO_SHAPE_CLASS).unwrap();
        jvm.load_class(MATHSDEMO_CIRCLE_CLASS).unwrap();
        jvm.load_class(MATHSDEMO_MATHSDEMO_CLASS).unwrap();
        jvm.load_class(PICODROID_UTIL_LOG_CLASS).unwrap();
        jvm.invoke_static("mathsdemo/MathsDemo", "main", heap, &mut handler)
            .unwrap();
    }

    loop {
        freertos_rust::CurrentTask::delay(freertos_rust::Duration::ms(60_000));
    }
}
