#[cfg(not(test))]
use alloc::boxed::Box;
#[cfg(not(test))]
use pico_jvm::apk::Papk;
#[cfg(not(test))]
use pico_jvm::types::JvmError;
#[cfg(not(test))]
use pico_jvm::{Jvm, SharedJvmHeap};

// Embedded APK bytes, generated by build.rs from the PICODROID_APK_PATH env var.
// Defines: pub static APK_DATA: &[u8] = include_bytes!("path/to/app.papk");
#[cfg(not(test))]
include!(concat!(env!("OUT_DIR"), "/apk_data.rs"));

// Embedded picodroid framework class bytecode, compiled and embedded by build.rs.
// Defines: pub static FRAMEWORK_CLASSES: &[&[u8]] = &[include_bytes!("..."), ...];
// Framework classes are part of the platform (like Android's boot classpath), not
// the APK — so they are always present in firmware Flash regardless of which app runs.
#[cfg(not(test))]
include!(concat!(env!("OUT_DIR"), "/framework_classes.rs"));

// ── Shared heap ──────────────────────────────────────────────────────────────
//
// All JVM threads share a single heap (objects, arrays, strings), matching the
// standard Java memory model.  On the single-core RP2040/RP2350 only one
// FreeRTOS task runs at a time, so concurrent access is safe without a global
// lock.  Allocation paths are short critical regions protected by the
// single-core scheduling guarantee.

// SAFETY: single-core Cortex-M; only one FreeRTOS task executes at a time.
#[cfg(not(test))]
struct SharedHeapCell(core::cell::UnsafeCell<SharedJvmHeap>);
#[cfg(not(test))]
unsafe impl Sync for SharedHeapCell {}

#[cfg(not(test))]
static SHARED_HEAP: SharedHeapCell =
    SharedHeapCell(core::cell::UnsafeCell::new(SharedJvmHeap::new()));

/// Return a mutable reference to the process-wide shared JVM heap.
///
/// # Safety
/// Must only be called from FreeRTOS task context on the single core used by
/// picodroid (never from an ISR).  Alloc operations inside ObjectHeap and
/// ArrayHeap are short enough that a task switch mid-alloc cannot occur on
/// cooperative yield points (sleep / UART read).
#[cfg(not(test))]
pub fn shared_heap() -> &'static mut SharedJvmHeap {
    unsafe { &mut *SHARED_HEAP.0.get() }
}

// ── Class loader registration ─────────────────────────────────────────────────
//
// The `Thread.start()` native handler spawns a new FreeRTOS task that creates
// a fresh Jvm and must load all application classes before invoking Runnable.run().
// A universal loader function reads all classes directly from the embedded APK,
// so every app (including threaddemo) works without special-casing.

#[cfg(not(test))]
type ClassLoaderFn = fn(&mut Jvm) -> Result<(), JvmError>;

// SAFETY: single-core Cortex-M; only one FreeRTOS task executes at a time.
// register_class_loader() is called once from the JVM bootstrap task before
// any Thread.start() dispatch can occur.
#[cfg(not(test))]
struct ClassLoaderCell(core::cell::UnsafeCell<Option<ClassLoaderFn>>);
#[cfg(not(test))]
unsafe impl Sync for ClassLoaderCell {}

#[cfg(not(test))]
static CLASS_LOADER: ClassLoaderCell = ClassLoaderCell(core::cell::UnsafeCell::new(None));

#[cfg(not(test))]
#[allow(dead_code)]
pub fn register_class_loader(f: ClassLoaderFn) {
    unsafe { *CLASS_LOADER.0.get() = Some(f) }
}

#[cfg(not(test))]
#[cfg_attr(feature = "sim", allow(dead_code))]
pub fn load_classes(jvm: &mut Jvm) -> Result<(), JvmError> {
    unsafe {
        match *CLASS_LOADER.0.get() {
            Some(f) => f(jvm),
            None => Ok(()),
        }
    }
}

// ── Framework class loading ───────────────────────────────────────────────────

/// Loads all picodroid framework classes into `jvm`.
///
/// Framework classes (`picodroid.*`) are compiled by `build.rs` and embedded
/// directly in firmware Flash — they are platform code, not app code.
/// This mirrors Android's boot classpath model.
#[cfg(not(test))]
fn load_framework_classes(jvm: &mut Jvm) -> Result<(), JvmError> {
    for class_data in FRAMEWORK_CLASSES {
        jvm.load_class(class_data)?;
    }
    Ok(())
}

// ── Active APK pointer ────────────────────────────────────────────────────────
//
// run_jvm_with() stores a pointer to the current APK here so that
// load_classes_from_apk() (a bare fn, not a closure) can serve both the
// baked-in APK_DATA and a dynamically-installed PAPK for Thread.start()
// spawned tasks without needing a global allocator or closure captures.
//
// SAFETY: single-core Cortex-M; only one FreeRTOS task writes (jvm_task) and
// only one reads (jvm_task or jvm-t spawned tasks) at a time.
#[cfg(not(test))]
struct ActiveApkCell(core::cell::UnsafeCell<(*const u8, usize)>);
#[cfg(not(test))]
unsafe impl Sync for ActiveApkCell {}

#[cfg(not(test))]
static ACTIVE_APK: ActiveApkCell =
    ActiveApkCell(core::cell::UnsafeCell::new((core::ptr::null(), 0)));

// ── APK-driven class loading ──────────────────────────────────────────────────

/// Loads all classes from the active APK into `jvm`.
///
/// Used both during initial JVM startup and by the `Thread.start()` native
/// handler when it spawns a fresh `Jvm` for a new thread.  Reads the APK
/// pointer set by `run_jvm_with()` so that dynamically-installed PAPKs
/// are loaded correctly in child threads without closure captures.
#[cfg(not(test))]
fn load_classes_from_apk(jvm: &mut Jvm) -> Result<(), JvmError> {
    let apk_data: &[u8] = unsafe {
        let (ptr, len) = *ACTIVE_APK.0.get();
        if ptr.is_null() {
            APK_DATA
        } else {
            core::slice::from_raw_parts(ptr, len)
        }
    };
    let apk = Papk::parse(apk_data).map_err(|_| JvmError::InvalidBytecode)?;
    for entry in apk.classes().map_err(|_| JvmError::InvalidBytecode)? {
        jvm.load_class(entry.data)?;
    }
    Ok(())
}

/// Loads framework classes then app classes — used by `Thread.start()` spawned
/// tasks that need a fully-populated fresh `Jvm`.
#[cfg(not(test))]
fn load_all_classes(jvm: &mut Jvm) -> Result<(), JvmError> {
    load_framework_classes(jvm)?;
    load_classes_from_apk(jvm)
}

// ── run_jvm_with / run_jvm ────────────────────────────────────────────────────

/// Run the JVM with a specific APK slice.
///
/// Resets the shared heap (clearing previous app state), loads framework and
/// app classes, then calls `<main_class>.main()`.  Returns when execution
/// completes naturally or is interrupted by `pdb install` (cooperative stop).
/// `JvmError::Interrupted` is silently ignored — it is a clean exit signal.
#[cfg(not(test))]
pub fn run_jvm_with(apk_data: &[u8]) {
    // Publish the APK pointer so load_classes_from_apk (a bare fn) picks it up
    // even when called from Thread.start()-spawned child tasks.
    unsafe { *ACTIVE_APK.0.get() = (apk_data.as_ptr(), apk_data.len()) };

    // Clear previous app's heap state before running a new app.
    shared_heap().reset();

    let mut jvm = Box::new(Jvm::new());
    let heap = shared_heap();
    let mut handler = crate::system::native_handler::PicodroidNativeHandler;

    // Register the combined loader so Thread.start() spawned tasks load both
    // framework and app classes into their fresh Jvm instances.
    register_class_loader(load_all_classes);

    // Load platform (framework) classes first, then app classes from the APK.
    load_framework_classes(&mut jvm).unwrap();
    load_classes_from_apk(&mut jvm).unwrap();

    // Determine the entry point from the APK manifest.
    let apk = Papk::parse(apk_data).unwrap();
    let main_class = apk
        .main_class()
        .expect("APK manifest is missing 'main-class'");

    // Interrupted is a clean cooperative stop — not a real error.
    match jvm.invoke_static(main_class, "main", heap, &mut handler) {
        Ok(_) | Err(JvmError::Interrupted) => {}
        #[cfg(not(feature = "sim"))]
        Err(e) => defmt::error!("JVM error: {}", defmt::Debug2Format(&e)),
        #[cfg(feature = "sim")]
        Err(e) => eprintln!("[jvm] error: {:?}", e),
    }
}

/// Run the JVM with the baked-in APK (sim entry point).
#[cfg(not(test))]
#[cfg_attr(not(feature = "sim"), allow(dead_code))]
pub fn run_jvm() {
    run_jvm_with(APK_DATA);

    #[cfg(not(feature = "sim"))]
    loop {
        freertos_rust::CurrentTask::delay(freertos_rust::Duration::ms(60_000));
    }
}
