#[cfg(not(test))]
use alloc::boxed::Box;
#[cfg(not(test))]
use pico_jvm::apk::Papk;
#[cfg(not(test))]
use pico_jvm::types::JvmError;
#[cfg(not(test))]
use pico_jvm::{Jvm, SharedJvmHeap};

// Embedded APK bytes, generated by build.rs from the PICODROID_APK_PATH env var.
// Defines: pub static APK_DATA: &[u8] = include_bytes!("path/to/app.papk");
#[cfg(not(test))]
include!(concat!(env!("OUT_DIR"), "/apk_data.rs"));

// ── Shared heap ──────────────────────────────────────────────────────────────
//
// All JVM threads share a single heap (objects, arrays, strings), matching the
// standard Java memory model.  On the single-core RP2040/RP2350 only one
// FreeRTOS task runs at a time, so concurrent access is safe without a global
// lock.  Allocation paths are short critical regions protected by the
// single-core scheduling guarantee.

// SAFETY: single-core Cortex-M; only one FreeRTOS task executes at a time.
#[cfg(not(test))]
struct SharedHeapCell(core::cell::UnsafeCell<SharedJvmHeap>);
#[cfg(not(test))]
unsafe impl Sync for SharedHeapCell {}

#[cfg(not(test))]
static SHARED_HEAP: SharedHeapCell =
    SharedHeapCell(core::cell::UnsafeCell::new(SharedJvmHeap::new()));

/// Return a mutable reference to the process-wide shared JVM heap.
///
/// # Safety
/// Must only be called from FreeRTOS task context on the single core used by
/// picodroid (never from an ISR).  Alloc operations inside ObjectHeap and
/// ArrayHeap are short enough that a task switch mid-alloc cannot occur on
/// cooperative yield points (sleep / UART read).
#[cfg(not(test))]
pub fn shared_heap() -> &'static mut SharedJvmHeap {
    unsafe { &mut *SHARED_HEAP.0.get() }
}

// ── Class loader registration ─────────────────────────────────────────────────
//
// The `Thread.start()` native handler spawns a new FreeRTOS task that creates
// a fresh Jvm and must load all application classes before invoking Runnable.run().
// A universal loader function reads all classes directly from the embedded APK,
// so every app (including threaddemo) works without special-casing.

#[cfg(not(test))]
type ClassLoaderFn = fn(&mut Jvm) -> Result<(), JvmError>;

// SAFETY: single-core Cortex-M; only one FreeRTOS task executes at a time.
// register_class_loader() is called once from the JVM bootstrap task before
// any Thread.start() dispatch can occur.
#[cfg(not(test))]
struct ClassLoaderCell(core::cell::UnsafeCell<Option<ClassLoaderFn>>);
#[cfg(not(test))]
unsafe impl Sync for ClassLoaderCell {}

#[cfg(not(test))]
static CLASS_LOADER: ClassLoaderCell = ClassLoaderCell(core::cell::UnsafeCell::new(None));

#[cfg(not(test))]
#[allow(dead_code)]
pub fn register_class_loader(f: ClassLoaderFn) {
    unsafe { *CLASS_LOADER.0.get() = Some(f) }
}

#[cfg(not(test))]
#[cfg_attr(feature = "sim", allow(dead_code))]
pub fn load_classes(jvm: &mut Jvm) -> Result<(), JvmError> {
    unsafe {
        match *CLASS_LOADER.0.get() {
            Some(f) => f(jvm),
            None => Ok(()),
        }
    }
}

// ── APK-driven class loading ──────────────────────────────────────────────────

/// Loads all classes from the embedded APK into `jvm`.
///
/// Used both during initial JVM startup and by the `Thread.start()` native
/// handler when it spawns a fresh `Jvm` for a new thread.  Because `APK_DATA`
/// is `'static`, all `ClassEntry::data` slices are `&'static [u8]` and satisfy
/// the `Jvm::load_class` requirement without any copying.
#[cfg(not(test))]
fn load_classes_from_apk(jvm: &mut Jvm) -> Result<(), JvmError> {
    let apk = Papk::parse(APK_DATA).map_err(|_| JvmError::InvalidBytecode)?;
    for entry in apk.classes().map_err(|_| JvmError::InvalidBytecode)? {
        jvm.load_class(entry.data)?;
    }
    Ok(())
}

// ── run_jvm ───────────────────────────────────────────────────────────────────

#[cfg(not(test))]
pub fn run_jvm() {
    let mut jvm = Box::new(Jvm::new());
    let heap = shared_heap();
    let mut handler = crate::system::native_handler::PicodroidNativeHandler;

    // Register the universal class loader so Thread.start() spawned tasks
    // can load all APK classes into their fresh Jvm instances.
    register_class_loader(load_classes_from_apk);

    // Load all classes declared in the embedded APK.
    load_classes_from_apk(&mut jvm).unwrap();

    // Determine the entry point from the APK manifest.
    let apk = Papk::parse(APK_DATA).unwrap();
    let main_class = apk
        .main_class()
        .expect("APK manifest is missing 'main-class'");

    jvm.invoke_static(main_class, "main", heap, &mut handler)
        .unwrap();

    #[cfg(not(feature = "sim"))]
    loop {
        freertos_rust::CurrentTask::delay(freertos_rust::Duration::ms(60_000));
    }
}
