// SPDX-License-Identifier: GPL-3.0-only
#![cfg_attr(not(any(test, feature = "sim")), no_std)]
#![cfg_attr(not(any(test, feature = "sim")), no_main)]

extern crate alloc;

mod app;
// Active-board Rust glue. Generated by build.rs (empty no-op when no board
// is active). Only pulled in on hardware builds.
#[cfg(not(any(test, feature = "sim")))]
mod boards;
mod dispatch_sites;
#[allow(dead_code)]
mod drivers;
mod framework_classes;
#[allow(dead_code)]
#[cfg(not(test))]
mod fs;
#[allow(dead_code)]
mod hal;
#[cfg(not(test))]
mod lifecycle;
#[cfg(not(test))]
mod lvgl_ffi;
#[cfg(not(any(test, feature = "sim")))]
mod packagemanager;
#[cfg(not(any(test, feature = "sim")))]
mod pdb;
#[cfg(not(test))]
mod service_lifecycle;
mod shrink_names;
#[cfg(feature = "sim")]
mod sim_allocator;
mod system;
mod task_priority;

// Host-testable pure-logic slices of RP HAL drivers. The rest of `hal::rp`
// is ARM-only and cfg-gated out on the host; these modules have no
// `rp-pico`/`rp235x-hal` deps, so pulling them in directly via `#[path]`
// lets their `#[cfg(test)]` blocks run under `scripts/test.sh`.
#[cfg(test)]
#[path = "hal/rp/i2c/protocol.rs"]
mod hal_rp_i2c_protocol_tests;
#[cfg(test)]
#[path = "hal/rp/pdb_usb/protocol.rs"]
mod hal_rp_pdb_usb_protocol_tests;
#[cfg(test)]
#[path = "hal/rp/spi/protocol.rs"]
mod hal_rp_spi_protocol_tests;

// Family-rp hardware imports (Cortex-M-specific via cortex-m-rt + the
// generic-FreeRTOS rust bindings).
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use cortex_m::asm;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use cortex_m_rt::{entry, exception, ExceptionFrame};
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use defmt_rtt as _;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use freertos_rust::*;
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
use panic_probe as _;

// Family-esp hardware imports (Xtensa LX7 via xtensa-lx-rt).
// defmt global logger and panic handler are in src/hal/esp/boot.rs.
// Note: esp-hal is deferred until rp235x-hal bumps riscv-rt to ^0.16 (the
// current conflict makes them mutually exclusive in the same Cargo workspace).
#[cfg(all(not(any(test, feature = "sim")), feature = "family-esp"))]
use xtensa_lx_rt::entry;

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[global_allocator]
static GLOBAL: FreeRtosAllocator = FreeRtosAllocator;

#[cfg(feature = "sim")]
#[global_allocator]
static GLOBAL: sim_allocator::CappedAllocator = sim_allocator::CappedAllocator::new();

#[cfg(all(not(any(test, feature = "sim")), feature = "family-esp"))]
#[global_allocator]
static GLOBAL: embedded_alloc::LlffHeap = embedded_alloc::LlffHeap::empty();

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[entry]
fn main() -> ! {
    hal::boot::clock_init();

    let boot_apk: &'static [u8] =
        unsafe { hal::flash::read_flash_papk() }.expect("PAPK flash region invalid");

    // Mount LittleFS on the FS_FLASH region.  Runs pre-scheduler (single-core),
    // formats on first boot or after corruption.  A failure here is non-fatal
    // for the JVM — persistence simply remains unavailable until the next boot.
    if let Err(e) = fs::init() {
        defmt::warn!("[fs] init failed: {}", defmt::Display2Format(&e));
    }

    hal::boot::start_tasks(boot_apk)
}

// Static backing store for the ESP heap allocator.  256 KiB is intentionally
// conservative for the stub build; tune when FreeRTOS/PSRAM land (Milestone 3).
#[cfg(all(not(any(test, feature = "sim")), feature = "family-esp"))]
static mut ESP_HEAP: core::mem::MaybeUninit<[u8; 256 * 1024]> = core::mem::MaybeUninit::uninit();

#[cfg(all(not(any(test, feature = "sim")), feature = "family-esp"))]
#[entry]
fn main() -> ! {
    // Initialize heap allocator before any alloc usage.
    unsafe { GLOBAL.init(ESP_HEAP.as_mut_ptr() as usize, 256 * 1024) }

    hal::boot::clock_init();

    let boot_apk: &'static [u8] =
        unsafe { hal::flash::read_flash_papk() }.expect("PAPK flash region invalid");

    if let Err(_e) = fs::init() {
        // defmt has no transport yet on ESP; logging deferred to Milestone 2
    }

    hal::boot::start_tasks(boot_apk)
}

#[cfg(feature = "sim")]
fn main() {
    if let Err(e) = fs::init() {
        eprintln!("[sim][fs] init failed: {}", e);
    }

    app::run_jvm();

    let (current, peak, limit) = GLOBAL.heap_stats();
    if limit == usize::MAX {
        println!("[sim] heap: peak {} KB (unlimited)", peak / 1024);
    } else {
        println!(
            "[sim] heap: peak {} KB / {} KB limit ({} KB current)",
            peak / 1024,
            limit / 1024,
            current / 1024,
        );
    }
}

// Cortex-M exception handlers and FreeRTOS application hooks. These are
// family-rp-specific: cortex-m-rt's #[exception] machinery and the
// FreeRTOS-rust bindings only exist on this family. A future family-esp
// will provide its own panic / fault hooks under cfg(feature = "family-esp").
#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[exception]
unsafe fn DefaultHandler(_irqn: i16) {
    asm::bkpt();
    #[allow(clippy::empty_loop)]
    loop {}
}

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[exception]
unsafe fn HardFault(_ef: &ExceptionFrame) -> ! {
    // On RP2040 (Cortex-M0+) bkpt halts cleanly with a debugger attached.
    // On RP2350 (Cortex-M33) bkpt without a debugger causes a re-entrant
    // fault → lockup, so we skip it.
    #[cfg(not(feature = "chip-rp2350"))]
    asm::bkpt();
    #[allow(clippy::empty_loop)]
    loop {}
}

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[no_mangle]
fn vApplicationMallocFailedHook() {
    // Intentionally a no-op: pvPortMalloc returns NULL after this hook,
    // allowing Rust's try_reserve_exact to return Err and trigger GC.
    // Non-try allocations still abort via Rust's handle_alloc_error.
}

#[cfg(all(not(any(test, feature = "sim")), feature = "family-rp"))]
#[allow(non_snake_case)]
#[no_mangle]
fn vApplicationStackOverflowHook(_pxTask: FreeRtosTaskHandle, _pcTaskName: FreeRtosCharPtr) {
    asm::bkpt();
    #[allow(clippy::empty_loop)]
    loop {}
}
