// SPDX-License-Identifier: GPL-3.0-only
// Generated by protoc-gen-picodroid from demo.proto. DO NOT EDIT.
package protodemo.proto;

import java.io.IOException;
import java.util.Arrays;
import picodroid.protobuf.CodedInputStream;
import picodroid.protobuf.CodedOutputStream;
import picodroid.protobuf.InvalidProtocolBufferException;
import picodroid.protobuf.MessageLite;
import picodroid.protobuf.WireFormat;

/** The messages of {@code demo.proto}. */
public final class Demo {
  private Demo() {}

  /** The values of proto enum {@code Mood}; {@code int} constants, inlined by javac. */
  public static final class Mood {
    public static final int MOOD_UNSPECIFIED = 0;
    public static final int HAPPY = 1;
    public static final int GRUMPY = 2;

    private Mood() {}
  }

  /** Proto message {@code protodemo.Point}. */
  public static final class Point implements MessageLite {
    private int x_ = 0;
    private int y_ = 0;

    public Point() {}

    public int getX() {
      return x_;
    }

    public Point setX(int value) {
      x_ = value;
      return this;
    }

    public Point clearX() {
      x_ = 0;
      return this;
    }

    public int getY() {
      return y_;
    }

    public Point setY(int value) {
      y_ = value;
      return this;
    }

    public Point clearY() {
      y_ = 0;
      return this;
    }

    public static Point parseFrom(byte[] data) throws InvalidProtocolBufferException {
      return parseFrom(data, 0, data.length);
    }

    public static Point parseFrom(byte[] data, int off, int len)
        throws InvalidProtocolBufferException {
      return parseFrom(CodedInputStream.newInstance(data, off, len));
    }

    public static Point parseFrom(CodedInputStream input) throws InvalidProtocolBufferException {
      Point message = new Point();
      try {
        message.mergeFrom(input);
      } catch (InvalidProtocolBufferException e) {
        throw e;
      } catch (IOException e) {
        throw new InvalidProtocolBufferException(e.getMessage());
      }
      return message;
    }

    /** Reads fields from {@code input} until its end or limit, on top of what is set. */
    public Point mergeFrom(CodedInputStream input) throws IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          case 8:
            x_ = input.readSInt32();
            break;
          case 16:
            y_ = input.readSInt32();
            break;
          default:
            input.skipField(tag);
        }
      }
    }

    @Override
    public void writeTo(CodedOutputStream output) throws IOException {
      if (x_ != 0) {
        output.writeSInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeSInt32(2, y_);
      }
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (x_ != 0) {
        size += CodedOutputStream.computeSInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += CodedOutputStream.computeSInt32Size(2, y_);
      }
      return size;
    }

    @Override
    public byte[] toByteArray() {
      byte[] result = new byte[getSerializedSize()];
      try {
        CodedOutputStream output = CodedOutputStream.newInstance(result);
        writeTo(output);
        output.checkNoSpaceLeft();
      } catch (IOException e) {
        throw new RuntimeException(
            "Serializing to a byte array threw an IOException (should never happen).");
      }
      return result;
    }
  }

  /** Proto message {@code protodemo.Everything}. */
  public static final class Everything implements MessageLite {
    /** The values of proto enum {@code Kind}; {@code int} constants, inlined by javac. */
    public static final class Kind {
      public static final int KIND_UNSPECIFIED = 0;
      public static final int ROUND = 1;
      public static final int SQUARE = 7;

      private Kind() {}
    }

    /** Proto message {@code protodemo.Everything.Inner}. */
    public static final class Inner implements MessageLite {
      private String label_ = "";
      private Demo.Point[] corners_;
      private int cornersCount_;

      public Inner() {}

      public String getLabel() {
        return label_;
      }

      public Inner setLabel(String value) {
        if (value == null) {
          throw new NullPointerException("label");
        }
        label_ = value;
        return this;
      }

      public Inner clearLabel() {
        label_ = "";
        return this;
      }

      public int getCornersCount() {
        return cornersCount_;
      }

      public Demo.Point getCorners(int index) {
        if (index < 0 || index >= cornersCount_) {
          throw new IndexOutOfBoundsException(String.valueOf(index));
        }
        return corners_[index];
      }

      public Inner addCorners(Demo.Point value) {
        if (value == null) {
          throw new NullPointerException("corners");
        }
        if (corners_ == null || cornersCount_ == corners_.length) {
          int capacity = cornersCount_ == 0 ? 4 : cornersCount_ * 2;
          Demo.Point[] grown = new Demo.Point[capacity];
          if (corners_ != null) {
            System.arraycopy(corners_, 0, grown, 0, cornersCount_);
          }
          corners_ = grown;
        }
        corners_[cornersCount_++] = value;
        return this;
      }

      public Inner clearCorners() {
        corners_ = null;
        cornersCount_ = 0;
        return this;
      }

      public static Inner parseFrom(byte[] data) throws InvalidProtocolBufferException {
        return parseFrom(data, 0, data.length);
      }

      public static Inner parseFrom(byte[] data, int off, int len)
          throws InvalidProtocolBufferException {
        return parseFrom(CodedInputStream.newInstance(data, off, len));
      }

      public static Inner parseFrom(CodedInputStream input) throws InvalidProtocolBufferException {
        Inner message = new Inner();
        try {
          message.mergeFrom(input);
        } catch (InvalidProtocolBufferException e) {
          throw e;
        } catch (IOException e) {
          throw new InvalidProtocolBufferException(e.getMessage());
        }
        return message;
      }

      /** Reads fields from {@code input} until its end or limit, on top of what is set. */
      public Inner mergeFrom(CodedInputStream input) throws IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            case 10:
              label_ = input.readString();
              break;
            case 18:
              {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                Demo.Point value = new Demo.Point();
                value.mergeFrom(input);
                input.popLimit(limit);
                addCorners(value);
              }
              break;
            default:
              input.skipField(tag);
          }
        }
      }

      @Override
      public void writeTo(CodedOutputStream output) throws IOException {
        if (!label_.isEmpty()) {
          output.writeString(1, label_);
        }
        for (int i = 0; i < cornersCount_; i++) {
          output.writeMessage(2, corners_[i]);
        }
      }

      @Override
      public int getSerializedSize() {
        int size = 0;
        if (!label_.isEmpty()) {
          size += CodedOutputStream.computeStringSize(1, label_);
        }
        for (int i = 0; i < cornersCount_; i++) {
          size += CodedOutputStream.computeMessageSize(2, corners_[i]);
        }
        return size;
      }

      @Override
      public byte[] toByteArray() {
        byte[] result = new byte[getSerializedSize()];
        try {
          CodedOutputStream output = CodedOutputStream.newInstance(result);
          writeTo(output);
          output.checkNoSpaceLeft();
        } catch (IOException e) {
          throw new RuntimeException(
              "Serializing to a byte array threw an IOException (should never happen).");
        }
        return result;
      }
    }

    private static final byte[] EMPTY_BYTES = new byte[0];

    private double d_ = 0.0;
    private float f_ = 0.0f;
    private int i32_ = 0;
    private long i64_ = 0L;
    private int u32_ = 0;
    private long u64_ = 0L;
    private int s32_ = 0;
    private long s64_ = 0L;
    private int f32_ = 0;
    private long f64_ = 0L;
    private int sf32_ = 0;
    private long sf64_ = 0L;
    private boolean flag_ = false;
    private String name_ = "";
    private byte[] blob_ = EMPTY_BYTES;
    private int mood_ = 0;
    private int kind_ = 0;
    private Demo.Everything.Inner inner_;
    private int maybe_ = 0;
    private boolean hasMaybe_;
    private String maybeName_ = "";
    private boolean hasMaybeName_;
    private int[] counts_;
    private int countsCount_;
    private boolean[] flags_;
    private int flagsCount_;
    private String[] tags_;
    private int tagsCount_;
    private byte[][] blobs_;
    private int blobsCount_;
    private Demo.Point[] points_;
    private int pointsCount_;
    private int[] moods_;
    private int moodsCount_;
    private double[] weights_;
    private int weightsCount_;
    private int class__ = 0;
    private int twoWordsHere_ = 0;

    public Everything() {}

    public double getD() {
      return d_;
    }

    public Everything setD(double value) {
      d_ = value;
      return this;
    }

    public Everything clearD() {
      d_ = 0.0;
      return this;
    }

    public float getF() {
      return f_;
    }

    public Everything setF(float value) {
      f_ = value;
      return this;
    }

    public Everything clearF() {
      f_ = 0.0f;
      return this;
    }

    public int getI32() {
      return i32_;
    }

    public Everything setI32(int value) {
      i32_ = value;
      return this;
    }

    public Everything clearI32() {
      i32_ = 0;
      return this;
    }

    public long getI64() {
      return i64_;
    }

    public Everything setI64(long value) {
      i64_ = value;
      return this;
    }

    public Everything clearI64() {
      i64_ = 0L;
      return this;
    }

    public int getU32() {
      return u32_;
    }

    public Everything setU32(int value) {
      u32_ = value;
      return this;
    }

    public Everything clearU32() {
      u32_ = 0;
      return this;
    }

    public long getU64() {
      return u64_;
    }

    public Everything setU64(long value) {
      u64_ = value;
      return this;
    }

    public Everything clearU64() {
      u64_ = 0L;
      return this;
    }

    public int getS32() {
      return s32_;
    }

    public Everything setS32(int value) {
      s32_ = value;
      return this;
    }

    public Everything clearS32() {
      s32_ = 0;
      return this;
    }

    public long getS64() {
      return s64_;
    }

    public Everything setS64(long value) {
      s64_ = value;
      return this;
    }

    public Everything clearS64() {
      s64_ = 0L;
      return this;
    }

    public int getF32() {
      return f32_;
    }

    public Everything setF32(int value) {
      f32_ = value;
      return this;
    }

    public Everything clearF32() {
      f32_ = 0;
      return this;
    }

    public long getF64() {
      return f64_;
    }

    public Everything setF64(long value) {
      f64_ = value;
      return this;
    }

    public Everything clearF64() {
      f64_ = 0L;
      return this;
    }

    public int getSf32() {
      return sf32_;
    }

    public Everything setSf32(int value) {
      sf32_ = value;
      return this;
    }

    public Everything clearSf32() {
      sf32_ = 0;
      return this;
    }

    public long getSf64() {
      return sf64_;
    }

    public Everything setSf64(long value) {
      sf64_ = value;
      return this;
    }

    public Everything clearSf64() {
      sf64_ = 0L;
      return this;
    }

    public boolean getFlag() {
      return flag_;
    }

    public Everything setFlag(boolean value) {
      flag_ = value;
      return this;
    }

    public Everything clearFlag() {
      flag_ = false;
      return this;
    }

    public String getName() {
      return name_;
    }

    public Everything setName(String value) {
      if (value == null) {
        throw new NullPointerException("name");
      }
      name_ = value;
      return this;
    }

    public Everything clearName() {
      name_ = "";
      return this;
    }

    public byte[] getBlob() {
      return blob_;
    }

    public Everything setBlob(byte[] value) {
      if (value == null) {
        throw new NullPointerException("blob");
      }
      blob_ = value;
      return this;
    }

    public Everything clearBlob() {
      blob_ = EMPTY_BYTES;
      return this;
    }

    public int getMoodValue() {
      return mood_;
    }

    public Everything setMoodValue(int value) {
      mood_ = value;
      return this;
    }

    public Everything clearMood() {
      mood_ = 0;
      return this;
    }

    public int getKindValue() {
      return kind_;
    }

    public Everything setKindValue(int value) {
      kind_ = value;
      return this;
    }

    public Everything clearKind() {
      kind_ = 0;
      return this;
    }

    public boolean hasInner() {
      return inner_ != null;
    }

    public Demo.Everything.Inner getInner() {
      return inner_;
    }

    public Everything setInner(Demo.Everything.Inner value) {
      inner_ = value;
      return this;
    }

    public Everything clearInner() {
      inner_ = null;
      return this;
    }

    public boolean hasMaybe() {
      return hasMaybe_;
    }

    public int getMaybe() {
      return maybe_;
    }

    public Everything setMaybe(int value) {
      maybe_ = value;
      hasMaybe_ = true;
      return this;
    }

    public Everything clearMaybe() {
      maybe_ = 0;
      hasMaybe_ = false;
      return this;
    }

    public boolean hasMaybeName() {
      return hasMaybeName_;
    }

    public String getMaybeName() {
      return maybeName_;
    }

    public Everything setMaybeName(String value) {
      if (value == null) {
        throw new NullPointerException("maybe_name");
      }
      maybeName_ = value;
      hasMaybeName_ = true;
      return this;
    }

    public Everything clearMaybeName() {
      maybeName_ = "";
      hasMaybeName_ = false;
      return this;
    }

    public int getCountsCount() {
      return countsCount_;
    }

    public int getCounts(int index) {
      if (index < 0 || index >= countsCount_) {
        throw new IndexOutOfBoundsException(String.valueOf(index));
      }
      return counts_[index];
    }

    public Everything addCounts(int value) {
      if (counts_ == null || countsCount_ == counts_.length) {
        int capacity = countsCount_ == 0 ? 4 : countsCount_ * 2;
        counts_ = counts_ == null ? new int[capacity] : Arrays.copyOf(counts_, capacity);
      }
      counts_[countsCount_++] = value;
      return this;
    }

    public Everything clearCounts() {
      counts_ = null;
      countsCount_ = 0;
      return this;
    }

    public int getFlagsCount() {
      return flagsCount_;
    }

    public boolean getFlags(int index) {
      if (index < 0 || index >= flagsCount_) {
        throw new IndexOutOfBoundsException(String.valueOf(index));
      }
      return flags_[index];
    }

    public Everything addFlags(boolean value) {
      if (flags_ == null || flagsCount_ == flags_.length) {
        int capacity = flagsCount_ == 0 ? 4 : flagsCount_ * 2;
        boolean[] grown = new boolean[capacity];
        if (flags_ != null) {
          System.arraycopy(flags_, 0, grown, 0, flagsCount_);
        }
        flags_ = grown;
      }
      flags_[flagsCount_++] = value;
      return this;
    }

    public Everything clearFlags() {
      flags_ = null;
      flagsCount_ = 0;
      return this;
    }

    public int getTagsCount() {
      return tagsCount_;
    }

    public String getTags(int index) {
      if (index < 0 || index >= tagsCount_) {
        throw new IndexOutOfBoundsException(String.valueOf(index));
      }
      return tags_[index];
    }

    public Everything addTags(String value) {
      if (value == null) {
        throw new NullPointerException("tags");
      }
      if (tags_ == null || tagsCount_ == tags_.length) {
        int capacity = tagsCount_ == 0 ? 4 : tagsCount_ * 2;
        String[] grown = new String[capacity];
        if (tags_ != null) {
          System.arraycopy(tags_, 0, grown, 0, tagsCount_);
        }
        tags_ = grown;
      }
      tags_[tagsCount_++] = value;
      return this;
    }

    public Everything clearTags() {
      tags_ = null;
      tagsCount_ = 0;
      return this;
    }

    public int getBlobsCount() {
      return blobsCount_;
    }

    public byte[] getBlobs(int index) {
      if (index < 0 || index >= blobsCount_) {
        throw new IndexOutOfBoundsException(String.valueOf(index));
      }
      return blobs_[index];
    }

    public Everything addBlobs(byte[] value) {
      if (value == null) {
        throw new NullPointerException("blobs");
      }
      if (blobs_ == null || blobsCount_ == blobs_.length) {
        int capacity = blobsCount_ == 0 ? 4 : blobsCount_ * 2;
        byte[][] grown = new byte[capacity][];
        if (blobs_ != null) {
          System.arraycopy(blobs_, 0, grown, 0, blobsCount_);
        }
        blobs_ = grown;
      }
      blobs_[blobsCount_++] = value;
      return this;
    }

    public Everything clearBlobs() {
      blobs_ = null;
      blobsCount_ = 0;
      return this;
    }

    public int getPointsCount() {
      return pointsCount_;
    }

    public Demo.Point getPoints(int index) {
      if (index < 0 || index >= pointsCount_) {
        throw new IndexOutOfBoundsException(String.valueOf(index));
      }
      return points_[index];
    }

    public Everything addPoints(Demo.Point value) {
      if (value == null) {
        throw new NullPointerException("points");
      }
      if (points_ == null || pointsCount_ == points_.length) {
        int capacity = pointsCount_ == 0 ? 4 : pointsCount_ * 2;
        Demo.Point[] grown = new Demo.Point[capacity];
        if (points_ != null) {
          System.arraycopy(points_, 0, grown, 0, pointsCount_);
        }
        points_ = grown;
      }
      points_[pointsCount_++] = value;
      return this;
    }

    public Everything clearPoints() {
      points_ = null;
      pointsCount_ = 0;
      return this;
    }

    public int getMoodsCount() {
      return moodsCount_;
    }

    public int getMoodsValue(int index) {
      if (index < 0 || index >= moodsCount_) {
        throw new IndexOutOfBoundsException(String.valueOf(index));
      }
      return moods_[index];
    }

    public Everything addMoodsValue(int value) {
      if (moods_ == null || moodsCount_ == moods_.length) {
        int capacity = moodsCount_ == 0 ? 4 : moodsCount_ * 2;
        moods_ = moods_ == null ? new int[capacity] : Arrays.copyOf(moods_, capacity);
      }
      moods_[moodsCount_++] = value;
      return this;
    }

    public Everything clearMoods() {
      moods_ = null;
      moodsCount_ = 0;
      return this;
    }

    public int getWeightsCount() {
      return weightsCount_;
    }

    public double getWeights(int index) {
      if (index < 0 || index >= weightsCount_) {
        throw new IndexOutOfBoundsException(String.valueOf(index));
      }
      return weights_[index];
    }

    public Everything addWeights(double value) {
      if (weights_ == null || weightsCount_ == weights_.length) {
        int capacity = weightsCount_ == 0 ? 4 : weightsCount_ * 2;
        weights_ = weights_ == null ? new double[capacity] : Arrays.copyOf(weights_, capacity);
      }
      weights_[weightsCount_++] = value;
      return this;
    }

    public Everything clearWeights() {
      weights_ = null;
      weightsCount_ = 0;
      return this;
    }

    public int getClass_() {
      return class__;
    }

    public Everything setClass_(int value) {
      class__ = value;
      return this;
    }

    public Everything clearClass_() {
      class__ = 0;
      return this;
    }

    public int getTwoWordsHere() {
      return twoWordsHere_;
    }

    public Everything setTwoWordsHere(int value) {
      twoWordsHere_ = value;
      return this;
    }

    public Everything clearTwoWordsHere() {
      twoWordsHere_ = 0;
      return this;
    }

    public static Everything parseFrom(byte[] data) throws InvalidProtocolBufferException {
      return parseFrom(data, 0, data.length);
    }

    public static Everything parseFrom(byte[] data, int off, int len)
        throws InvalidProtocolBufferException {
      return parseFrom(CodedInputStream.newInstance(data, off, len));
    }

    public static Everything parseFrom(CodedInputStream input)
        throws InvalidProtocolBufferException {
      Everything message = new Everything();
      try {
        message.mergeFrom(input);
      } catch (InvalidProtocolBufferException e) {
        throw e;
      } catch (IOException e) {
        throw new InvalidProtocolBufferException(e.getMessage());
      }
      return message;
    }

    /** Reads fields from {@code input} until its end or limit, on top of what is set. */
    public Everything mergeFrom(CodedInputStream input) throws IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          case 9:
            d_ = input.readDouble();
            break;
          case 21:
            f_ = input.readFloat();
            break;
          case 24:
            i32_ = input.readInt32();
            break;
          case 32:
            i64_ = input.readInt64();
            break;
          case 40:
            u32_ = input.readUInt32();
            break;
          case 48:
            u64_ = input.readUInt64();
            break;
          case 56:
            s32_ = input.readSInt32();
            break;
          case 64:
            s64_ = input.readSInt64();
            break;
          case 77:
            f32_ = input.readFixed32();
            break;
          case 81:
            f64_ = input.readFixed64();
            break;
          case 93:
            sf32_ = input.readSFixed32();
            break;
          case 97:
            sf64_ = input.readSFixed64();
            break;
          case 104:
            flag_ = input.readBool();
            break;
          case 114:
            name_ = input.readString();
            break;
          case 122:
            blob_ = input.readBytes();
            break;
          case 128:
            mood_ = input.readEnum();
            break;
          case 136:
            kind_ = input.readEnum();
            break;
          case 146:
            {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              Demo.Everything.Inner value = new Demo.Everything.Inner();
              value.mergeFrom(input);
              input.popLimit(limit);
              inner_ = value;
            }
            break;
          case 152:
            maybe_ = input.readInt32();
            hasMaybe_ = true;
            break;
          case 162:
            maybeName_ = input.readString();
            hasMaybeName_ = true;
            break;
          case 168:
            addCounts(input.readInt32());
            break;
          case 170:
            {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addCounts(input.readInt32());
              }
              input.popLimit(limit);
            }
            break;
          case 176:
            addFlags(input.readBool());
            break;
          case 178:
            {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addFlags(input.readBool());
              }
              input.popLimit(limit);
            }
            break;
          case 186:
            addTags(input.readString());
            break;
          case 194:
            addBlobs(input.readBytes());
            break;
          case 202:
            {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              Demo.Point value = new Demo.Point();
              value.mergeFrom(input);
              input.popLimit(limit);
              addPoints(value);
            }
            break;
          case 208:
            addMoodsValue(input.readEnum());
            break;
          case 210:
            {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addMoodsValue(input.readEnum());
              }
              input.popLimit(limit);
            }
            break;
          case 217:
            addWeights(input.readDouble());
            break;
          case 218:
            {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addWeights(input.readDouble());
              }
              input.popLimit(limit);
            }
            break;
          case 224:
            class__ = input.readInt32();
            break;
          case 232:
            twoWordsHere_ = input.readInt32();
            break;
          default:
            input.skipField(tag);
        }
      }
    }

    @Override
    public void writeTo(CodedOutputStream output) throws IOException {
      if (d_ != 0.0) {
        output.writeDouble(1, d_);
      }
      if (f_ != 0.0f) {
        output.writeFloat(2, f_);
      }
      if (i32_ != 0) {
        output.writeInt32(3, i32_);
      }
      if (i64_ != 0L) {
        output.writeInt64(4, i64_);
      }
      if (u32_ != 0) {
        output.writeUInt32(5, u32_);
      }
      if (u64_ != 0L) {
        output.writeUInt64(6, u64_);
      }
      if (s32_ != 0) {
        output.writeSInt32(7, s32_);
      }
      if (s64_ != 0L) {
        output.writeSInt64(8, s64_);
      }
      if (f32_ != 0) {
        output.writeFixed32(9, f32_);
      }
      if (f64_ != 0L) {
        output.writeFixed64(10, f64_);
      }
      if (sf32_ != 0) {
        output.writeSFixed32(11, sf32_);
      }
      if (sf64_ != 0L) {
        output.writeSFixed64(12, sf64_);
      }
      if (flag_) {
        output.writeBool(13, flag_);
      }
      if (!name_.isEmpty()) {
        output.writeString(14, name_);
      }
      if (blob_.length != 0) {
        output.writeBytes(15, blob_);
      }
      if (mood_ != 0) {
        output.writeEnum(16, mood_);
      }
      if (kind_ != 0) {
        output.writeEnum(17, kind_);
      }
      if (inner_ != null) {
        output.writeMessage(18, inner_);
      }
      if (hasMaybe_) {
        output.writeInt32(19, maybe_);
      }
      if (hasMaybeName_) {
        output.writeString(20, maybeName_);
      }
      if (countsCount_ > 0) {
        output.writeTag(21, WireFormat.WIRETYPE_LENGTH_DELIMITED);
        output.writeUInt32NoTag(packedCountsSize());
        for (int i = 0; i < countsCount_; i++) {
          output.writeInt32NoTag(counts_[i]);
        }
      }
      if (flagsCount_ > 0) {
        output.writeTag(22, WireFormat.WIRETYPE_LENGTH_DELIMITED);
        output.writeUInt32NoTag(packedFlagsSize());
        for (int i = 0; i < flagsCount_; i++) {
          output.writeBoolNoTag(flags_[i]);
        }
      }
      for (int i = 0; i < tagsCount_; i++) {
        output.writeString(23, tags_[i]);
      }
      for (int i = 0; i < blobsCount_; i++) {
        output.writeBytes(24, blobs_[i]);
      }
      for (int i = 0; i < pointsCount_; i++) {
        output.writeMessage(25, points_[i]);
      }
      if (moodsCount_ > 0) {
        output.writeTag(26, WireFormat.WIRETYPE_LENGTH_DELIMITED);
        output.writeUInt32NoTag(packedMoodsValueSize());
        for (int i = 0; i < moodsCount_; i++) {
          output.writeEnumNoTag(moods_[i]);
        }
      }
      if (weightsCount_ > 0) {
        output.writeTag(27, WireFormat.WIRETYPE_LENGTH_DELIMITED);
        output.writeUInt32NoTag(packedWeightsSize());
        for (int i = 0; i < weightsCount_; i++) {
          output.writeDoubleNoTag(weights_[i]);
        }
      }
      if (class__ != 0) {
        output.writeInt32(28, class__);
      }
      if (twoWordsHere_ != 0) {
        output.writeInt32(29, twoWordsHere_);
      }
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (d_ != 0.0) {
        size += CodedOutputStream.computeDoubleSize(1, d_);
      }
      if (f_ != 0.0f) {
        size += CodedOutputStream.computeFloatSize(2, f_);
      }
      if (i32_ != 0) {
        size += CodedOutputStream.computeInt32Size(3, i32_);
      }
      if (i64_ != 0L) {
        size += CodedOutputStream.computeInt64Size(4, i64_);
      }
      if (u32_ != 0) {
        size += CodedOutputStream.computeUInt32Size(5, u32_);
      }
      if (u64_ != 0L) {
        size += CodedOutputStream.computeUInt64Size(6, u64_);
      }
      if (s32_ != 0) {
        size += CodedOutputStream.computeSInt32Size(7, s32_);
      }
      if (s64_ != 0L) {
        size += CodedOutputStream.computeSInt64Size(8, s64_);
      }
      if (f32_ != 0) {
        size += CodedOutputStream.computeFixed32Size(9, f32_);
      }
      if (f64_ != 0L) {
        size += CodedOutputStream.computeFixed64Size(10, f64_);
      }
      if (sf32_ != 0) {
        size += CodedOutputStream.computeSFixed32Size(11, sf32_);
      }
      if (sf64_ != 0L) {
        size += CodedOutputStream.computeSFixed64Size(12, sf64_);
      }
      if (flag_) {
        size += CodedOutputStream.computeBoolSize(13, flag_);
      }
      if (!name_.isEmpty()) {
        size += CodedOutputStream.computeStringSize(14, name_);
      }
      if (blob_.length != 0) {
        size += CodedOutputStream.computeBytesSize(15, blob_);
      }
      if (mood_ != 0) {
        size += CodedOutputStream.computeEnumSize(16, mood_);
      }
      if (kind_ != 0) {
        size += CodedOutputStream.computeEnumSize(17, kind_);
      }
      if (inner_ != null) {
        size += CodedOutputStream.computeMessageSize(18, inner_);
      }
      if (hasMaybe_) {
        size += CodedOutputStream.computeInt32Size(19, maybe_);
      }
      if (hasMaybeName_) {
        size += CodedOutputStream.computeStringSize(20, maybeName_);
      }
      if (countsCount_ > 0) {
        int packed = packedCountsSize();
        size +=
            CodedOutputStream.computeTagSize(21)
                + CodedOutputStream.computeUInt32SizeNoTag(packed)
                + packed;
      }
      if (flagsCount_ > 0) {
        int packed = packedFlagsSize();
        size +=
            CodedOutputStream.computeTagSize(22)
                + CodedOutputStream.computeUInt32SizeNoTag(packed)
                + packed;
      }
      for (int i = 0; i < tagsCount_; i++) {
        size += CodedOutputStream.computeStringSize(23, tags_[i]);
      }
      for (int i = 0; i < blobsCount_; i++) {
        size += CodedOutputStream.computeBytesSize(24, blobs_[i]);
      }
      for (int i = 0; i < pointsCount_; i++) {
        size += CodedOutputStream.computeMessageSize(25, points_[i]);
      }
      if (moodsCount_ > 0) {
        int packed = packedMoodsValueSize();
        size +=
            CodedOutputStream.computeTagSize(26)
                + CodedOutputStream.computeUInt32SizeNoTag(packed)
                + packed;
      }
      if (weightsCount_ > 0) {
        int packed = packedWeightsSize();
        size +=
            CodedOutputStream.computeTagSize(27)
                + CodedOutputStream.computeUInt32SizeNoTag(packed)
                + packed;
      }
      if (class__ != 0) {
        size += CodedOutputStream.computeInt32Size(28, class__);
      }
      if (twoWordsHere_ != 0) {
        size += CodedOutputStream.computeInt32Size(29, twoWordsHere_);
      }
      return size;
    }

    private int packedCountsSize() {
      int size = 0;
      for (int i = 0; i < countsCount_; i++) {
        size += CodedOutputStream.computeInt32SizeNoTag(counts_[i]);
      }
      return size;
    }

    private int packedFlagsSize() {
      int size = 0;
      for (int i = 0; i < flagsCount_; i++) {
        size += CodedOutputStream.computeBoolSizeNoTag(flags_[i]);
      }
      return size;
    }

    private int packedMoodsValueSize() {
      int size = 0;
      for (int i = 0; i < moodsCount_; i++) {
        size += CodedOutputStream.computeEnumSizeNoTag(moods_[i]);
      }
      return size;
    }

    private int packedWeightsSize() {
      int size = 0;
      for (int i = 0; i < weightsCount_; i++) {
        size += CodedOutputStream.computeDoubleSizeNoTag(weights_[i]);
      }
      return size;
    }

    @Override
    public byte[] toByteArray() {
      byte[] result = new byte[getSerializedSize()];
      try {
        CodedOutputStream output = CodedOutputStream.newInstance(result);
        writeTo(output);
        output.checkNoSpaceLeft();
      } catch (IOException e) {
        throw new RuntimeException(
            "Serializing to a byte array threw an IOException (should never happen).");
      }
      return result;
    }
  }
}
