// SPDX-License-Identifier: GPL-3.0-only
//! Java class, member and descriptor names as the loaded framework spells
//! them — `c::java_lang_String`, `m::toString`, `d::String__V`.
//!
//! Generated by `jvm/build.rs` (`build_support/names.rs`) from the committed
//! `sdk/*.tsv` lists, through the active shrink map when the build runs
//! with `PICODROID_SHRINK=1`. A no-shrink build compiles every const to the
//! original literal; a shrink build compiles it to the map's target, so the
//! JVM's tables, `catch` matching, `instanceof`, native dispatch and
//! `Class.getName()` all see one spelling and nothing is translated at run
//! time. Rust code in this crate never spells one of these names as a string
//! literal (picodroid-core's `no_original_name_literals` test scans this
//! crate too).
//!
//! `SHRINK_ACTIVE` says whether the loaded spelling differs; the
//! `#[cfg(test)]` reverse translators exist for tests that compare loaded
//! names against original-name tables.

include!(concat!(env!("OUT_DIR"), "/names.rs"));

/// Respell a hand-assembled test fixture the way the active map would have:
/// every constant-pool `Utf8` that is an original class name, a descriptor
/// naming one, or a renamed member becomes its loaded spelling. Identity in
/// a no-shrink build and for anything the map does not touch; malformed
/// input is returned unchanged so error-path tests keep their fixtures.
/// Only the constant pool is rewritten — nothing after it holds a byte
/// offset into it — so `Code`, indices and attribute lengths stay valid.
#[cfg(test)]
pub fn spelled(bytes: &'static [u8]) -> &'static [u8] {
    use alloc::vec::Vec;
    if !SHRINK_ACTIVE || bytes.len() < 10 {
        return bytes;
    }
    fn u16at(b: &[u8], i: usize) -> Option<u16> {
        Some(u16::from_be_bytes([*b.get(i)?, *b.get(i + 1)?]))
    }
    fn respell(s: &[u8]) -> Option<Vec<u8>> {
        let text = core::str::from_utf8(s).ok()?;
        if let Some((_, to)) = CLASS_PAIRS
            .iter()
            .find(|(from, to)| *from == text && from != to)
        {
            return Some(to.as_bytes().to_vec());
        }
        if let Some((_, to)) = MEMBER_PAIRS.iter().find(|(from, _)| *from == text) {
            return Some(to.as_bytes().to_vec());
        }
        if text.contains('L') && text.contains(';') {
            let out = unshrink_descriptor_inverse(text);
            if out != text {
                return Some(out.into_bytes());
            }
        }
        None
    }
    // Forward-rewrite the `L…;` segments of a descriptor.
    fn unshrink_descriptor_inverse(desc: &str) -> alloc::string::String {
        let mut out = alloc::string::String::with_capacity(desc.len());
        let mut rest = desc;
        while let Some(pos) = rest.find('L') {
            let (head, tail) = rest.split_at(pos);
            out.push_str(head);
            let Some(end) = tail.find(';') else {
                out.push_str(tail);
                return out;
            };
            out.push('L');
            out.push_str(shrink_class(&tail[1..end]));
            out.push(';');
            rest = &tail[end + 1..];
        }
        out.push_str(rest);
        out
    }
    let Some(cp_count) = u16at(bytes, 8) else {
        return bytes;
    };
    // Pass 1: which Utf8 slots are `ldc` string constants. The ASM remap
    // rebuilds the pool and leaves string literals alone, so a fixture's
    // `"run"` string must survive even though `run` the method renames.
    let mut string_slots: Vec<u16> = Vec::new();
    {
        let mut i = 1usize;
        let mut pos = 10usize;
        while i < cp_count as usize {
            let Some(&tag) = bytes.get(pos) else {
                return bytes;
            };
            let size = match tag {
                1 => 3 + u16at(bytes, pos + 1).map_or(0, |l| l as usize),
                3 | 4 | 9 | 10 | 11 | 12 | 17 | 18 => 5,
                5 | 6 => 9,
                7 | 8 | 16 | 19 | 20 => 3,
                15 => 4,
                _ => return bytes,
            };
            if tag == 8 {
                if let Some(idx) = u16at(bytes, pos + 1) {
                    string_slots.push(idx);
                }
            }
            pos += size;
            i += if matches!(tag, 5 | 6) { 2 } else { 1 };
        }
    }
    let mut out: Vec<u8> = bytes[..10].to_vec();
    let mut i = 1usize;
    let mut pos = 10usize;
    let mut changed = false;
    while i < cp_count as usize {
        let Some(&tag) = bytes.get(pos) else {
            return bytes;
        };
        let size = match tag {
            1 => {
                let Some(len) = u16at(bytes, pos + 1) else {
                    return bytes;
                };
                let Some(payload) = bytes.get(pos + 3..pos + 3 + len as usize) else {
                    return bytes;
                };
                out.push(1);
                let keep = string_slots.contains(&(i as u16));
                match if keep { None } else { respell(payload) } {
                    Some(new) => {
                        out.extend_from_slice(&(new.len() as u16).to_be_bytes());
                        out.extend_from_slice(&new);
                        changed = true;
                    }
                    None => {
                        out.extend_from_slice(&bytes[pos + 1..pos + 3 + len as usize]);
                    }
                }
                pos += 3 + len as usize;
                i += 1;
                continue;
            }
            3 | 4 | 9 | 10 | 11 | 12 | 17 | 18 => 5,
            5 | 6 => 9,
            7 | 8 | 16 | 19 | 20 => 3,
            15 => 4,
            _ => return bytes,
        };
        let Some(entry) = bytes.get(pos..pos + size) else {
            return bytes;
        };
        out.extend_from_slice(entry);
        pos += size;
        i += if matches!(tag, 5 | 6) { 2 } else { 1 };
    }
    if !changed {
        return bytes;
    }
    out.extend_from_slice(&bytes[pos..]);
    alloc::boxed::Box::leak(out.into_boxed_slice())
}
