// SPDX-License-Identifier: GPL-3.0-only
//! LVGL C sources compilation.

use crate::config::collect_files;
use std::collections::HashMap;
use std::path::Path;

/// Compiled alongside LVGL to pin the C enum ABI the Rust FFI assumes.
///
/// `lvgl_ffi.rs` types LVGL's enums as `u8`, which only holds while the C
/// compiler is applying `-fshort-enums`. The static assert turns a lost flag
/// into a build error; the exported size lets `lvgl_ffi`'s test compare C's
/// real struct layout against the Rust mirror (see `abi_tests`).
const ENUM_ABI_CHECK_C: &str = r#"/* Generated by build_support/lvgl.rs — do not edit. */
#include "lvgl.h"

_Static_assert(sizeof(lv_indev_state_t) == 1,
    "LVGL C enums are wider than 1 byte: -fshort-enums is not in effect, but "
    "lvgl_ffi.rs types these enums as u8. Struct layouts would silently diverge.");

const unsigned int pd_c_sizeof_lv_indev_data = sizeof(lv_indev_data_t);
"#;

/// Compile LVGL C sources into a static library.
///
/// `repo_root` must be the absolute path to the repository root so that
/// `vendor/lvgl` and `lv_conf.h` can be located regardless of which
/// `platforms/<family>/` directory the build.rs runs from.
pub fn build(out: &Path, board_cfg: &Option<HashMap<String, String>>, repo_root: &Path) {
    let lvgl_src = repo_root.join("vendor/lvgl/src");
    if !lvgl_src.exists() {
        return;
    }

    let c_files = collect_files(&lvgl_src, "c");
    if c_files.is_empty() {
        return;
    }

    // Filter out stdlib backends we don't use (clib, micropython, rtthread),
    // GPU backends we disabled, and driver files (we use our own HAL).
    let c_files: Vec<_> = c_files
        .into_iter()
        .filter(|p| {
            let s = p.to_string_lossy();
            !s.contains("stdlib/clib")
                && !s.contains("stdlib/micropython")
                && !s.contains("stdlib/rtthread")
                && !s.contains("draw/vg_lite")
                && !s.contains("draw/nxp")
                && !s.contains("draw/sdl")
                && !s.contains("draw/renesas")
                && !s.contains("draw/opengles")
                && !s.contains("libs/thorvg")
                && !s.contains("others/vg_lite_tvg")
                && !s.contains("/drivers/")
        })
        .collect();

    let lvgl_dir = repo_root.join("vendor/lvgl");
    let mut build = cc::Build::new();
    build
        .include(repo_root)
        .include(&lvgl_dir)
        .include(&lvgl_src)
        .define("LV_CONF_INCLUDE_SIMPLE", None)
        .define("LV_LVGL_H_INCLUDE_SIMPLE", None)
        .warnings(false)
        .extra_warnings(false);

    // Board-specific LVGL overrides (take precedence over lv_conf.h via #ifndef guards).
    if let Some(cfg) = board_cfg {
        if let Some(dpi) = cfg.get("lv_dpi") {
            build.define("LV_DPI_DEF", dpi.as_str());
        }
        if let Some(mem_kb) = cfg.get("lv_mem_kb") {
            let mem_val = format!("({mem_kb} * 1024U)");
            build.define("LV_MEM_SIZE", mem_val.as_str());
        }
    }

    // C enums must be 1 byte when their values fit: lvgl_ffi.rs mirrors them
    // with u8 typedefs, and a wider enum silently moves struct fields (e.g.
    // lv_indev_data_t.state lands at the wrong offset).  Short enums are the
    // bare-metal ARM EABI default but *not* an ARM default — the 32-bit
    // simulator lane's arm-linux-gnueabihf-gcc follows the GNU/Linux ABI and
    // uses 4-byte enums, as does x86_64.  Pass the flag everywhere; where it
    // is already the default it changes nothing, so device objects are
    // unaffected.  `enum_abi_check.c` below makes a violation a build error
    // rather than a silent layout bug.
    build.flag("-fshort-enums");

    for f in &c_files {
        build.file(f);
    }

    let abi_check = out.join("enum_abi_check.c");
    std::fs::write(&abi_check, ENUM_ABI_CHECK_C).expect("write enum_abi_check.c");
    build.file(&abi_check);

    build.compile("lvgl");

    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("lv_conf.h").display()
    );
    println!("cargo:rerun-if-changed={}", lvgl_src.display());
}
