// SPDX-License-Identifier: GPL-3.0-only
//! APK + framework class embedding; PAPK flash-init section generation.

use crate::config::collect_files;
use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Emit `framework_mapping_version.rs` into `out` declaring the active
/// shrink-map version. Resolves by reading the root `Cargo.toml` version
/// and picking the highest committed `sdk/shrink-maps/v<semver>.toml`
/// whose semver is ≤ that version; falls back to `"0.0.0"` (sentinel
/// meaning "no shrinking") when no map has been cut yet.
///
/// `root` is the repo root directory (where `Cargo.toml` and `sdk/` live).
/// The emitted file exposes `FRAMEWORK_MAP_VERSION: &str`, included by
/// the firmware crate so that `verify_compat` at PAPK load time can
/// reject mismatched apps.
pub fn emit_framework_map_version(out: &Path, root: &Path) {
    // Shrinking is opt-in. Without PICODROID_SHRINK=1 we emit the `0.0.0`
    // sentinel so nothing else in the pipeline touches framework .class
    // bytes — matching Android's "R8 off by default" behavior.
    println!("cargo:rerun-if-env-changed=PICODROID_SHRINK");

    let active = if shrink_enabled() {
        // The root Cargo.toml is now a virtual workspace; the picodroid package
        // version lives in platforms/rp/Cargo.toml.
        let cargo_toml = {
            let rp = root.join("platforms/rp/Cargo.toml");
            if rp.exists() {
                rp
            } else {
                root.join("Cargo.toml")
            }
        };
        let shrink_maps_dir = root.join("sdk").join("shrink-maps");

        println!("cargo:rerun-if-changed={}", cargo_toml.display());
        println!("cargo:rerun-if-changed={}", shrink_maps_dir.display());

        let pkg_version = read_package_version(&cargo_toml)
            .unwrap_or_else(|e| panic!("failed to read picodroid version: {e}"));
        resolve_active_map_version(&pkg_version, &shrink_maps_dir)
    } else {
        "0.0.0".to_string()
    };

    let content = format!(
        "/// Shrink-map version active for this firmware build. Generated by build.rs.\n\
         pub const FRAMEWORK_MAP_VERSION: &str = {active:?};\n"
    );
    fs::write(out.join("framework_mapping_version.rs"), content)
        .unwrap_or_else(|e| panic!("cannot write framework_mapping_version.rs: {e}"));
}

/// The active shrink map, or `None` when shrinking is off or no map covers
/// the package version. Same resolution as [`apply_active_shrink`].
pub fn active_shrink_map(root: &Path) -> Option<class_shrink::mapping::ShrinkMap> {
    let map_path = active_shrink_map_path(root)?;
    Some(
        class_shrink::mapping::ShrinkMap::load(&map_path)
            .unwrap_or_else(|e| panic!("failed to load {}: {e}", map_path.display())),
    )
}

/// Path of the active shrink map file, if any (see [`active_shrink_map`]).
fn active_shrink_map_path(root: &Path) -> Option<PathBuf> {
    if !shrink_enabled() {
        return None;
    }
    let shrink_maps_dir = root.join("sdk").join("shrink-maps");
    let cargo_toml = {
        let rp = root.join("platforms/rp/Cargo.toml");
        if rp.exists() {
            rp
        } else {
            root.join("Cargo.toml")
        }
    };
    let pkg_version = read_package_version(&cargo_toml).ok()?;
    let active = resolve_active_map_version(&pkg_version, &shrink_maps_dir);
    if active == "0.0.0" {
        return None;
    }
    Some(shrink_maps_dir.join(format!("v{active}.toml")))
}

/// Shrinking is gated on the `PICODROID_SHRINK=1` env var — set by the
/// `--shrink` flag on top-level scripts (build.sh / flash.sh / sim.sh /
/// build-apk.sh). Any value other than `"1"` (including unset) is off.
pub fn shrink_enabled() -> bool {
    matches!(env::var("PICODROID_SHRINK").as_deref(), Ok("1"))
}

/// Lightweight semver tuple parser — returns `None` on malformed input.
/// Pre-release suffixes (`-rc1`, `+build`) are stripped before comparison.
fn parse_semver(s: &str) -> Option<(u32, u32, u32)> {
    let core = s.split(['-', '+']).next().unwrap_or(s);
    let mut it = core.split('.');
    let major = it.next()?.parse().ok()?;
    let minor = it.next()?.parse().ok()?;
    let patch = it.next()?.parse().ok()?;
    if it.next().is_some() {
        return None;
    }
    Some((major, minor, patch))
}

/// Naive `[package] version = "x.y.z"` extractor to avoid a toml crate
/// dependency in the build script.
fn read_package_version(cargo_toml: &Path) -> Result<String, String> {
    let text = fs::read_to_string(cargo_toml)
        .map_err(|e| format!("failed to read {}: {e}", cargo_toml.display()))?;
    let mut in_package = false;
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_package = trimmed == "[package]";
            continue;
        }
        if !in_package {
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("version") {
            let rest = rest.trim_start().trim_start_matches('=').trim();
            let v = rest.trim_matches(|c| c == '"' || c == '\'');
            if parse_semver(v).is_some() {
                return Ok(v.to_string());
            }
        }
    }
    Err(format!(
        "no [package] version found in {}",
        cargo_toml.display()
    ))
}

fn resolve_active_map_version(pkg_version: &str, shrink_maps_dir: &Path) -> String {
    const UNRELEASED: &str = "0.0.0";
    let Some(pkg) = parse_semver(pkg_version) else {
        return UNRELEASED.to_string();
    };
    let entries = match fs::read_dir(shrink_maps_dir) {
        Ok(e) => e,
        Err(_) => return UNRELEASED.to_string(),
    };
    let mut committed: Vec<(String, (u32, u32, u32))> = Vec::new();
    for entry in entries.flatten() {
        let Some(name) = entry.file_name().to_str().map(|s| s.to_string()) else {
            continue;
        };
        let Some(stem) = name.strip_prefix('v').and_then(|s| s.strip_suffix(".toml")) else {
            continue;
        };
        if let Some(sv) = parse_semver(stem) {
            committed.push((stem.to_string(), sv));
        }
    }
    committed.sort_by_key(|(_, sv)| *sv);
    committed
        .into_iter()
        .rfind(|(_, sv)| *sv <= pkg)
        .map(|(v, _)| v)
        .unwrap_or_else(|| UNRELEASED.to_string())
}

/// Compile the picodroid framework Java sources through Gradle, optionally
/// apply the active shrink map, and embed each `.class` file as a
/// `&'static [u8]` into `framework_classes.rs`. Firmware built with
/// `debug_assertions` off (every device build) embeds `:sdk:stripClasses`'
/// output — the classes without `LineNumberTable` / `SourceFile` /
/// `StackMapTable`, which that JVM never reads — and the generated file says
/// so in `FRAMEWORK_CLASSES_DEBUG_STRIPPED`; see the gate below.
///
/// `root` is the repo root directory (where `gradlew`, `sdk/`, etc. live).
/// Shrinking is only triggered when [`resolve_active_map_version`] returns
/// a version other than the `"0.0.0"` sentinel *and* a matching map file
/// exists. The Rust side names classes through the `c::` consts
/// `build_support/names.rs` generates from the same map (see
/// `picodroid-core/build.rs::emit_names`), so nothing translates at run time.
///
/// `excludes` are JVM internal class names (`picodroid/json/JSONObject`) the
/// active board opts out of, from its `framework_class_excludes` key. The
/// whole SDK is otherwise embedded on every board and loaded at boot, so a
/// new class costs its full `.class` size in flash everywhere — which the
/// RP2040's near-full program region cannot absorb. Excluding a name also
/// excludes its inner classes (`Foo$Builder` goes with `Foo`). The emitted
/// `FRAMEWORK_EXCLUDED_CLASSES` names what was dropped so a miss can say so
/// instead of surfacing as a bare NoClassDefFound.
pub fn embed_framework_classes(out: &Path, root: &Path, excludes: &[String]) {
    // The empty/full cutover is keyed on PICODROID_APK_PATH (only embedded
    // builds set it). Without this directive, a `cargo build` without the
    // var caches the empty table, and the subsequent `flash.sh` build (which
    // does set the var) reuses that cache and silently boots with no
    // framework classes — every Java app then dies with NoSuchMethod the
    // moment it touches Intent / StringBuilder / etc.
    println!("cargo:rerun-if-env-changed=PICODROID_APK_PATH");
    if env::var("PICODROID_APK_PATH").is_err() {
        fs::write(
            out.join("framework_classes.rs"),
            b"pub static FRAMEWORK_CLASSES: &[&[u8]] = &[];\npub static FRAMEWORK_EXCLUDED_CLASSES: &[&str] = &[];\npub const FRAMEWORK_CLASSES_DEBUG_STRIPPED: bool = false;\n",
        )
        .unwrap();
        return;
    }

    let framework_dir = root.join("sdk/java");
    let java_files = collect_files(&framework_dir, "java");
    for f in &java_files {
        println!("cargo:rerun-if-changed={}", f.display());
    }
    // The Gradle build config itself is an input — changes to how :sdk is
    // configured must re-trigger class regeneration. Track buildSrc by its
    // sources only: the whole directory would include buildSrc/build and
    // buildSrc/.gradle, which the `:sdk:compileJava` invocation below itself
    // touches — making every subsequent cargo build see a stale fingerprint
    // and recompile this crate forever.
    for p in [
        "settings.gradle.kts",
        "build.gradle.kts",
        "sdk/build.gradle.kts",
        "buildSrc/build.gradle.kts",
        "buildSrc/src",
    ] {
        println!("cargo:rerun-if-changed={}", root.join(p).display());
    }

    let gradlew = root.join(if cfg!(windows) {
        "gradlew.bat"
    } else {
        "gradlew"
    });
    // Device firmware compiles with debug_assertions off in both profiles
    // (scripts/lib.sh build_firmware), which compiles out the JVM's only
    // LineNumberTable reader (jvm/src/class_file/parse.rs, under
    // `#[cfg(debug_assertions)]`); SourceFile and StackMapTable have no reader
    // at all. Embed the tree `:sdk:stripClasses` writes without them (~14 KB
    // of flash on every board, docs/designs/flash-string-budget-2026-08.md §4)
    // and keep compileJava's raw tree for debug_assertions builds — the sim,
    // whose stack traces resolve `(:line)` from it. CARGO_CFG_DEBUG_ASSERTIONS
    // is the exact gate: it tracks the `--config profile.dev.debug-assertions`
    // override (DEBUG and PROFILE do not) and is part of cargo's build-script
    // fingerprint, so no rerun-if-env-changed is needed. Cargo sets it to the
    // empty string when on, hence the presence test.
    let strip_debug = env::var_os("CARGO_CFG_DEBUG_ASSERTIONS").is_none();
    // With a member-shrinking map active, embed the tree the ASM
    // `ShrinkMembersTask` wrote on top of that choice (member names renamed,
    // class names still original — `apply_active_shrink` renames those next).
    // The map path travels as a -P property: a warm Gradle daemon's
    // environment is frozen, so env would silently go stale.
    let member_map = active_shrink_map(root).filter(|m| m.has_members());
    let mut gradle_args: Vec<String> = Vec::new();
    let (gradle_task, classes_dir) = match (strip_debug, &member_map) {
        (true, None) => (
            ":sdk:stripClasses",
            root.join("sdk/build/classes-stripped/java/main"),
        ),
        (false, None) => (":sdk:compileJava", root.join("sdk/build/classes/java/main")),
        (true, Some(_)) => (
            ":sdk:shrinkMembersStripped",
            root.join("sdk/build/classes-members-stripped/java/main"),
        ),
        (false, Some(_)) => (
            ":sdk:shrinkMembersRaw",
            root.join("sdk/build/classes-members-raw/java/main"),
        ),
    };
    if member_map.is_some() {
        let map_path = active_shrink_map_path(root).expect("member map has a path");
        println!("cargo:rerun-if-changed={}", map_path.display());
        gradle_args.push(format!("-Ppicodroid.shrinkMap={}", map_path.display()));
    }
    let status = Command::new(&gradlew)
        .arg(gradle_task)
        .args(&gradle_args)
        .arg("--console=plain")
        .arg("-q")
        .current_dir(root)
        .status()
        .expect(
            "./gradlew not found — run from repo root and ensure a JDK is installed\n\
             (Ubuntu: apt-get install default-jdk-headless  |  macOS: brew install --cask temurin)",
        );
    assert!(
        status.success(),
        "./gradlew {gradle_task} failed while compiling picodroid framework classes"
    );
    // A clean'd or half-written tree would otherwise surface later as an
    // opaque include_bytes! error, and a strip that lost a class would surface
    // on device as NoClassDefFound.
    let class_count = collect_files(&classes_dir, "class").len();
    assert!(
        class_count > 0,
        "{} holds no .class files after ./gradlew {gradle_task}",
        classes_dir.display()
    );
    if strip_debug || member_map.is_some() {
        let raw_count = collect_files(&root.join("sdk/build/classes/java/main"), "class").len();
        assert_eq!(
            class_count, raw_count,
            "{gradle_task} produced {class_count} classes but compileJava produced {raw_count}"
        );
    }

    // If the active map covers our package version, shrink into a sibling
    // directory and point the embed step at the shrunk output. Otherwise
    // embed the raw Gradle output.
    // Under a shrink map the files sit at their shrunk paths (`a/XX.class`);
    // keep the reverse map so `framework_class_excludes`, written in original
    // names, still matches.
    let (embed_dir, unshrink) = match apply_active_shrink(out, &classes_dir, root) {
        Some((dir, map)) => (
            dir,
            map.iter_classes()
                .map(|(from, to)| (to.to_string(), from.to_string()))
                .collect::<HashMap<String, String>>(),
        ),
        None => (classes_dir, HashMap::new()),
    };

    let mut class_files = collect_files(&embed_dir, "class");
    class_files.sort();

    let mut entries = String::new();
    let mut dropped: Vec<String> = Vec::new();
    for f in &class_files {
        if let Some(name) = excluded_class_name(f, &embed_dir, excludes, &unshrink) {
            dropped.push(name);
            continue;
        }
        let abs = f
            .canonicalize()
            .unwrap_or_else(|_| f.clone())
            .display()
            .to_string();
        entries.push_str(&format!("    include_bytes!({abs:?}),\n"));
    }

    // Name an exclude that matched nothing: a typo would otherwise look like
    // a working opt-out while the class still ships.
    for want in excludes {
        if !dropped
            .iter()
            .any(|d| d == want || d.starts_with(&format!("{want}$")))
        {
            panic!(
                "framework_class_excludes lists {want:?}, which matches no compiled SDK class \
                 — check the spelling (JVM internal form, e.g. picodroid/json/JSONObject)"
            );
        }
    }

    dropped.sort();
    let dropped_entries: String = dropped.iter().map(|n| format!("    {n:?},\n")).collect();
    let content = format!(
        "pub static FRAMEWORK_CLASSES: &[&[u8]] = &[\n{entries}];\n\
         pub static FRAMEWORK_EXCLUDED_CLASSES: &[&str] = &[\n{dropped_entries}];\n\
         /// True when the embedded classes came from `:sdk:stripClasses` (no\n\
         /// LineNumberTable / SourceFile / StackMapTable), i.e. the firmware was\n\
         /// built with `debug_assertions` off. Pinned to `!cfg!(debug_assertions)`\n\
         /// by a picodroid-core test.\n\
         pub const FRAMEWORK_CLASSES_DEBUG_STRIPPED: bool = {strip_debug};\n"
    );
    fs::write(out.join("framework_classes.rs"), content).unwrap();
}

/// The JVM internal class name of `file` when the board excludes it, else
/// `None`. Inner classes follow their outer class: excluding `a/B` drops
/// `a/B$C` too. `unshrink` maps a shrunk path name back to the original the
/// exclude list is written in (empty when no map is active).
fn excluded_class_name(
    file: &Path,
    embed_dir: &Path,
    excludes: &[String],
    unshrink: &HashMap<String, String>,
) -> Option<String> {
    if excludes.is_empty() {
        return None;
    }
    let rel = file.strip_prefix(embed_dir).ok()?;
    let name = rel
        .with_extension("")
        .to_string_lossy()
        .replace(std::path::MAIN_SEPARATOR, "/");
    let name = unshrink.get(&name).cloned().unwrap_or(name);
    let outer = name.split('$').next().unwrap_or(&name);
    excludes
        .iter()
        .any(|e| e == &name || e == outer)
        .then_some(name)
}

/// If shrinking is enabled and an active map covers the current picodroid
/// version, load it, apply it to `classes_dir`, and return the path holding
/// the shrunk outputs together with the map. Also publishes the map to
/// `target/picodroid/framework-mapping.toml` so `scripts/build-apk.sh` can
/// find it without groping cargo metadata.
///
/// `root` is the repo root (where `Cargo.toml`, `sdk/`, `target/` live).
/// Returns `None` when shrinking is disabled (default) or no map is active —
/// caller embeds raw javac output and the emitted unshrink function is an
/// identity passthrough.
fn apply_active_shrink(
    out: &Path,
    classes_dir: &Path,
    root: &Path,
) -> Option<(PathBuf, class_shrink::mapping::ShrinkMap)> {
    if !shrink_enabled() {
        return None;
    }
    let shrink_maps_dir = root.join("sdk").join("shrink-maps");
    // Root Cargo.toml is a virtual workspace; package version lives in platforms/rp/.
    let cargo_toml = {
        let rp = root.join("platforms/rp/Cargo.toml");
        if rp.exists() {
            rp
        } else {
            root.join("Cargo.toml")
        }
    };
    let pkg_version = read_package_version(&cargo_toml).ok()?;
    let active = resolve_active_map_version(&pkg_version, &shrink_maps_dir);
    if active == "0.0.0" {
        return None;
    }
    let map_path = shrink_maps_dir.join(format!("v{active}.toml"));
    let map = class_shrink::mapping::ShrinkMap::load(&map_path)
        .unwrap_or_else(|e| panic!("failed to load {}: {e}", map_path.display()));
    println!("cargo:rerun-if-changed={}", map_path.display());

    // Publish the map to a stable location for scripts/build-apk.sh.
    let publish_dir = root.join("target").join("picodroid");
    fs::create_dir_all(&publish_dir).ok();
    let _ = fs::copy(&map_path, publish_dir.join("framework-mapping.toml"));

    // Apply to framework classes.
    let shrunk_dir = out.join("framework_classes_shrunk");
    let _ = fs::remove_dir_all(&shrunk_dir);
    class_shrink::shrink::shrink_directory(classes_dir, &shrunk_dir, &map)
        .unwrap_or_else(|e| panic!("framework shrink failed: {e}"));

    Some((shrunk_dir, map))
}

/// Generate the `apk_data()` accessor for the app `.papk`.
///
/// Three shapes:
/// - ARM embedded / no `PICODROID_APK_PATH`: empty slice (the APK lives in
///   the PAPK_FLASH region, see [`embed_papk_flash_init`], or there is none).
/// - Host simulator (`sim` feature): the APK is read from disk at startup —
///   runtime `PICODROID_APK_PATH` wins, falling back to the build-time path.
///   No cargo rerun directives are emitted in this branch, so Java-only
///   rebuilds of the same `.papk` never dirty the Rust build.
/// - Other host builds (e.g. `cargo test`, ESP inline embed): `include_bytes!`
///   of the build-time path, as before.
pub fn embed_apk(out: &Path, is_arm_embedded: bool) {
    let is_sim = env::var("CARGO_FEATURE_SIM").is_ok();

    if is_sim && !is_arm_embedded {
        // Deliberately no rerun-if-changed / rerun-if-env-changed here:
        // neither the .papk bytes nor the env var's build-time value affect
        // the generated code beyond the fallback string.
        let fallback = env::var("PICODROID_APK_PATH").unwrap_or_default();
        // On device the APK lives in flash (XIP) and costs zero heap; the
        // sim must not charge it to the simulated heap either
        // (docs/parity-audit.md APK-01/M3). The RP sim exposes a heap-cap
        // bypass for exactly this class of host-only allocation; the ESP
        // crate has no capped allocator yet, so it gets a no-op.
        let bypass_stmt = if env::var("CARGO_PKG_NAME").as_deref() == Ok("picodroid") {
            "let _flash_xip = crate::sim_allocator::bypass();"
        } else {
            "// (no heap-cap bypass: this crate has no capped sim allocator)"
        };
        let generated = format!(
            "/// Sim builds load the APK from disk at startup; the runtime\n\
             /// `PICODROID_APK_PATH` env var wins over the build-time fallback.\n\
             pub fn apk_data() -> &'static [u8] {{\n\
             \x20   static APK: std::sync::OnceLock<&'static [u8]> = std::sync::OnceLock::new();\n\
             \x20   APK.get_or_init(|| {{\n\
             \x20       {bypass_stmt}\n\
             \x20       let path = std::env::var(\"PICODROID_APK_PATH\")\n\
             \x20           .unwrap_or_else(|_| {fallback:?}.to_string());\n\
             \x20       if path.is_empty() {{\n\
             \x20           panic!(\"no APK: set PICODROID_APK_PATH to a .papk built by ./scripts/build-apk.sh\");\n\
             \x20       }}\n\
             \x20       let bytes = std::fs::read(&path)\n\
             \x20           .unwrap_or_else(|e| panic!(\"cannot read APK at '{{path}}': {{e}}\"));\n\
             \x20       eprintln!(\"[sim] APK loaded from {{path}} ({{}} bytes, flash-modeled: uncounted)\", bytes.len());\n\
             \x20       &*::std::boxed::Box::leak(bytes.into_boxed_slice())\n\
             \x20   }})\n\
             }}\n"
        );
        fs::write(out.join("apk_data.rs"), generated).unwrap();
        return;
    }

    println!("cargo:rerun-if-env-changed=PICODROID_APK_PATH");

    const EMPTY: &[u8] = b"pub fn apk_data() -> &'static [u8] {\n    &[]\n}\n";

    let apk_path = match env::var("PICODROID_APK_PATH") {
        Ok(p) => p,
        Err(_) => {
            fs::write(out.join("apk_data.rs"), EMPTY).unwrap();
            return;
        }
    };

    if is_arm_embedded {
        fs::write(out.join("apk_data.rs"), EMPTY).unwrap();
        return;
    }

    assert!(
        Path::new(&apk_path).exists(),
        "APK file not found: {apk_path}\n\
         Build it first with: ./scripts/build-apk.sh --app <name>"
    );

    let abs_apk_path = std::fs::canonicalize(&apk_path)
        .unwrap_or_else(|e| panic!("Cannot resolve APK path '{apk_path}': {e}"));

    // A corrupt/truncated .papk baked in via include_bytes! would only
    // surface as a parse failure at runtime; fail the build instead.
    let apk_bytes =
        fs::read(&abs_apk_path).unwrap_or_else(|e| panic!("Cannot read APK at '{apk_path}': {e}"));
    if let Err(e) = papk_format::validate_structure(&apk_bytes) {
        panic!("PICODROID_APK_PATH '{apk_path}' is not a structurally valid PAPK: {e}");
    }

    let generated = format!(
        "pub fn apk_data() -> &'static [u8] {{\n    include_bytes!({path:?})\n}}\n",
        path = abs_apk_path.display().to_string(),
    );
    fs::write(out.join("apk_data.rs"), generated).unwrap();

    println!("cargo:rerun-if-changed={}", abs_apk_path.display());
}

/// Build a PAPK flash image (4 KB metadata sector + raw APK bytes) and emit
/// a linker section that places it at `PAPK_FLASH`. Only active for ARM
/// embedded targets with `PICODROID_APK_PATH` set.
pub fn embed_papk_flash_init(out: &Path, is_arm_embedded: bool) {
    let is_sim = env::var("CARGO_FEATURE_SIM").is_ok();
    let apk_path = env::var("PICODROID_APK_PATH").ok();

    if !is_arm_embedded || is_sim || apk_path.is_none() {
        fs::write(out.join("papk_flash_init.rs"), b"").unwrap();
        return;
    }

    let apk_path = apk_path.unwrap();
    let apk_bytes =
        fs::read(&apk_path).unwrap_or_else(|e| panic!("Cannot read APK at '{apk_path}': {e}"));
    // Refuse to bake a corrupt image into PAPK_FLASH — on device this would
    // only surface as an install/boot failure with no host-side clue.
    if let Err(e) = papk_format::validate_structure(&apk_bytes) {
        panic!("PICODROID_APK_PATH '{apk_path}' is not a structurally valid PAPK: {e}");
    }
    let apk_len = apk_bytes.len();

    // Same boot-meta layout the device parses, from the same source — this
    // used to be a hand-assembled copy under a comment claiming they matched.
    use papk_format::flash_image;
    let meta = flash_image::build_meta_page(apk_len as u32);
    let mut image = Vec::with_capacity(flash_image::META_SIZE + apk_len);
    image.extend_from_slice(&meta[..flash_image::HEADER_LEN]);
    image.resize(flash_image::META_SIZE, 0xFF);
    image.extend_from_slice(&apk_bytes);

    let bin_path = out.join("papk_flash_init.bin");
    fs::write(&bin_path, &image)
        .unwrap_or_else(|e| panic!("Cannot write papk_flash_init.bin: {e}"));
    let abs_bin = bin_path.canonicalize().unwrap();
    let total_size = image.len();

    let rs = format!(
        "#[link_section = \".papk_flash_init\"]\n\
         #[used]\n\
         static PAPK_FLASH_INIT: [u8; {total_size}] = *include_bytes!({path:?});\n",
        path = abs_bin.display().to_string()
    );
    fs::write(out.join("papk_flash_init.rs"), rs)
        .unwrap_or_else(|e| panic!("Cannot write papk_flash_init.rs: {e}"));

    // PAPK_FLASH region is defined in memory.x (rp2040) / memory_rp2350.x (rp2350).
    let ld =
        "SECTIONS {\n  .papk_flash_init : {\n    KEEP(*(.papk_flash_init))\n  } > PAPK_FLASH\n}\n";
    let ld_path = out.join("papk_flash_init.x");
    fs::write(&ld_path, ld).unwrap_or_else(|e| panic!("Cannot write papk_flash_init.x: {e}"));
    println!("cargo:rustc-link-arg=-T{}", ld_path.display());

    println!("cargo:rerun-if-changed={apk_path}");
}
