// SPDX-License-Identifier: GPL-3.0-only
//! APK + framework class embedding; PAPK flash-init section generation.

use crate::config::collect_files;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Emit `framework_mapping_version.rs` into `out` declaring the active
/// shrink-map version. Resolves by reading the root `Cargo.toml` version
/// and picking the highest committed `sdk/shrink-maps/v<semver>.toml`
/// whose semver is ≤ that version; falls back to `"0.0.0"` (sentinel
/// meaning "no shrinking") when no map has been cut yet.
///
/// The emitted file exposes `FRAMEWORK_MAP_VERSION: &str`, included by
/// the firmware crate so that `verify_compat` at PAPK load time can
/// reject mismatched apps.
pub fn emit_framework_map_version(out: &Path) {
    // Shrinking is opt-in. Without PICODROID_SHRINK=1 we emit the `0.0.0`
    // sentinel so nothing else in the pipeline touches framework .class
    // bytes — matching Android's "R8 off by default" behavior.
    println!("cargo:rerun-if-env-changed=PICODROID_SHRINK");

    let active = if shrink_enabled() {
        let manifest_dir = env::var("CARGO_MANIFEST_DIR")
            .map(PathBuf::from)
            .expect("CARGO_MANIFEST_DIR must be set during build");
        let cargo_toml = manifest_dir.join("Cargo.toml");
        let shrink_maps_dir = manifest_dir.join("sdk").join("shrink-maps");

        println!("cargo:rerun-if-changed={}", cargo_toml.display());
        println!("cargo:rerun-if-changed={}", shrink_maps_dir.display());

        let pkg_version = read_package_version(&cargo_toml)
            .unwrap_or_else(|e| panic!("failed to read picodroid version: {e}"));
        resolve_active_map_version(&pkg_version, &shrink_maps_dir)
    } else {
        "0.0.0".to_string()
    };

    let content = format!(
        "/// Shrink-map version active for this firmware build. Generated by build.rs.\n\
         pub const FRAMEWORK_MAP_VERSION: &str = {active:?};\n"
    );
    fs::write(out.join("framework_mapping_version.rs"), content)
        .unwrap_or_else(|e| panic!("cannot write framework_mapping_version.rs: {e}"));
}

/// Shrinking is gated on the `PICODROID_SHRINK=1` env var — set by the
/// `--shrink` flag on top-level scripts (build.sh / flash.sh / sim.sh /
/// build-apk.sh). Any value other than `"1"` (including unset) is off.
fn shrink_enabled() -> bool {
    matches!(env::var("PICODROID_SHRINK").as_deref(), Ok("1"))
}

/// Lightweight semver tuple parser — returns `None` on malformed input.
/// Pre-release suffixes (`-rc1`, `+build`) are stripped before comparison.
fn parse_semver(s: &str) -> Option<(u32, u32, u32)> {
    let core = s.split(['-', '+']).next().unwrap_or(s);
    let mut it = core.split('.');
    let major = it.next()?.parse().ok()?;
    let minor = it.next()?.parse().ok()?;
    let patch = it.next()?.parse().ok()?;
    if it.next().is_some() {
        return None;
    }
    Some((major, minor, patch))
}

/// Naive `[package] version = "x.y.z"` extractor to avoid a toml crate
/// dependency in the build script.
fn read_package_version(cargo_toml: &Path) -> Result<String, String> {
    let text = fs::read_to_string(cargo_toml)
        .map_err(|e| format!("failed to read {}: {e}", cargo_toml.display()))?;
    let mut in_package = false;
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_package = trimmed == "[package]";
            continue;
        }
        if !in_package {
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("version") {
            let rest = rest.trim_start().trim_start_matches('=').trim();
            let v = rest.trim_matches(|c| c == '"' || c == '\'');
            if parse_semver(v).is_some() {
                return Ok(v.to_string());
            }
        }
    }
    Err(format!(
        "no [package] version found in {}",
        cargo_toml.display()
    ))
}

fn resolve_active_map_version(pkg_version: &str, shrink_maps_dir: &Path) -> String {
    const UNRELEASED: &str = "0.0.0";
    let Some(pkg) = parse_semver(pkg_version) else {
        return UNRELEASED.to_string();
    };
    let entries = match fs::read_dir(shrink_maps_dir) {
        Ok(e) => e,
        Err(_) => return UNRELEASED.to_string(),
    };
    let mut committed: Vec<(String, (u32, u32, u32))> = Vec::new();
    for entry in entries.flatten() {
        let Some(name) = entry.file_name().to_str().map(|s| s.to_string()) else {
            continue;
        };
        let Some(stem) = name.strip_prefix('v').and_then(|s| s.strip_suffix(".toml")) else {
            continue;
        };
        if let Some(sv) = parse_semver(stem) {
            committed.push((stem.to_string(), sv));
        }
    }
    committed.sort_by_key(|(_, sv)| *sv);
    committed
        .into_iter()
        .rfind(|(_, sv)| *sv <= pkg)
        .map(|(v, _)| v)
        .unwrap_or_else(|| UNRELEASED.to_string())
}

/// Compile picodroid framework Java sources with `javac`, optionally apply
/// the active shrink map, and embed each `.class` file as a `&'static [u8]`
/// into `framework_classes.rs`.
///
/// Shrinking is only triggered when [`resolve_active_map_version`] returns
/// a version other than the `"0.0.0"` sentinel *and* a matching map file
/// exists. When shrinking runs, this function also writes
/// `framework_unshrink.rs` — a reverse-translation table from shrunk name
/// back to original, consumed by the native dispatch layer. When shrinking
/// is off the emitted table is an identity passthrough.
pub fn embed_framework_classes(out: &Path) {
    if env::var("PICODROID_APK_PATH").is_err() {
        fs::write(
            out.join("framework_classes.rs"),
            b"pub static FRAMEWORK_CLASSES: &[&[u8]] = &[];\n",
        )
        .unwrap();
        emit_identity_unshrink(out);
        return;
    }

    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set during build"),
    );
    let framework_dir = manifest_dir.join("sdk/java");
    let java_files = collect_files(&framework_dir, "java");
    for f in &java_files {
        println!("cargo:rerun-if-changed={}", f.display());
    }
    // The Gradle build config itself is an input — changes to how :sdk is
    // configured must re-trigger class regeneration.
    for p in [
        "settings.gradle.kts",
        "build.gradle.kts",
        "sdk/build.gradle.kts",
        "buildSrc",
    ] {
        println!("cargo:rerun-if-changed={}", manifest_dir.join(p).display());
    }

    let gradlew = manifest_dir.join(if cfg!(windows) {
        "gradlew.bat"
    } else {
        "gradlew"
    });
    let status = Command::new(&gradlew)
        .arg(":sdk:compileJava")
        .arg("--console=plain")
        .arg("-q")
        .current_dir(&manifest_dir)
        .status()
        .expect(
            "./gradlew not found — run from repo root and ensure a JDK is installed\n\
             (Ubuntu: apt-get install default-jdk-headless  |  macOS: brew install --cask temurin)",
        );
    assert!(
        status.success(),
        "./gradlew :sdk:compileJava failed while compiling picodroid framework classes"
    );
    let classes_dir = manifest_dir.join("sdk/build/classes/java/main");

    // If the active map covers our package version, shrink into a sibling
    // directory and point the embed step at the shrunk output. Otherwise
    // embed the raw Gradle output.
    let embed_dir = apply_active_shrink(out, &classes_dir).unwrap_or(classes_dir);

    let mut class_files = collect_files(&embed_dir, "class");
    class_files.sort();

    let mut entries = String::new();
    for f in &class_files {
        let abs = f
            .canonicalize()
            .unwrap_or_else(|_| f.clone())
            .display()
            .to_string();
        entries.push_str(&format!("    include_bytes!({abs:?}),\n"));
    }

    let content = format!("pub static FRAMEWORK_CLASSES: &[&[u8]] = &[\n{entries}];\n");
    fs::write(out.join("framework_classes.rs"), content).unwrap();
}

/// If shrinking is enabled and an active map covers the current picodroid
/// version, load it, apply it to `classes_dir`, and return the path holding
/// the shrunk outputs. Also publishes the map to
/// `target/picodroid/framework-mapping.toml` so `scripts/build-apk.sh` can
/// find it without groping cargo metadata, and emits `framework_unshrink.rs`
/// with a reverse-translation function.
///
/// Returns `None` when shrinking is disabled (default) or no map is active —
/// caller embeds raw javac output and the emitted unshrink function is an
/// identity passthrough.
fn apply_active_shrink(out: &Path, classes_dir: &Path) -> Option<PathBuf> {
    if !shrink_enabled() {
        emit_identity_unshrink(out);
        return None;
    }
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").ok()?);
    let shrink_maps_dir = manifest_dir.join("sdk").join("shrink-maps");
    let cargo_toml = manifest_dir.join("Cargo.toml");
    let pkg_version = read_package_version(&cargo_toml).ok()?;
    let active = resolve_active_map_version(&pkg_version, &shrink_maps_dir);
    if active == "0.0.0" {
        emit_identity_unshrink(out);
        return None;
    }
    let map_path = shrink_maps_dir.join(format!("v{active}.toml"));
    let map = class_shrink::mapping::ShrinkMap::load(&map_path)
        .unwrap_or_else(|e| panic!("failed to load {}: {e}", map_path.display()));
    println!("cargo:rerun-if-changed={}", map_path.display());

    // Publish the map to a stable location for scripts/build-apk.sh.
    let publish_dir = manifest_dir.join("target").join("picodroid");
    fs::create_dir_all(&publish_dir).ok();
    let _ = fs::copy(&map_path, publish_dir.join("framework-mapping.toml"));

    // Apply to framework classes.
    let shrunk_dir = out.join("framework_classes_shrunk");
    let _ = fs::remove_dir_all(&shrunk_dir);
    class_shrink::shrink::shrink_directory(classes_dir, &shrunk_dir, &map)
        .unwrap_or_else(|e| panic!("framework shrink failed: {e}"));

    emit_unshrink_table(out, &map);
    Some(shrunk_dir)
}

/// Emit identity `unshrink_class` / `shrink_class` functions — used when no
/// shrink map is active. Returns input verbatim in both directions.
fn emit_identity_unshrink(out: &Path) {
    let content = "/// Reverse-translate a shrunk class name back to its original form. \n\
                   /// No-shrink build: identity passthrough.\n\
                   pub fn unshrink_class(name: &str) -> &str { name }\n\
                   \n\
                   /// Forward-translate an original class name to its shrunk form. \n\
                   /// No-shrink build: identity passthrough.\n\
                   pub fn shrink_class(name: &str) -> &str { name }\n";
    fs::write(out.join("framework_unshrink.rs"), content).unwrap();
}

/// Emit `unshrink_class` (shrunk → original) and `shrink_class` (original
/// → shrunk) based on the given map. Both use `match` on `&str` — compact
/// and fast for the small framework set.
fn emit_unshrink_table(out: &Path, map: &class_shrink::mapping::ShrinkMap) {
    let mut body = String::new();
    body.push_str(
        "/// Reverse-translate a shrunk class name back to its original form. \n\
         /// Inserted at native-dispatch entry points so match arms in Rust can \n\
         /// continue using the original internal names. Unknown names pass through.\n\
         pub fn unshrink_class(name: &str) -> &str {\n    match name {\n",
    );
    for (from, to) in map.iter_classes() {
        body.push_str(&format!("        {to:?} => {from:?},\n"));
    }
    body.push_str("        other => other,\n    }\n}\n\n");

    body.push_str(
        "/// Forward-translate an original class name to its shrunk form. \n\
         /// Used at `jvm.invoke_instance` / `invoke_instance_with_args` call sites \n\
         /// that hardcode original framework class names — the loaded classes use \n\
         /// the shrunk form, so lookups would otherwise miss.\n\
         pub fn shrink_class(name: &str) -> &str {\n    match name {\n",
    );
    for (from, to) in map.iter_classes() {
        body.push_str(&format!("        {from:?} => {to:?},\n"));
    }
    body.push_str("        other => other,\n    }\n}\n");
    fs::write(out.join("framework_unshrink.rs"), body).unwrap();
}

/// Embed a pre-built `.papk` file into the firmware as `APK_DATA`.
/// For ARM targets the APK lives in the PAPK_FLASH region (see
/// [`embed_papk_flash_init`]), so this emits an empty stub there.
pub fn embed_apk(out: &Path, is_arm_embedded: bool) {
    println!("cargo:rerun-if-env-changed=PICODROID_APK_PATH");

    let apk_path = match env::var("PICODROID_APK_PATH") {
        Ok(p) => p,
        Err(_) => {
            fs::write(
                out.join("apk_data.rs"),
                b"pub static APK_DATA: &[u8] = &[];\n",
            )
            .unwrap();
            return;
        }
    };

    if is_arm_embedded {
        fs::write(
            out.join("apk_data.rs"),
            b"pub static APK_DATA: &[u8] = &[];\n",
        )
        .unwrap();
        return;
    }

    assert!(
        Path::new(&apk_path).exists(),
        "APK file not found: {apk_path}\n\
         Build it first with: ./scripts/build-apk.sh --app <name>"
    );

    let abs_apk_path = std::fs::canonicalize(&apk_path)
        .unwrap_or_else(|e| panic!("Cannot resolve APK path '{apk_path}': {e}"));

    let generated = format!(
        "pub static APK_DATA: &[u8] = include_bytes!({path:?});\n",
        path = abs_apk_path.display().to_string(),
    );
    fs::write(out.join("apk_data.rs"), generated).unwrap();

    println!("cargo:rerun-if-changed={}", abs_apk_path.display());
}

/// Build a PAPK flash image (4 KB metadata sector + raw APK bytes) and emit
/// a linker section that places it at `PAPK_FLASH`. Only active for ARM
/// embedded targets with `PICODROID_APK_PATH` set.
pub fn embed_papk_flash_init(out: &Path, is_arm_embedded: bool) {
    let is_sim = env::var("CARGO_FEATURE_SIM").is_ok();
    let apk_path = env::var("PICODROID_APK_PATH").ok();

    if !is_arm_embedded || is_sim || apk_path.is_none() {
        fs::write(out.join("papk_flash_init.rs"), b"").unwrap();
        return;
    }

    let apk_path = apk_path.unwrap();
    let apk_bytes =
        fs::read(&apk_path).unwrap_or_else(|e| panic!("Cannot read APK at '{apk_path}': {e}"));
    let apk_len = apk_bytes.len();

    // Layout matches read_flash_papk() on-device.
    const PAPK_FLASH_MAGIC: u32 = 0x5044_4231; // "PDB1"
    const META_SIZE: usize = 4096;
    let mut image = Vec::with_capacity(META_SIZE + apk_len);
    image.extend_from_slice(&PAPK_FLASH_MAGIC.to_le_bytes());
    image.extend_from_slice(&0u32.to_le_bytes()); // flags
    image.extend_from_slice(&(apk_len as u32).to_le_bytes()); // len
    image.resize(META_SIZE, 0xFF);
    image.extend_from_slice(&apk_bytes);

    let bin_path = out.join("papk_flash_init.bin");
    fs::write(&bin_path, &image)
        .unwrap_or_else(|e| panic!("Cannot write papk_flash_init.bin: {e}"));
    let abs_bin = bin_path.canonicalize().unwrap();
    let total_size = image.len();

    let rs = format!(
        "#[link_section = \".papk_flash_init\"]\n\
         #[used]\n\
         static PAPK_FLASH_INIT: [u8; {total_size}] = *include_bytes!({path:?});\n",
        path = abs_bin.display().to_string()
    );
    fs::write(out.join("papk_flash_init.rs"), rs)
        .unwrap_or_else(|e| panic!("Cannot write papk_flash_init.rs: {e}"));

    // PAPK_FLASH region is defined in memory.x (rp2040) / memory_rp2350.x (rp2350).
    let ld =
        "SECTIONS {\n  .papk_flash_init : {\n    KEEP(*(.papk_flash_init))\n  } > PAPK_FLASH\n}\n";
    let ld_path = out.join("papk_flash_init.x");
    fs::write(&ld_path, ld).unwrap_or_else(|e| panic!("Cannot write papk_flash_init.x: {e}"));
    println!("cargo:rustc-link-arg=-T{}", ld_path.display());

    println!("cargo:rerun-if-changed={apk_path}");
}
