// SPDX-License-Identifier: GPL-3.0-only
package picodroid

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*

/**
 * Generates `NetTestConfig.java` carrying the build-time network-test target
 * host, so networking examples can default to loopback in the repo yet be
 * pointed at a real host (the HIL host's LAN IP, a dev machine) without a
 * source edit — NET-7 in docs/networking-followups-2026-08.md.
 *
 * The host value comes from the `picodroidNetTestHost` Gradle property,
 * falling back to the `PICODROID_NET_TEST_HOST` environment variable, then
 * loopback. Scripts should prefer the per-invocation property: a warm Gradle
 * daemon keeps its original environment, so env-only plumbing goes stale
 * (the PICODROID_SHRINK lesson, 81b6b7c).
 */
abstract class GenerateNetTestConfigTask : DefaultTask() {
    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val host: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun run() {
        val pkg = packageName.get()
        val out = outputDir.get().asFile
        out.deleteRecursively()
        val pkgDir = out.resolve(pkg.replace('.', '/'))
        pkgDir.mkdirs()

        val sb = StringBuilder()
        sb.append("// Generated by picodroid — do not edit.\n")
        sb.append("package ").append(pkg).append(";\n\n")
        sb.append("/** Build-time network-test target (picodroidNetTestHost / PICODROID_NET_TEST_HOST). */\n")
        sb.append("public final class NetTestConfig {\n")
        sb.append("    private NetTestConfig() {}\n\n")
        sb.append("    /** Hostname or dotted-quad IPv4 of the test host (default loopback). */\n")
        sb.append("    public static final String HOST = \"").append(host.get()).append("\";\n")
        sb.append("}\n")

        pkgDir.resolve("NetTestConfig.java").writeText(sb.toString())
    }
}
