// SPDX-License-Identifier: GPL-3.0-only
package picodroid

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*

/**
 * Generates `<package>/BuildConfig.java` from the fields a
 * [`picodroidBuildConfig`][BuildConfigExtension] block declares — Android's
 * `BuildConfig`, reduced to string constants. Same second-srcDir shape as
 * [GenerateNetTestConfigTask].
 */
abstract class GenerateBuildConfigTask : DefaultTask() {
    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val fields: MapProperty<String, String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun run() {
        val pkg = packageName.get()
        val out = outputDir.get().asFile
        out.deleteRecursively()
        val pkgDir = out.resolve(pkg.replace('.', '/'))
        pkgDir.mkdirs()

        val sb = StringBuilder()
        sb.append("// Generated by picodroid — do not edit.\n")
        sb.append("package ").append(pkg).append(";\n\n")
        sb.append("/** Build-time constants from the picodroidBuildConfig block. */\n")
        sb.append("public final class BuildConfig {\n")
        sb.append("    private BuildConfig() {}\n")
        for ((name, value) in fields.get().toSortedMap()) {
            require(name.matches(Regex("[A-Za-z_][A-Za-z0-9_]*"))) {
                "picodroidBuildConfig: '$name' is not a Java identifier"
            }
            sb.append("\n    public static final String ").append(name)
                .append(" = \"").append(javaEscape(value)).append("\";\n")
        }
        sb.append("}\n")
        pkgDir.resolve("BuildConfig.java").writeText(sb.toString())
    }

    private fun javaEscape(s: String): String = buildString {
        for (c in s) {
            when (c) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> if (c < ' ' || c > '~') append(String.format("\\u%04x", c.code)) else append(c)
            }
        }
    }
}
