// SPDX-License-Identifier: GPL-3.0-only
package picodroid

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*

/**
 * Generates `AssetConstants.java` from the app's `assets/` directory so app
 * code can reference bundled assets by a compile-checked constant
 * (`AssetConstants.LOGO`) instead of a bare string literal (`"logo.png"`) —
 * the picodroid analogue of Android's generated `R` class, scoped to assets.
 *
 * The constant *value* is the full filename exactly as papk-pack stores it
 * (e.g. `"logo.png"`), so it stays a drop-in for `setImageSource(...)`. Only
 * `*.png` is scanned, matching papk-pack's asset filter.
 */
abstract class GenerateAssetConstantsTask : DefaultTask() {
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val assetsDir: DirectoryProperty

    @get:Input
    abstract val packageName: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun run() {
        val pkg = packageName.get()
        val assets = assetsDir.get().asFile
            .listFiles { f -> f.isFile && f.name.lowercase().endsWith(".png") }
            ?.map { it.name }
            ?.sorted()
            ?: emptyList()

        // Map a sanitized Java identifier -> the original filename. On a
        // name collision (two files sanitizing to the same identifier) append
        // a numeric suffix and warn, so the build still produces a valid,
        // unambiguous class instead of failing on a duplicate field.
        val used = HashMap<String, String>() // identifier -> source filename
        val fields = ArrayList<Pair<String, String>>() // identifier, filename
        for (name in assets) {
            var ident = sanitize(name)
            if (used.containsKey(ident)) {
                var n = 2
                while (used.containsKey("${ident}_$n")) n++
                logger.warn(
                    "AssetConstants: '$name' and '${used[ident]}' both map to " +
                        "'$ident'; using '${ident}_$n' for '$name'"
                )
                ident = "${ident}_$n"
            }
            used[ident] = name
            fields += ident to name
        }

        val out = outputDir.get().asFile
        out.deleteRecursively()
        val pkgDir = out.resolve(pkg.replace('.', '/'))
        pkgDir.mkdirs()

        val sb = StringBuilder()
        sb.append("// Generated by picodroid — do not edit.\n")
        sb.append("package ").append(pkg).append(";\n\n")
        sb.append("/** Names of the assets bundled from this app's {@code assets/} directory. */\n")
        sb.append("public final class AssetConstants {\n")
        sb.append("    private AssetConstants() {}\n")
        for ((ident, file) in fields) {
            sb.append("\n    /** {@code assets/").append(file).append("} */\n")
            sb.append("    public static final String ").append(ident)
                .append(" = \"").append(file).append("\";\n")
        }
        sb.append("}\n")

        pkgDir.resolve("AssetConstants.java").writeText(sb.toString())
    }

    /**
     * Turn a filename into a SCREAMING_SNAKE_CASE Java identifier: drop the
     * extension, upper-case, replace each run of non-alphanumeric characters
     * with a single underscore, and prefix `_` if the result would start with
     * a digit (or be empty).
     */
    private fun sanitize(filename: String): String {
        val base = filename.substringBeforeLast('.')
        val cleaned = buildString {
            var lastUnderscore = false
            for (c in base) {
                if (c.isLetterOrDigit()) {
                    append(c.uppercaseChar())
                    lastUnderscore = false
                } else if (!lastUnderscore) {
                    append('_')
                    lastUnderscore = true
                }
            }
        }.trim('_')
        if (cleaned.isEmpty()) {
            throw GradleException("asset '$filename' yields an empty identifier")
        }
        return if (cleaned.first().isDigit()) "_$cleaned" else cleaned
    }
}
