// SPDX-License-Identifier: GPL-3.0-only
//! Generator for `sdk/member-names.tsv` — every method and field the SDK
//! declares, in original spelling. `build_support/papk.rs::emit_member_names`
//! turns the `M` rows into the `crate::shrink_names::m` consts that native
//! dispatch and the lifecycle upcalls match SDK method names through, so the
//! file has to exist for a bare `cargo build` (no Gradle, no corpus) and is
//! therefore committed rather than derived at build time.
//!
//! `member_names_are_current` regenerates the text from `FRAMEWORK_CLASSES`
//! and compares it with the committed file; `scripts/gen-api-contract.sh`
//! runs it with `PICODROID_UPDATE_MEMBER_NAMES=1` to rewrite the file. Both
//! shrink lanes of `scripts/test.sh` must produce identical output (names are
//! un-shrunk first).
//!
//! Three guards live alongside it, because the member shrink's correctness
//! rests on two invariants no compiler checks:
//! * `handled_rows_use_member_consts` / `no_sdk_method_literals_in_dispatch`
//!   — Rust matches SDK method names only through `m::`, never as a string
//!   literal (a literal keeps matching in a no-shrink build and silently
//!   stops under `--shrink`);
//! * `no_builtin_name_is_ever_mapped` — no committed map renames a name the
//!   JVM dispatches by literal on arbitrary receivers (`toString`, `run`,
//!   `compare`, …: every `java/**` member in the contract, the builtin
//!   tables, and the interpreter's special cases).
//!
//! Test-only, wired via `#[cfg(test)] #[path]` in `lib.rs` like
//! `api_contract.rs`.

#[cfg(test)]
mod tests {
    use crate::shrink_names::unshrink_member;
    use pico_jvm::class_file::ClassFile;
    use std::collections::BTreeSet;

    const MANIFEST_PATH: &str = "sdk/member-names.tsv";
    const UPDATE_VAR: &str = "PICODROID_UPDATE_MEMBER_NAMES";
    const COMMITTED: &str = include_str!("../../../sdk/member-names.tsv");

    fn utf8(cf: &ClassFile, idx: u16) -> String {
        core::str::from_utf8(cf.cp_utf8(idx).expect("utf8 index"))
            .expect("utf8")
            .to_string()
    }

    /// `(is_method, original name)` for every declared member of every
    /// framework class, `<init>`/`<clinit>` excluded.
    fn collect() -> (BTreeSet<(bool, String)>, usize) {
        let mut rows = BTreeSet::new();
        let mut classes = 0;
        for bytes in crate::framework_classes::FRAMEWORK_CLASSES {
            let cf = ClassFile::parse(bytes).expect("parse framework class");
            classes += 1;
            for m in cf.methods() {
                let name = unshrink_member(&utf8(&cf, m.name_index)).to_string();
                if name.starts_with('<') {
                    continue;
                }
                rows.insert((true, name));
            }
            for f in cf.fields().iter().chain(cf.static_fields()) {
                let name = unshrink_member(&utf8(&cf, f.name_index)).to_string();
                rows.insert((false, name));
            }
        }
        (rows, classes)
    }

    fn render(rows: &BTreeSet<(bool, String)>) -> String {
        let mut out = String::from(
            "# sdk/member-names.tsv — every method (M) and field (F) name the SDK declares.\n\
             #\n\
             # GENERATED by picodroid-core's `member_names_are_current` test\n\
             # (picodroid-core/src/native_handler/member_names.rs); do not edit by hand.\n\
             # Regenerate with\n\
             #     scripts/gen-api-contract.sh\n\
             # after adding, removing or renaming an SDK method or field.\n\
             #\n\
             # build_support/papk.rs turns the M rows into the `shrink_names::m` consts\n\
             # (one per method name; value = the active shrink map's target under\n\
             # --shrink, the original otherwise) that Rust native dispatch and the\n\
             # lifecycle upcalls match SDK method names through.\n",
        );
        for (is_method, name) in rows {
            out.push(if *is_method { 'M' } else { 'F' });
            out.push('\t');
            out.push_str(name);
            out.push('\n');
        }
        out
    }

    /// Method names of the manifest (`M` rows), i.e. every SDK method name.
    fn sdk_method_names() -> BTreeSet<String> {
        COMMITTED
            .lines()
            .filter(|l| l.starts_with("M\t"))
            .map(|l| l[2..].to_string())
            .collect()
    }

    /// Source files that match or invoke SDK method names at runtime.
    fn dispatch_sources() -> Vec<(std::path::PathBuf, String)> {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let mut files = Vec::new();
        fn walk(dir: &std::path::Path, out: &mut Vec<std::path::PathBuf>) {
            for e in std::fs::read_dir(dir).unwrap() {
                let p = e.unwrap().path();
                if p.is_dir() {
                    walk(&p, out);
                } else if p.extension().is_some_and(|x| x == "rs") {
                    out.push(p);
                }
            }
        }
        walk(&root.join("native_handler"), &mut files);
        for f in [
            "dispatch_sites.rs",
            "lifecycle.rs",
            "service_lifecycle.rs",
            "bg_worker.rs",
            "boot.rs",
            "hardware/sensors/mod.rs",
            "graphics/widgets/list_view.rs",
        ] {
            files.push(root.join(f));
        }
        // Original-name tables, test-only by construction.
        let exempt = [
            "method_tables.rs",
            "api_contract.rs",
            "class_registry.rs",
            "member_names.rs",
        ];
        files
            .into_iter()
            .filter(|p| !exempt.contains(&p.file_name().unwrap().to_str().unwrap()))
            .map(|p| {
                let text = std::fs::read_to_string(&p).unwrap();
                (p, text)
            })
            .collect()
    }

    /// Every `ALL_HANDLED` row's method name is matched through `m::` in a
    /// dispatcher source — the rows are original names, the arms must not be.
    #[test]
    fn handled_rows_use_member_consts() {
        let sources = dispatch_sources();
        let mut missing = Vec::new();
        for table in crate::native_method_tables_tests::ALL_HANDLED {
            for &(class, method, _) in *table {
                let needle = format!("m::{method}");
                let found = sources.iter().any(|(_, text)| {
                    text.split(|c: char| !(c.is_alphanumeric() || c == '_' || c == ':'))
                        .any(|tok| tok == needle || tok.ends_with(&format!("::{needle}")))
                });
                if !found {
                    missing.push(format!("{class}.{method}"));
                }
            }
        }
        assert!(
            missing.is_empty(),
            "handled rows whose method is not matched as `m::<name>` anywhere in the \
             dispatch sources (a literal arm would silently stop matching under --shrink): \
             {missing:?}"
        );
    }

    /// No dispatch/upcall source spells an SDK method name as a string
    /// literal. `"<init>"`, `"main"`, `"injectMembers"` and the like are not
    /// SDK methods and stay literals.
    #[test]
    fn no_sdk_method_literals_in_dispatch() {
        let names = sdk_method_names();
        let mut offenders = Vec::new();
        for (path, text) in dispatch_sources() {
            for (lineno, line) in text.lines().enumerate() {
                let mut rest = line;
                while let Some(start) = rest.find('"') {
                    let after = &rest[start + 1..];
                    let Some(end) = after.find('"') else { break };
                    let lit = &after[..end];
                    if names.contains(lit) {
                        offenders.push(format!(
                            "{}:{}: {:?}",
                            path.strip_prefix(env!("CARGO_MANIFEST_DIR"))
                                .unwrap()
                                .display(),
                            lineno + 1,
                            lit
                        ));
                    }
                    rest = &after[end + 1..];
                }
            }
        }
        assert!(
            offenders.is_empty(),
            "SDK method names must be matched via `crate::shrink_names::m::<name>`, not a \
             literal: {offenders:#?}"
        );
    }

    /// Names the JVM dispatches by literal on any receiver — the whole
    /// `java/**` contract plus the interpreter's own special cases — must
    /// never appear as a `[[member]]` source in any committed map.
    #[test]
    fn no_builtin_name_is_ever_mapped() {
        let mut fenced: BTreeSet<String> = BTreeSet::new();
        for table in [
            pico_jvm::native::BUILTIN_METHODS,
            pico_jvm::native::BUILTIN_INTERFACE_METHODS,
            crate::native_method_tables_tests::PLATFORM_BUILTIN_METHODS,
        ] {
            for &(_, rows) in table {
                for &(name, _) in rows {
                    fenced.insert(name.to_string());
                }
            }
        }
        for &(_, name, _) in pico_jvm::native::BUILTIN_SDK_HANDLED {
            fenced.insert(name.to_string());
        }
        for name in [
            "toString",
            "compare",
            "getClass",
            "sort",
            "append",
            "valueOf",
            "format",
            "clone",
            "main",
            "injectMembers",
        ] {
            fenced.insert(name.to_string());
        }
        let contract =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../sdk/api-contract.tsv");
        fenced.extend(class_shrink::shrink::read_contract_member_names(&contract).unwrap());
        assert!(fenced.len() > 80, "fence collapsed: {} names", fenced.len());

        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../sdk/shrink-maps");
        let mut maps = 0;
        for e in std::fs::read_dir(&dir).unwrap() {
            let p = e.unwrap().path();
            if p.extension().and_then(|x| x.to_str()) != Some("toml") {
                continue;
            }
            let map = class_shrink::mapping::ShrinkMap::load(&p).unwrap();
            maps += 1;
            let bad: Vec<&str> = map
                .iter_members()
                .map(|(from, _)| from)
                .filter(|from| fenced.contains(*from))
                .collect();
            assert!(
                bad.is_empty(),
                "{} maps names the runtime matches by literal — never un-keep: {bad:?}",
                p.display()
            );
        }
        assert!(maps > 0);
    }

    /// `compat::MEMBER_SHRINK_FLOOR` is the version of the first committed
    /// map that carries `[[member]]` rows, and every such map records it.
    #[test]
    fn member_floor_matches_committed_maps() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../sdk/shrink-maps");
        let mut with_members: Vec<(String, class_shrink::mapping::ShrinkMap)> = Vec::new();
        for e in std::fs::read_dir(&dir).unwrap() {
            let p = e.unwrap().path();
            if p.extension().and_then(|x| x.to_str()) != Some("toml") {
                continue;
            }
            let map = class_shrink::mapping::ShrinkMap::load(&p).unwrap();
            if map.has_members() {
                let stem = p
                    .file_stem()
                    .unwrap()
                    .to_str()
                    .unwrap()
                    .trim_start_matches('v');
                with_members.push((stem.to_string(), map));
            }
        }
        if with_members.is_empty() {
            return; // no member map cut yet — the floor is a promise, not a fact
        }
        with_members.sort_by_key(|(v, _)| compat::parse_semver(v).unwrap());
        assert_eq!(
            with_members[0].0,
            compat::MEMBER_SHRINK_FLOOR,
            "compat::MEMBER_SHRINK_FLOOR must name the first map with [[member]] rows"
        );
        for (v, map) in &with_members {
            assert_eq!(
                map.member_floor.as_deref(),
                Some(compat::MEMBER_SHRINK_FLOOR),
                "v{v}.toml carries the wrong member-floor"
            );
        }
    }

    #[test]
    fn member_names_are_current() {
        let (rows, classes) = collect();
        assert!(
            classes >= 100,
            "only {classes} framework classes seen — FRAMEWORK_CLASSES is empty (run via \
             scripts/test.sh or scripts/gen-api-contract.sh, which set PICODROID_APK_PATH)"
        );
        let methods = rows.iter().filter(|r| r.0).count();
        assert!(
            methods >= 400,
            "only {methods} method names — a parser regression?"
        );
        for name in [
            "onCreate",
            "nativeCreate",
            "setText",
            "fireClick",
            "dispatchRunnable",
        ] {
            assert!(
                rows.contains(&(true, name.to_string())),
                "expected SDK method {name} missing from the manifest"
            );
        }
        let text = render(&rows);
        if text == COMMITTED {
            return;
        }
        if std::env::var(UPDATE_VAR).as_deref() == Ok("1") {
            let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("..")
                .join(MANIFEST_PATH);
            std::fs::write(&path, &text)
                .unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
            eprintln!("wrote {} ({} rows)", path.display(), rows.len());
            return;
        }
        let first_diff = text
            .lines()
            .zip(COMMITTED.lines())
            .position(|(a, b)| a != b)
            .map(|i| i + 1)
            .unwrap_or(text.lines().count().min(COMMITTED.lines().count()) + 1);
        panic!(
            "{MANIFEST_PATH} is stale (first difference at line {first_diff}); \
             run scripts/gen-api-contract.sh"
        );
    }
}
